##############################################################################
#
#    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
#
#    The material in this file is confidential and contains trade secrets
#    of Vivante Corporation. This is proprietary information owned by
#    Vivante Corporation. No part of this work may be disclosed,
#    reproduced, copied, transmitted, or used in any way for any purpose,
#    without the express written permission of Vivante Corporation.
#
##############################################################################


include ../Makefile.def
OUT = ../bin
NAME = libvg_lite.so
SOURCES = vg_lite_dump.c vg_lite.c vg_lite_path.c vg_lite_matrix.c vg_lite_image.c ../VGLiteKernel/linux/vg_lite_ioctl.c

CFLAGS += -I../inc -I../VGLiteKernel -I.
CFLAGS += -Wno-missing-braces -D_GNU_SOURCE -lpthread -lrt

LIBS += m
LDFLAGS += $(addprefix -l,$(LIBS))
LDFLAGS += -fPIC -shared -Wl,-z,defs

all : $(OUT)/$(NAME)

clean:
	@rm -f $(OUT)/$(NAME)

$(OUT):
	@mkdir $(OUT)

$(OUT)/$(NAME) : $(OUT) $(SOURCES)
	@echo $(CC) $(CFLAGS) -o $@ $(SOURCES) $(LDFLAGS)
	@$(CC) $(CFLAGS) -o $@ $(SOURCES) $(LDFLAGS)
