/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FILES_CENTRAL_PB_H_INCLUDED
#define PB_FILES_CENTRAL_PB_H_INCLUDED
#include "pb_0_4_6.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Platform { 
    Platform_UNDEFINED = 0, 
    Platform_IOS = 1, 
    Platform_ANDROID = 2 
} Platform;

/* Struct definitions */
typedef struct _GetCentralInformation { 
    char dummy_field;
} GetCentralInformation;

typedef struct _CentralInformation { 
    char name[32];
    Platform platform;
} CentralInformation;


/* Helper constants for enums */
#define _Platform_MIN Platform_UNDEFINED
#define _Platform_MAX Platform_ANDROID
#define _Platform_ARRAYSIZE ((Platform)(Platform_ANDROID+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CentralInformation_init_default          {"", _Platform_MIN}
#define GetCentralInformation_init_default       {0}
#define CentralInformation_init_zero             {"", _Platform_MIN}
#define GetCentralInformation_init_zero          {0}

/* Field tags (for use in manual encoding/decoding) */
#define CentralInformation_name_tag              1
#define CentralInformation_platform_tag          2

/* Struct field encoding specification for nanopb */
#define CentralInformation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UENUM,    platform,          2)
#define CentralInformation_CALLBACK NULL
#define CentralInformation_DEFAULT NULL

#define GetCentralInformation_FIELDLIST(X, a) \

#define GetCentralInformation_CALLBACK NULL
#define GetCentralInformation_DEFAULT NULL

extern const pb_msgdesc_t CentralInformation_msg;
extern const pb_msgdesc_t GetCentralInformation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CentralInformation_fields &CentralInformation_msg
#define GetCentralInformation_fields &GetCentralInformation_msg

/* Maximum encoded size of messages (where known) */
#define CentralInformation_size                  35
#define GetCentralInformation_size               0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
