/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FILES_COMMON_PB_H_INCLUDED
#define PB_FILES_COMMON_PB_H_INCLUDED
#include <pb_0_4_6.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Transport { 
    Transport_BLUETOOTH_LOW_ENERGY = 0, 
    Transport_BLUETOOTH_RFCOMM = 1, 
    Transport_BLUETOOTH_IAP = 2 
} Transport;

typedef enum _ErrorCode { 
    ErrorCode_SUCCESS = 0, 
    ErrorCode_UNKNOWN = 1, 
    ErrorCode_INTERNAL = 2, 
    ErrorCode_UNSUPPORTED = 3, 
    ErrorCode_USER_CANCELLED = 4, 
    ErrorCode_NOT_FOUND = 5, 
    ErrorCode_INVALID = 6, 
    ErrorCode_BUSY = 7 
} ErrorCode;

typedef enum _SpeechInitiationType { 
    SpeechInitiationType_PRESS_AND_HOLD = 0, 
    SpeechInitiationType_TAP = 1, 
    SpeechInitiationType_WAKEWORD = 2 
} SpeechInitiationType;

/* Helper constants for enums */
#define _Transport_MIN Transport_BLUETOOTH_LOW_ENERGY
#define _Transport_MAX Transport_BLUETOOTH_IAP
#define _Transport_ARRAYSIZE ((Transport)(Transport_BLUETOOTH_IAP+1))

#define _ErrorCode_MIN ErrorCode_SUCCESS
#define _ErrorCode_MAX ErrorCode_BUSY
#define _ErrorCode_ARRAYSIZE ((ErrorCode)(ErrorCode_BUSY+1))

#define _SpeechInitiationType_MIN SpeechInitiationType_PRESS_AND_HOLD
#define _SpeechInitiationType_MAX SpeechInitiationType_WAKEWORD
#define _SpeechInitiationType_ARRAYSIZE ((SpeechInitiationType)(SpeechInitiationType_WAKEWORD+1))


#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
