/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FILES_STATE_PB_H_INCLUDED
#define PB_FILES_STATE_PB_H_INCLUDED
#include <pb_0_4_6.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _GetState { 
    uint32_t feature;
} GetState;

typedef struct _State { 
    uint32_t feature;
    pb_size_t which_value;
    union {
        bool boolean;
        uint32_t integer;
    } value;
} State;

typedef struct _SetState { 
    bool has_state;
    State state;
} SetState;

typedef struct _SynchronizeState { 
    bool has_state;
    State state;
} SynchronizeState;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define State_init_default                       {0, 0, {0}}
#define GetState_init_default                    {0}
#define SetState_init_default                    {false, State_init_default}
#define SynchronizeState_init_default            {false, State_init_default}
#define State_init_zero                          {0, 0, {0}}
#define GetState_init_zero                       {0}
#define SetState_init_zero                       {false, State_init_zero}
#define SynchronizeState_init_zero               {false, State_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define GetState_feature_tag                     1
#define State_feature_tag                        1
#define State_boolean_tag                        2
#define State_integer_tag                        3
#define SetState_state_tag                       1
#define SynchronizeState_state_tag               1

/* Struct field encoding specification for nanopb */
#define State_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   feature,           1) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean,value.boolean),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,integer,value.integer),   3)
#define State_CALLBACK NULL
#define State_DEFAULT NULL

#define GetState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   feature,           1)
#define GetState_CALLBACK NULL
#define GetState_DEFAULT NULL

#define SetState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  state,             1)
#define SetState_CALLBACK NULL
#define SetState_DEFAULT NULL
#define SetState_state_MSGTYPE State

#define SynchronizeState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  state,             1)
#define SynchronizeState_CALLBACK NULL
#define SynchronizeState_DEFAULT NULL
#define SynchronizeState_state_MSGTYPE State

extern const pb_msgdesc_t State_msg;
extern const pb_msgdesc_t GetState_msg;
extern const pb_msgdesc_t SetState_msg;
extern const pb_msgdesc_t SynchronizeState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define State_fields &State_msg
#define GetState_fields &GetState_msg
#define SetState_fields &SetState_msg
#define SynchronizeState_fields &SynchronizeState_msg

/* Maximum encoded size of messages (where known) */
#define GetState_size                            6
#define SetState_size                            14
#define State_size                               12
#define SynchronizeState_size                    14

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
