##############################################################################
#
#    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
#
#    The material in this file is confidential and contains trade secrets
#    of Vivante Corporation. This is proprietary information owned by
#    Vivante Corporation. No part of this work may be disclosed,
#    reproduced, copied, transmitted, or used in any way for any purpose,
#    without the express written permission of Vivante Corporation.
#
##############################################################################


include ../../Makefile.def

OUT = ../../bin
NAME = libvg_lite_util.so
SOURCES = \
	load_png.c save_png.c fbdev.c vg_lite_util.c \
	$(wildcard libpng-1.6.1/*.c) \
	$(wildcard zlib-1.2.7/*.c)

CFLAGS += -I$(SDK_DIR)/inc -I.
CFLAGS += -Ilibpng-1.6.1 -Izlib-1.2.7
CFLAGS += -DHAVE_FBDEV

LIBS += vg_lite m
LDFLAGS += -L$(SDK_DIR)/drivers -L$(OUT) $(addprefix -l,$(LIBS))
LDFLAGS += -fPIC -shared  -Wl,-z,defs

all : $(OUT)/$(NAME)

clean :
	@rm -f $(OUT)/$(NAME)

$(OUT) :
	@mkdir $(OUT)

$(OUT)/$(NAME) : $(OUT) $(SOURCES)
	@echo $(CC) $(CFLAGS) -o $@ $(SOURCES) $(LDFLAGS)
	@$(CC) $(CFLAGS) -o $@ $(SOURCES) $(LDFLAGS)
