/***************************************************************************
 *
 * Copyright 2015-2021 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __REG_CAPSENSOR__BEST1502X_H__
#define __REG_CAPSENSOR__BEST1502X_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "plat_types.h"

struct CAPSENSOR_T {
    __IO uint32_t REG_000;
    __IO uint32_t REG_004;
    __IO uint32_t REG_008;
    __IO uint32_t REG_00C;
    __IO uint32_t REG_010;
    __IO uint32_t REG_014;
    __IO uint32_t REG_018;
    __IO uint32_t REG_01C;
    __IO uint32_t REG_020;
    __IO uint32_t REG_024;
    __IO uint32_t REG_028;
    __IO uint32_t REG_02C;
    __IO uint32_t REG_030;
    __IO uint32_t REG_034;
    __IO uint32_t REG_038;
    __IO uint32_t REG_03C;
    __IO uint32_t REG_040;
    __IO uint32_t REG_044;
    __IO uint32_t REG_048;
    __IO uint32_t REG_04C;
    __IO uint32_t REG_050;
    __IO uint32_t REG_054;
    __IO uint32_t REG_058;
    __IO uint32_t REG_05C;
    __IO uint32_t REG_060;
    __IO uint32_t REG_064;
    __IO uint32_t REG_068;
    __IO uint32_t REG_06C;
    __IO uint32_t REG_070;
    __IO uint32_t REG_074;
    __IO uint32_t REG_078;
    __IO uint32_t REG_07C;
    __IO uint32_t REG_080;
    __IO uint32_t REG_084;
    __IO uint32_t REG_088;
    __IO uint32_t REG_08C;
    __IO uint32_t REG_090;
    __IO uint32_t REG_094;
    __IO uint32_t REG_098;
    __IO uint32_t REG_09C;
    __IO uint32_t REG_0A0;
    __IO uint32_t REG_0A4;
    __IO uint32_t REG_0A8;
};

// REG_000
#define CAP_SENS_REG_STG_NUM_SHIFT            28
#define CAP_SENS_REG_STG_NUM_MASK             (0x7 << CAP_SENS_REG_STG_NUM_SHIFT)
#define CAP_SENS_REG_STG_NUM(n)               (((n) & CAP_SENS_REG_STG_NUM_MASK) >> CAP_SENS_REG_STG_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT    24
#define CAP_SENS_REG_INTVL1_CONV_NUM_MASK     (0xF << CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_CONV_NUM(n)       (((n) & CAP_SENS_REG_INTVL1_CONV_NUM_MASK) >> CAP_SENS_REG_INTVL1_CONV_NUM_SHIFT)
#define CAP_SENS_REG_INTVL1_SHIFT             16
#define CAP_SENS_REG_INTVL1_MASK              (0xFF << CAP_SENS_REG_INTVL1_SHIFT)
#define CAP_SENS_REG_INTVL1(n)                (((n) & CAP_SENS_REG_INTVL1_MASK) >> CAP_SENS_REG_INTVL1_SHIFT)
#define CAP_SENS_REG_INTVL2_SHIFT             0
#define CAP_SENS_REG_INTVL2_MASK              (0xFFFF << CAP_SENS_REG_INTVL2_SHIFT)
#define CAP_SENS_REG_INTVL2(n)                (((n) & CAP_SENS_REG_INTVL2_MASK) >> CAP_SENS_REG_INTVL2_SHIFT)

// REG_004
#define CAP_SENS_REG_CFG_STG3_SHIFT           24
#define CAP_SENS_REG_CFG_STG3_MASK            (0x1F << CAP_SENS_REG_CFG_STG3_SHIFT)
#define CAP_SENS_REG_CFG_STG3(n)              (((n) & CAP_SENS_REG_CFG_STG3_MASK) >> CAP_SENS_REG_CFG_STG3_SHIFT)
#define CAP_SENS_REG_CFG_STG2_SHIFT           16
#define CAP_SENS_REG_CFG_STG2_MASK            (0x1F << CAP_SENS_REG_CFG_STG2_SHIFT)
#define CAP_SENS_REG_CFG_STG2(n)              (((n) & CAP_SENS_REG_CFG_STG2_MASK) >> CAP_SENS_REG_CFG_STG2_SHIFT)
#define CAP_SENS_REG_CFG_STG1_SHIFT           8
#define CAP_SENS_REG_CFG_STG1_MASK            (0x1F << CAP_SENS_REG_CFG_STG1_SHIFT)
#define CAP_SENS_REG_CFG_STG1(n)              (((n) & CAP_SENS_REG_CFG_STG1_MASK) >> CAP_SENS_REG_CFG_STG1_SHIFT)
#define CAP_SENS_REG_CFG_STG0_SHIFT           0
#define CAP_SENS_REG_CFG_STG0_MASK            (0x1F << CAP_SENS_REG_CFG_STG0_SHIFT)
#define CAP_SENS_REG_CFG_STG0(n)              (((n) & CAP_SENS_REG_CFG_STG0_MASK) >> CAP_SENS_REG_CFG_STG0_SHIFT)

// REG_008
#define CAP_SENS_REG_CFG_STG7_SHIFT           24
#define CAP_SENS_REG_CFG_STG7_MASK            (0x1F << CAP_SENS_REG_CFG_STG7_SHIFT)
#define CAP_SENS_REG_CFG_STG7(n)              (((n) & CAP_SENS_REG_CFG_STG7_MASK) >> CAP_SENS_REG_CFG_STG7_SHIFT)
#define CAP_SENS_REG_CFG_STG6_SHIFT           16
#define CAP_SENS_REG_CFG_STG6_MASK            (0x1F << CAP_SENS_REG_CFG_STG6_SHIFT)
#define CAP_SENS_REG_CFG_STG6(n)              (((n) & CAP_SENS_REG_CFG_STG6_MASK) >> CAP_SENS_REG_CFG_STG6_SHIFT)
#define CAP_SENS_REG_CFG_STG5_SHIFT           8
#define CAP_SENS_REG_CFG_STG5_MASK            (0x1F << CAP_SENS_REG_CFG_STG5_SHIFT)
#define CAP_SENS_REG_CFG_STG5(n)              (((n) & CAP_SENS_REG_CFG_STG5_MASK) >> CAP_SENS_REG_CFG_STG5_SHIFT)
#define CAP_SENS_REG_CFG_STG4_SHIFT           0
#define CAP_SENS_REG_CFG_STG4_MASK            (0x1F << CAP_SENS_REG_CFG_STG4_SHIFT)
#define CAP_SENS_REG_CFG_STG4(n)              (((n) & CAP_SENS_REG_CFG_STG4_MASK) >> CAP_SENS_REG_CFG_STG4_SHIFT)

// REG_00C
#define CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN1_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN1(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN1_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN0_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN0(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN0_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN0_SHIFT)

// REG_010
#define CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN3_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN3(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN3_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN2_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN2(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN2_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN2_SHIFT)

// REG_014
#define CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN5(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN4_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN4(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN4_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN4_SHIFT)

// REG_018
#define CAP_SENS_REG_CAP_OFFSET_CHAN7_SHIFT            16
#define CAP_SENS_REG_CAP_OFFSET_CHAN7_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN7(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN5_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT            0
#define CAP_SENS_REG_CAP_OFFSET_CHAN6_MASK             (0xFFFF << CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_OFFSET_CHAN6(n)               (((n) & CAP_SENS_REG_CAP_OFFSET_CHAN6_MASK) >> CAP_SENS_REG_CAP_OFFSET_CHAN6_SHIFT)

// REG_01C
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT        8
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_MASK         (0xFF << CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM(n)           (((n) & CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_MASK) >> CAP_SENS_REG_TCH_ACTIVE_NOISE_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT          0
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_MASK           (0xFF << CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT)
#define CAP_SENS_REG_TCH_ACTIVE_CAP_NUM(n)             (((n) & CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_MASK) >> CAP_SENS_REG_TCH_ACTIVE_CAP_NUM_SHIFT)

// REG_020
#define CAP_SENS_REG_CAP_THR_CHAN1_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN1_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN1(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN1_MASK) >> CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN0_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN0_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN0(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN0_MASK) >> CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)

// REG_024
#define CAP_SENS_REG_CAP_THR_CHAN3_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN3_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN3(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN3_MASK) >> CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN2_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN2_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN2(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN2_MASK) >> CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)

// REG_028
#define CAP_SENS_REG_CAP_THR_CHAN5_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN5_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN5(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN5_MASK) >> CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN4_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN4_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN4(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN4_MASK) >> CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)

// REG_02C
#define CAP_SENS_REG_CAP_THR_CHAN7_SHIFT        16
#define CAP_SENS_REG_CAP_THR_CHAN7_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN7(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN7_MASK) >> CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN6_SHIFT        0
#define CAP_SENS_REG_CAP_THR_CHAN6_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_THR_CHAN6(n)           (((n) & CAP_SENS_REG_CAP_THR_CHAN6_MASK) >> CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)

// REG_030
#define CAP_SENS_REG_CAP_THR_DIFF1_SHIFT        16
#define CAP_SENS_REG_CAP_THR_DIFF1_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF1_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF1(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF1_MASK) >> CAP_SENS_REG_CAP_THR_DIFF1_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF0_SHIFT        0
#define CAP_SENS_REG_CAP_THR_DIFF0_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF0_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF0(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF0_MASK) >> CAP_SENS_REG_CAP_THR_DIFF0_SHIFT)

// REG_034
#define CAP_SENS_REG_CAP_THR_DIFF3_SHIFT        16
#define CAP_SENS_REG_CAP_THR_DIFF3_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF3_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF3(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF3_MASK) >> CAP_SENS_REG_CAP_THR_DIFF3_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF2_SHIFT        0
#define CAP_SENS_REG_CAP_THR_DIFF2_MASK         (0xFFFF << CAP_SENS_REG_CAP_THR_DIFF2_SHIFT)
#define CAP_SENS_REG_CAP_THR_DIFF2(n)           (((n) & CAP_SENS_REG_CAP_THR_DIFF2_MASK) >> CAP_SENS_REG_CAP_THR_DIFF2_SHIFT)

// REG_038
#define CAP_SENS_REG_NOISE_THR_CHAN1_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN1_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN1(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN1_MASK) >> CAP_SENS_REG_CAP_THR_CHAN1_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN0_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN0_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN0(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN0_MASK) >> CAP_SENS_REG_CAP_THR_CHAN0_SHIFT)

// REG_03C
#define CAP_SENS_REG_NOISE_THR_CHAN3_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN3_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN3(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN3_MASK) >> CAP_SENS_REG_CAP_THR_CHAN3_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN2_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN2_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN2(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN2_MASK) >> CAP_SENS_REG_CAP_THR_CHAN2_SHIFT)

// REG_040
#define CAP_SENS_REG_NOISE_THR_CHAN5_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN5_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN5(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN5_MASK) >> CAP_SENS_REG_CAP_THR_CHAN5_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN4_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN4_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN4(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN4_MASK) >> CAP_SENS_REG_CAP_THR_CHAN4_SHIFT)

// REG_044
#define CAP_SENS_REG_NOISE_THR_CHAN7_SHIFT       16
#define CAP_SENS_REG_NOISE_THR_CHAN7_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN7(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN7_MASK) >> CAP_SENS_REG_CAP_THR_CHAN7_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN6_SHIFT       0
#define CAP_SENS_REG_NOISE_THR_CHAN6_MASK        (0xFFFF << CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)
#define CAP_SENS_REG_NOISE_THR_CHAN6(n)          (((n) & CAP_SENS_REG_CAP_THR_CHAN6_MASK) >> CAP_SENS_REG_CAP_THR_CHAN6_SHIFT)

// REG_048
#define CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT       24
#define CAP_SENS_REG_CHANN_SEL_DIFF3_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF3(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF3_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT       16
#define CAP_SENS_REG_CHANN_SEL_DIFF2_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF2(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF2_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT       8
#define CAP_SENS_REG_CHANN_SEL_DIFF1_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF1(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF1_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT       0
#define CAP_SENS_REG_CHANN_SEL_DIFF0_MASK        (0x3F << CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DIFF0(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DIFF0_MASK) >> CAP_SENS_REG_CHANN_SEL_DIFF0_SHIFT)

// REG_04C
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT       24
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK3(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK3_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT       16
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK2(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK2_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT       8
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK1(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK1_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT       0
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_MASK        (0x1F << CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT)
#define CAP_SENS_REG_CHANN_SEL_DBL_CLICK0(n)          (((n) & CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_MASK) >> CAP_SENS_REG_CHANN_SEL_DBL_CLICK0_SHIFT)

// REG_050
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT    16
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_MASK     (0xFFFF << CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN(n)       (((n) & CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_MASK) >> CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MIN_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT    0
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_MASK     (0xFFFF << CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT)
#define CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX(n)       (((n) & CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_MASK) >> CAP_SENS_REG_CHANN_DBL_CLICK_INTVL_MAX_SHIFT)

// REG_054
#define CAP_SENS_REG_VCORE_PWUP_1            (1 << 28)
#define CAP_SENS_REG_VCORE_PWUP_0            (1 << 27)
#define CAP_SENS_REG_VCORE_PWUP_DR           (1 << 26)
#define CAP_SENS_REG_CDC_CORE_RST            (1 << 25)
#define CAP_SENS_REG_CDC_CORE_RST_DR         (1 << 24)
#define CAP_SENS_REG_CDC_CORE_PWUP           (1 << 21)
#define CAP_SENS_REG_CDC_CORE_PWUP_DR        (1 << 20)
#define CAP_SENS_REG_VREF_PRECHG             (1 << 17)
#define CAP_SENS_REG_VREF_PRECHF_DR          (1 << 16)
#define CAP_SENS_REG_RCOSC_PWUP_1            (1 << 14)
#define CAP_SENS_REG_RCOSC_PWUP_0            (1 << 13)
#define CAP_SENS_REG_RCOSC_PWUP_DR           (1 << 12)
#define CAP_SENS_REG_LDO_PWUP_1              (1 << 10)
#define CAP_SENS_REG_LDO_PWUP_0              (1 << 9)
#define CAP_SENS_REG_LDO_PWUP_DR             (1 << 8)
#define CAP_SENS_REG_VREF_PWUP_1             (1 << 6)
#define CAP_SENS_REG_VREF_PWUP_0             (1 << 5)
#define CAP_SENS_REG_VREF_PWUP_DR            (1 << 4)
#define CAP_SENS_REG_BIAS_PWUP_1             (1 << 2)
#define CAP_SENS_REG_BIAS_PWUP_0             (1 << 1)
#define CAP_SENS_REG_BIAS_PWUP_DR            (1 << 0)

// REG_058
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT    0
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY_MASK     (0xFF << CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT)
#define CAP_SENS_REG_CONV_EN_INITIAL_DLY(n)       (((n) & CAP_SENS_REG_CONV_EN_INITIAL_DLY_MASK) >> CAP_SENS_REG_CONV_EN_INITIAL_DLY_SHIFT)

// REG_05C
#define CAP_SENS_REG_CONV_WAIT_SHIFT               20
#define CAP_SENS_REG_CONV_WAIT_MASK                (0xFF << CAP_SENS_REG_CONV_WAIT_SHIFT)
#define CAP_SENS_REG_CONV_WAIT(n)                  (((n) & CAP_SENS_REG_CONV_WAIT_MASK) >> CAP_SENS_REG_CONV_WAIT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT        16
#define CAP_SENS_REG_CDC_CORE_RST_CNT_MASK         (0xF << CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_RST_CNT(n)           (((n) & CAP_SENS_REG_CDC_CORE_RST_CNT_MASK) >> CAP_SENS_REG_CDC_CORE_RST_CNT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT      8
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT_MASK       (0xFF << CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT)
#define CAP_SENS_REG_CDC_CORE_PWUP_WAIT(n)         (((n) & CAP_SENS_REG_CDC_CORE_PWUP_WAIT_MASK) >> CAP_SENS_REG_CDC_CORE_PWUP_WAIT_SHIFT)
#define CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT         0
#define CAP_SENS_REG_VREF_PRECHG_CNT_MASK          (0xFF << CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT)
#define CAP_SENS_REG_VREF_PRECHG_CNT(n)            (((n) & CAP_SENS_REG_VREF_PRECHG_CNT_MASK) >> CAP_SENS_REG_VREF_PRECHG_CNT_SHIFT)

// REG_060
#define CAP_SENS_REG_CSENSE_RSEL_SHIFT         26
#define CAP_SENS_REG_CSENSE_RSEL_MASK          (0x3 << CAP_SENS_REG_CSENSE_RSEL_SHIFT)
#define CAP_SENS_REG_CSENSE_RSEL(n)            (((n) & CAP_SENS_REG_CSENSE_RSEL_MASK) >> CAP_SENS_REG_CSENSE_RSEL_SHIFT)
#define CAP_SENS_REG_CREF_SEL_SHIFT            22
#define CAP_SENS_REG_CREF_SEL_MASK             (0xF << CAP_SENS_REG_CREF_SEL_SHIFT)
#define CAP_SENS_REG_CREF_SEL(n)               (((n) & CAP_SENS_REG_CREF_SEL_MASK) >> CAP_SENS_REG_CREF_SEL_SHIFT)
#define CAP_SENS_REG_LDO_VREF_ISEL_SHIFT       19
#define CAP_SENS_REG_LDO_VREF_ISEL_MASK        (0x7 << CAP_SENS_REG_LDO_VREF_ISEL_SHIFT)
#define CAP_SENS_REG_LDO_VREF_ISEL(n)          (((n) & CAP_SENS_REG_LDO_VREF_ISEL_MASK) >> CAP_SENS_REG_LDO_VREF_ISEL_SHIFT)
#define CAP_SENS_REG_LDO_VSEL_SHIFT            16
#define CAP_SENS_REG_LDO_VSEL_MASK             (0x7 << CAP_SENS_REG_LDO_VSEL_SHIFT)
#define CAP_SENS_REG_LDO_VSEL(n)               (((n) & CAP_SENS_REG_LDO_VSEL_MASK) >> CAP_SENS_REG_LDO_VSEL_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_1_SHIFT          12
#define CAP_SENS_REG_LDO_ISEL_1_MASK           (0xF << CAP_SENS_REG_LDO_ISEL_1_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_1(n)             (((n) & CAP_SENS_REG_LDO_ISEL_1_MASK) >> CAP_SENS_REG_LDO_ISEL_1_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_0_SHIFT          8
#define CAP_SENS_REG_LDO_ISEL_0_MASK           (0xF << CAP_SENS_REG_LDO_ISEL_0_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_0(n)             (((n) & CAP_SENS_REG_LDO_ISEL_0_MASK) >> CAP_SENS_REG_LDO_ISEL_0_SHIFT)
#define CAP_SENS_REG_LDO_ISEL_DR               (1 << 7)
#define CAP_SENS_REG_BIAS_ISEL_1_SHIFT         4
#define CAP_SENS_REG_BIAS_ISEL_1_MASK          (0x7 << CAP_SENS_REG_BIAS_ISEL_1_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_1(n)            (((n) & CAP_SENS_REG_BIAS_ISEL_1_MASK) >> CAP_SENS_REG_BIAS_ISEL_1_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_0_SHIFT         1
#define CAP_SENS_REG_BIAS_ISEL_0_MASK          (0x7 << CAP_SENS_REG_BIAS_ISEL_0_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_0(n)            (((n) & CAP_SENS_REG_BIAS_ISEL_0_MASK) >> CAP_SENS_REG_BIAS_ISEL_0_SHIFT)
#define CAP_SENS_REG_BIAS_ISEL_DR              (1 << 0)

// REG_064
#define CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT     19
#define CAP_SENS_REG_SAR_VRES_LOGIC_MASK      (0xF << CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT)
#define CAP_SENS_REG_SAR_VRES_LOGIC(n)        (((n) & CAP_SENS_REG_SAR_VRES_LOGIC_MASK) >> CAP_SENS_REG_SAR_VRES_LOGIC_SHIFT)
#define CAP_SENS_REG_SAR_VRES_DLY_SHIFT       15
#define CAP_SENS_REG_SAR_VRES_DLY_MASK        (0xF << CAP_SENS_REG_SAR_VRES_DLY_SHIFT)
#define CAP_SENS_REG_SAR_VRES_DLY(n)          (((n) & CAP_SENS_REG_SAR_VRES_DLY_MASK) >> CAP_SENS_REG_SAR_VRES_DLY_SHIFT)
#define CAP_SENS_REG_SAR_VRES_CMP_SHIFT       11
#define CAP_SENS_REG_SAR_VRES_CMP_MASK        (0xF << CAP_SENS_REG_SAR_VRES_CMP_SHIFT)
#define CAP_SENS_REG_SAR_VRES_CMP(n)          (((n) & CAP_SENS_REG_SAR_VRES_CMP_MASK) >> CAP_SENS_REG_SAR_VRES_CMP_SHIFT)
#define CAP_SENS_REG_SAR_DLY_CTRL             (1 << 10)
#define CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT     8
#define CAP_SENS_REG_RCOSC_FRE_MODE_MASK      (0x3 << CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_MODE(n)        (((n) & CAP_SENS_REG_RCOSC_FRE_MODE_MASK) >> CAP_SENS_REG_RCOSC_FRE_MODE_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT     0
#define CAP_SENS_REG_RCOSC_FRE_TRIM_MASK      (0xFF << CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT)
#define CAP_SENS_REG_RCOSC_FRE_TRIM(n)        (((n) & CAP_SENS_REG_RCOSC_FRE_TRIM_MASK) >> CAP_SENS_REG_RCOSC_FRE_TRIM_SHIFT)

// REG_068
#define CAP_SENS_REG_FIFO_CLR                 (1 << 4)
#define CAP_SENS_REG_SOFT_MODE                (1 << 3)
#define CAP_SENS_REG_TEST_MODE                (1 << 2)
#define CAP_SENS_REG_DMA_EN                   (1 << 1)
#define CAP_SENS_REG_CAP_SENSOR_EN            (1 << 0)

// REG_06C
#define CAP_SENS_REG_RD_DATA_SHIFT            0
#define CAP_SENS_REG_RD_DATA_MASK             (0x7FFF << CAP_SENS_REG_RD_DATA_SHIFT)
#define CAP_SENS_REG_RD_DATA(n)               (((n) & CAP_SENS_REG_RD_DATA_MASK) >> CAP_SENS_REG_RD_DATA_SHIFT)

// REG_070
#define CAP_SENS_REG_FIFO_EMPTY               (1 << 16) 
#define CAP_SENS_REG_FIFO_DATA_CNT_SHIFT      8
#define CAP_SENS_REG_FIFO_DATA_CNT_MASK       (0x3F << CAP_SENS_REG_FIFO_DATA_CNT_SHIFT)
#define CAP_SENS_REG_FIFO_DATA_CNT(n)         (((n) & CAP_SENS_REG_FIFO_DATA_CNT_MASK) >> CAP_SENS_REG_FIFO_DATA_CNT_SHIFT)
#define CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT    0
#define CAP_SENS_REG_FIFO_ALFULL_LVL_MASK     (0x3F << CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT)
#define CAP_SENS_REG_FIFO_ALFULL_LVL(n)       (((n) & CAP_SENS_REG_FIFO_ALFULL_LVL_MASK) >> CAP_SENS_REG_FIFO_ALFULL_LVL_SHIFT)

// REG_074
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT       20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_MASK        (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK(n)          (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT       16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_MASK        (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK(n)          (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT      8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_MASK       (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK(n)         (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT     0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_MASK      (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK(n)        (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_MASK_SHIFT)

// REG_078
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT        20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_MASK         (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR(n)           (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT        16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_MASK         (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR(n)           (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT       8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_MASK        (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR(n)          (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT      0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_MASK       (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR(n)         (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_CLR_SHIFT)

// REG_07C
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT        20
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_MASK         (0xF << CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DBL_CLICK_ACTIVE_INT(n)           (((n) & CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_MASK) >> CAP_SENS_REG_DBL_CLICK_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT        16
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_MASK         (0xF << CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT(n)           (((n) & CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_DIFF_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT       8
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_MASK        (0xFF << CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT(n)          (((n) & CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_NOISE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT      0
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_MASK       (0xFF << CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT)
#define CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT(n)         (((n) & CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_MASK) >> CAP_SENS_REG_SINGLE_CHAN_ACTIVE_INT_SHIFT)

// REG_080
#define CAP_SENS_REG_SAR_TEST_LOCK                     (1 << 12)
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT          8
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE_MASK           (0xF << CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_CONV_CYCLE(n)             (((n) & CAP_SENS_REG_SAR_TST_CONV_CYCLE_MASK) << CAP_SENS_REG_SAR_TST_CONV_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT           4
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE_MASK            (0xF << CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_SMP_CYCLE(n)              (((n) & CAP_SENS_REG_SAR_TST_SMP_CYCLE_MASK) << CAP_SENS_REG_SAR_TST_SMP_CYCLE_SHIFT)
#define CAP_SENS_REG_SAR_TST_DIG_EN                    (1 << 1)
#define CAP_SENS_REG_SAR_TST_EN                        (1 << 0)

// REG_084
#define CAP_SENS_REG_TPORT_SEL_SHIFT              0
#define CAP_SENS_REG_TPORT_SEL_MASK               (0x7 << CAP_SENS_REG_TPORT_SEL_SHIFT)
#define CAP_SENS_REG_TPORT_SEL(n)                 (((n) & CAP_SENS_REG_TPORT_SEL_MASK) << CAP_SENS_REG_TPORT_SEL_SHIFT)

// REG_088
#define CAP_SENS_REG_DIN_USN_SHIFT                0
#define CAP_SENS_REG_DIN_USN_MASK                 (0xFFF << CAP_SENS_REG_DIN_USN_SHIFT)
#define CAP_SENS_REG_DIN_USN(n)                   (((n) & CAP_SENS_REG_DIN_USN_MASK) << CAP_SENS_REG_DIN_USN_SHIFT)

// REG_08C
#define CAP_SENS_REG_RCOSC_CAL_RESETN            (1 << 4)
#define CAP_SENS_REG_RCOSC_CAL_START             (1 << 3)
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT    0
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL_MASK     (0x7 << CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT)
#define CAP_SENS_REG_RCOSC_CAL_TIME_SEL(n)       (((n) & CAP_SENS_REG_RCOSC_CAL_TIME_SEL_MASK) << CAP_SENS_REG_RCOSC_CAL_TIME_SEL_SHIFT)

// REG_090
#define CAP_SENS_REG_DIG_RCOSC_CAL_DONE          (1 << 15)
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT     0
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT_MASK      (0x7FFF << CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT)
#define CAP_SENS_REG_DIG_RCOSC_CAL_CNT(n)        (((n) & CAP_SENS_REG_DIG_RCOSC_CAL_CNT_MASK) << CAP_SENS_REG_DIG_RCOSC_CAL_CNT_SHIFT)

// REG_094
#define CAP_SENS_REG_CAP_CHAN0_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN0_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_CHAN0(n)                (((n) & CAP_SENS_REG_CAP_CHAN0_MASK) << CAP_SENS_REG_CAP_CHAN0_SHIFT)
#define CAP_SENS_REG_CAP_CHAN1_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN1_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN1_SHIFT)
#define CAP_SENS_REG_CAP_CHAN1(n)                (((n) & CAP_SENS_REG_CAP_CHAN1_MASK) << CAP_SENS_REG_CAP_CHAN1_SHIFT)

// REG_098
#define CAP_SENS_REG_CAP_CHAN2_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN2_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_CHAN2(n)                (((n) & CAP_SENS_REG_CAP_CHAN2_MASK) << CAP_SENS_REG_CAP_CHAN2_SHIFT)
#define CAP_SENS_REG_CAP_CHAN3_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN3_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN3_SHIFT)
#define CAP_SENS_REG_CAP_CHAN3(n)                (((n) & CAP_SENS_REG_CAP_CHAN3_MASK) << CAP_SENS_REG_CAP_CHAN3_SHIFT)

// REG_09C
#define CAP_SENS_REG_CAP_CHAN4_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN4_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_CHAN4(n)                (((n) & CAP_SENS_REG_CAP_CHAN4_MASK) << CAP_SENS_REG_CAP_CHAN4_SHIFT)
#define CAP_SENS_REG_CAP_CHAN5_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN5_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN5_SHIFT)
#define CAP_SENS_REG_CAP_CHAN5(n)                (((n) & CAP_SENS_REG_CAP_CHAN5_MASK) << CAP_SENS_REG_CAP_CHAN5_SHIFT)

// REG_0A0
#define CAP_SENS_REG_CAP_CHAN6_SHIFT             16
#define CAP_SENS_REG_CAP_CHAN6_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_CHAN6(n)                (((n) & CAP_SENS_REG_CAP_CHAN6_MASK) << CAP_SENS_REG_CAP_CHAN6_SHIFT)
#define CAP_SENS_REG_CAP_CHAN7_SHIFT             0
#define CAP_SENS_REG_CAP_CHAN7_MASK              (0xFFFF << CAP_SENS_REG_CAP_CHAN7_SHIFT)
#define CAP_SENS_REG_CAP_CHAN7(n)                (((n) & CAP_SENS_REG_CAP_CHAN7_MASK) << CAP_SENS_REG_CAP_CHAN7_SHIFT)

// REG_0A4
#define CAP_SENS_REG_RSV0_SHIFT                  0
#define CAP_SENS_REG_RSV0_MASK                   (0xFF << CAP_SENS_REG_RSV0_SHIFT)
#define CAP_SENS_REG_RSV0(n)                     (((n) & CAP_SENS_REG_RSV0_MASK) << CAP_SENS_REG_RSV0_SHIFT)

// REG_0A8
#define CAP_SENS_REG_RSV1_SHIFT                  0
#define CAP_SENS_REG_RSV1_MASK                   (0xFF << CAP_SENS_REG_RSV1_SHIFT)
#define CAP_SENS_REG_RSV1(n)                     (((n) & CAP_SENS_REG_RSV1_MASK) << CAP_SENS_REG_RSV1_SHIFT)

#ifdef __cplusplus
}
#endif

#endif
