#!/bin/bash

TARGET_LIST="seb01_earbuds"
CHIPID="best1503"
COMMAND=$1
set -e

# BES2700IH软件需求：
# 1、用于TWS耳机。
# 2、支持BLE，支持GATT_OVER_BR_EDR；支持主从切换后BLE也无缝切换（主耳广播），快速连接APP。
# 3、支持Hybrid ANC，通过SPP连接校准。
# 4、支持BLE OTA固件升级。（是否支持remap方式，固件压缩？）
# 5、支持有线单线UART固件升级。
# 6、支持一拖二，可以通过宏开关。
# 7、音频编码只需要SBC和AAC。
# 8、支持BECO NPU, 有demo可以验证。

BUILD_CUSTOMER_CFG="POWER_ON_ENTER_TWS_PAIRING_ENABLED=1 TRACE_BUF_SIZE=32*1024 \
				BLE=1 GATT_OVER_BR_EDR=1 CTKD_ENABLE=1 IS_CTKD_OVER_BR_EDR_ENABLED=1 BLE_PRF_HID=1 BLE_HID_ENABLE=1 \
				BES_OTA=1 OTA_BIN_COMPRESSED=1 APP_TRACE_RX_ENABLE=0 APP_RX_API_ENABLE=0 \
				SPP_EQ_TUNING=1 TOTA_v2=1 A2DP_VIRTUAL_SURROUND=1 AUDIO_BASS_ENHANCER=1 \
				SPEECH_TX_2MIC_NS8=1 SPEECH_TX_1MIC_NS=0 SPEECH_TX_3MIC_NS=0 \
				FLASH_REMAP=0 OTA_REBOOT_FLASH_REMAP=0 BT_HID_DEVICE=1 BT_SERVICE_ENABLE=1 \
				ANC_ASSIST_ENABLED=1 ANC_ENABLE=0 ANC_APP=1 AUDIO_ADAPTIVE_VOLUME=0 \
				SPEECH_RX_COMPEXP=1 SPEECH_RX_AGC=1 FLASH_UNIQUE_ID=1 \
				SPEECH_TX_2MIC_PREAF=1 SPEECH_TX_DC_FILTER=1 SPEECH_TX_EQ=1 SPEECH_RX_NS2FLOAT=1 SPEECH_RX_EQ=1 \
				BES_LIB_DIR=lib/bes/best1503/PRO_0003 \
				A2DP_AAC_ON=1 A2DP_LDAC_ON=0 A2DP_LHDC_ON=0 A2DP_LHDC_V3=0 A2DP_LHDCV5_ON=0
				BT_SVC_MODULE_TWS_BLE_SEAMLESS_SWITCH=1 BLE_SEEMLESS_ENABLED=1
				FREEMAN_OTA_ENABLE=1 A2DP_VIRTUAL_SURROUND_STEREO=0 AUDIO_LIMITER=1 AUDIO_DRC=0
				SPEECH_NS_BECO=1 ANC_FF_ENABLED=1 ANC_FB_ENABLED=1 SWIFT_ENABLE=1"
 

#				FREE_TWS_PAIRING_ENABLED=0 POWER_ON_OPEN_BOX_ENABLED=1 \
#				A2DP_AAC_ON=1 A2DP_LDAC_ON=0 A2DP_LHDC_ON=0 A2DP_LHDC_V3=0 A2DP_LHDCV5_ON=0 \
#				BT_SVC_MODULE_TWS_BLE_SEAMLESS_SWITCH=1 BLE_SEEMLESS_ENABLED=1 
#				FREEMAN_OTA_ENABLE=1 A2DP_VIRTUAL_SURROUND_STEREO=0 AUDIO_LIMITER=1 AUDIO_DRC=0 \
#				SPEECH_NS_BECO=1 ANC_FF_ENABLED=1 ANC_FB_ENABLED=1" 

if [[ "$COMMAND" == "clean" ]];
then
    make T=$TARGET_LIST clean ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID OTA_BIN_COMPRESSED=1 DEBUG=1 -j64 GEN_LIB=1 BES_LIB_DIR=lib/bes/best1503/PRO_0003 ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'lst' ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 lst all ||{ echo "$LINENO command failed"; exit 1; }
else
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID OTA_BIN_COMPRESSED=1 DEBUG=1 BES_LIB_DIR=lib/bes/best1503/PRO_0003 -j64 ||{ echo "$LINENO command failed"; exit 1; }
fi
echo $BUILD_CUSTOMER_CFG