#!/bin/bash


TARGET_LIST="best1502p"
CHIPID="best1502p"
COMMAND=$1

LIB_DIR_CFG="BES_LIB_DIR=lib/bes/"$CHIPID"/PRO_0004"

POWER_ON_CFG="POWER_ON_ENTER_TWS_PAIRING_ENABLED=1"

AUDIO_CODEC_CFG="AAC_PNS_SKIP=1 A2DP_AAC_ON=1 A2DP_LDAC_ON=1 A2DP_LHDC_ON=0 A2DP_LHDC_V3=0 A2DP_LHDCV5_ON=0"
AUDIO_PROCESS_CFG="A2DP_VIRTUAL_SURROUND=0 A2DP_VIRTUAL_SURROUND_STEREO=0 AUDIO_BASS_ENHANCER=0 AUDIO_LIMITER=0 AUDIO_DRC=0 APP_DEBUG_TOOL=TOTA"

COM_CFG="DEBUG=1 APP_TRACE_RX_ENABLE=1 APP_RX_API_ENABLE=1 TRACE_BUF_SIZE=16*1024"

OTA_BASE="OTA_BIN_COMPRESSED=1"
OTA_APP_CFG="$OTA_BASE BES_OTA=1"
OTA_BOOTLOADER_CFG="$OTA_BASE USB_CDC_DOWNLOAD=1"

ENC_CFG="TX_3MIC_PREAF=1 SPEECH_TX_3MIC_NS=1"

ANC_CFG="ANC_ENABLE=1 ANC_FF_ENABLED=1 ANC_FB_ENABLED=1"
ANC_FIR_CFG="APP_MCPP_CLI=BTH APP_MCPP_BTH_SENS=1 SENSOR_HUB=1 APP_RPC_ENABLE=1 SENS_TRC_TO_MCU=1 VOICE_ASSIST_FF_FIR_LMS=1 \
            ANC_ASSIST_ENABLED=1 VOICE_ASSIST_FF_FIR_LMS_BTH_SENS=1 LARGE_SENS_RAM=1 SENS_FIR_LMS_SIZE=0x20000 \
            APP_ANC_ASSIST_THREAD=1 AUDIO_ANC_TT_HW=1 SENSORHUB_START_WHEN_MAIN_MCU_ON=0 "

AI_RECORDING_CFG="RECORDING_USE_OPUS=1 AI_VOICE_TRACE_ENABLE=1 TOTA_v2=1"

BT_APP_FEATURE_CFG="BLE=1 GFPS_ENABLE=1 HOST_GEN_ECDH_KEY=1 GATT_OVER_BR_EDR=1"

CAPSENSOR_CFG="CAPSENSOR_ENABLE=1 CAPSENSOR_WEAR=1 CAPSENSOR_TOUCH=1 CAPSENSOR_SLIDE=1 CAPSENSOR_TRACE_DEBUG=0 CAPSENSOR_SPP_SERVER=0"

DEBUG_LIB_CFG="$LIB_DIR_CFG/DEBUG"
NO_DEBUG_LIB_CFG="$LIB_DIR_CFG/NODEBUG"

FREEMAN_ENABLED_STERO=1
FIR_LMS_AEC_ENABLED=0
SPEECH_ARMCC_LIB=0

set -e

BUILD_CUSTOMER_CFG="-j FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO FREEMAN_OTA_ENABLE=1 USER_BURN_ADDR_PAIR_EN=1 \
                    $POWER_ON_CFG $AUDIO_CODEC_CFG $AUDIO_PROCESS_CFG $COM_CFG \
                    $OTA_APP_CFG $ENC_CFG $ANC_CFG $ANC_FIR_CFG $AI_RECORDING_CFG $BT_APP_FEATURE_CFG $CAPSENSOR_CFG "

if [[ "$COMMAND" == "clean" ]];
then
    make T=$TARGET_LIST clean ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == "gen_lib" ]];
then
        make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -sj DEBUG=0 $NO_DEBUG_LIB_CFG GEN_LIB=1 ||{ echo "$LINENO command failed"; exit 1; }
        make T=sensor_hub -j8 DEBUG=0 $NO_DEBUG_LIB_CFG GEN_LIB=1 SENS_TRC_TO_MCU=1 CHIP=$CHIPID VOICE_ASSIST_FF_FIR_LMS=1 MCU_I2C_SLAVE=1 LARGE_SENS_RAM=1 SENS_USE_SENS_MAIN=1 SPEECH_ARMCC_LIB=$SPEECH_ARMCC_LIB APP_MCPP_CLI=SENS APP_MCPP_SRV=bes APP_MCPP_BTH_SENS=1 AUDIO_ANC_FIR_HW=1 FIR_LMS_AEC_ENABLED=$FIR_LMS_AEC_ENABLED CP_IN_SAME_EE=1 SENS_FIR_LMS_SIZE=0x20000 VOICE_ASSIST_FF_FIR_LMS_CP_ACCEL=1 VOICE_ASSIST_FF_FIR_LMS_MULTI_THREAD=0 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO
        make T=prod_test/ota_copy CHIP=$CHIPID $OTA_BOOTLOADER_CFG DEBUG=0 -sj GEN_LIB=1 $NO_DEBUG_LIB_CFG ||{ echo "$LINENO command failed"; exit 1; }

        make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -sj GEN_LIB=1 DEBUG=1 $DEBUG_LIB_CFG ||{ echo "$LINENO command failed"; exit 1; }
        make T=sensor_hub -j8 DEBUG=2 $DEBUG_LIB_CFG GEN_LIB=1 SENS_TRC_TO_MCU=1 CHIP=$CHIPID VOICE_ASSIST_FF_FIR_LMS=1 MCU_I2C_SLAVE=1 LARGE_SENS_RAM=1 SENS_USE_SENS_MAIN=1 SPEECH_ARMCC_LIB=$SPEECH_ARMCC_LIB APP_MCPP_CLI=SENS APP_MCPP_SRV=bes APP_MCPP_BTH_SENS=1 AUDIO_ANC_FIR_HW=1 FIR_LMS_AEC_ENABLED=$FIR_LMS_AEC_ENABLED CP_IN_SAME_EE=1 SENS_FIR_LMS_SIZE=0x20000 VOICE_ASSIST_FF_FIR_LMS_CP_ACCEL=1 VOICE_ASSIST_FF_FIR_LMS_MULTI_THREAD=0 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO
        make T=prod_test/ota_copy CHIP=$CHIPID $OTA_BOOTLOADER_CFG DEBUG=1 -sj GEN_LIB=1 $DEBUG_LIB_CFG ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'lst' ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG -j64 lst all ||{ echo "$LINENO command failed"; exit 1; }
elif [[ "$COMMAND" == 'debugoff' ]];
then
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG DEBUG=0 $NO_DEBUG_LIB_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
    make T=prod_test/ota_copy CHIP=$CHIPID $OTA_BOOTLOADER_CFG DEBUG=0 $NO_DEBUG_LIB_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
else
    echo "Build Bootloader"
    make T=prod_test/ota_copy CHIP=$CHIPID $OTA_BOOTLOADER_CFG DEBUG=1 $DEBUG_LIB_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }

    echo "Build Sensorhub"
    make T=sensor_hub -j8 SENS_TRC_TO_MCU=1 CHIP=$CHIPID DEBUG=1 $DEBUG_LIB_CFG VOICE_ASSIST_FF_FIR_LMS=1 MCU_I2C_SLAVE=1 LARGE_SENS_RAM=1 SENS_USE_SENS_MAIN=1 SPEECH_ARMCC_LIB=$SPEECH_ARMCC_LIB APP_MCPP_CLI=SENS APP_MCPP_SRV=bes APP_MCPP_BTH_SENS=1 AUDIO_ANC_FIR_HW=1 FIR_LMS_AEC_ENABLED=$FIR_LMS_AEC_ENABLED CP_IN_SAME_EE=1 SENS_FIR_LMS_SIZE=0x20000 VOICE_ASSIST_FF_FIR_LMS_CP_ACCEL=1 VOICE_ASSIST_FF_FIR_LMS_MULTI_THREAD=0 FREEMAN_ENABLED_STERO=$FREEMAN_ENABLED_STERO

    echo "Build App"
    make T=$TARGET_LIST $BUILD_CUSTOMER_CFG DEBUG=1 $DEBUG_LIB_CFG -j64 ||{ echo "$LINENO command failed"; exit 1; }
fi
echo "make T=$TARGET_LIST $BUILD_CUSTOMER_CFG"