##############################################################################
#
#    Copyright (c) 2005 - 2020 by Vivante Corp.  All rights reserved.
#
#    The material in this file is confidential and contains trade secrets
#    of Vivante Corporation. This is proprietary information owned by
#    Vivante Corporation. No part of this work may be disclosed,
#    reproduced, copied, transmitted, or used in any way for any purpose,
#    without the express written permission of Vivante Corporation.
#
##############################################################################


SDK_DIR ?= ./build
.phony: all install doc

all:
ifneq ($(KERNEL_DIR),)
	@$(MAKE) -C VGLiteKernel
endif
	@$(MAKE) -C VGLite

clean:
	@rm -rf bin
ifneq ($(KERNEL_DIR),)
	@$(MAKE) -C VGLiteKernel clean
endif
	@$(MAKE) -C VGLite clean

install: all $(SDK_DIR)
	@cp -rf bin/* $(SDK_DIR)/drivers
	@cp -f inc/* $(SDK_DIR)/inc

$(SDK_DIR):
	@mkdir -p $(SDK_DIR)/drivers
	@mkdir -p $(SDK_DIR)/inc
