/***************************************************************************
 *
 * Copyright 2015-2022 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __HAL_IOMUX_BEST1503_H__
#define __HAL_IOMUX_BEST1503_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "plat_types.h"

#ifndef ROM_BUILD
#define PMU_HAS_LED_PIN
#define PMU_HAS_LED_IRQ
#endif

enum HAL_IOMUX_PIN_T {
    HAL_IOMUX_PIN_P0_0 = 0,
    HAL_IOMUX_PIN_P0_1,
    HAL_IOMUX_PIN_P0_2,
    HAL_IOMUX_PIN_P0_3,
    HAL_IOMUX_PIN_P0_4,
    HAL_IOMUX_PIN_P0_5,
    HAL_IOMUX_PIN_P0_6,
    HAL_IOMUX_PIN_P0_7,

    HAL_IOMUX_PIN_P1_0,
    HAL_IOMUX_PIN_P1_1,
    HAL_IOMUX_PIN_P1_2,
    HAL_IOMUX_PIN_P1_3,
    HAL_IOMUX_PIN_P1_4,
    HAL_IOMUX_PIN_P1_5,
    HAL_IOMUX_PIN_P1_6,
    HAL_IOMUX_PIN_P1_7,

    HAL_IOMUX_PIN_P2_0,
    HAL_IOMUX_PIN_P2_1,
    HAL_IOMUX_PIN_P2_2,
    HAL_IOMUX_PIN_P2_3,
    HAL_IOMUX_PIN_P2_4,
    HAL_IOMUX_PIN_P2_5,
    HAL_IOMUX_PIN_P2_6,
    HAL_IOMUX_PIN_P2_7,

    HAL_IOMUX_PIN_P3_0,
    HAL_IOMUX_PIN_P3_1,
    HAL_IOMUX_PIN_P3_2,
    HAL_IOMUX_PIN_P3_3,
    HAL_IOMUX_PIN_P3_4,
    HAL_IOMUX_PIN_P3_5,
    HAL_IOMUX_PIN_P3_6,
    HAL_IOMUX_PIN_P3_7,

    HAL_IOMUX_PIN_P4_0,
    HAL_IOMUX_PIN_P4_1,
    HAL_IOMUX_PIN_P4_2,
    HAL_IOMUX_PIN_P4_3,
    HAL_IOMUX_PIN_P4_4,
    HAL_IOMUX_PIN_P4_5,
    HAL_IOMUX_PIN_P4_6,
    HAL_IOMUX_PIN_P4_7,

    HAL_IOMUX_PIN_P5_0,
    HAL_IOMUX_PIN_P5_1,
    HAL_IOMUX_PIN_P5_2,
    HAL_IOMUX_PIN_P5_3,
    HAL_IOMUX_PIN_P5_4,
    HAL_IOMUX_PIN_P5_5,
    HAL_IOMUX_PIN_P5_6,
    HAL_IOMUX_PIN_P5_7,

    HAL_IOMUX_PIN_P6_0,
    HAL_IOMUX_PIN_P6_1,
    HAL_IOMUX_PIN_P6_2,
    HAL_IOMUX_PIN_P6_3,
    HAL_IOMUX_PIN_P6_4,
    HAL_IOMUX_PIN_P6_5,
    HAL_IOMUX_PIN_P6_6,
    HAL_IOMUX_PIN_P6_7,

    HAL_IOMUX_PIN_P7_0,
    HAL_IOMUX_PIN_P7_1,
    HAL_IOMUX_PIN_P7_2,
    HAL_IOMUX_PIN_P7_3,
    HAL_IOMUX_PIN_P7_4,
    HAL_IOMUX_PIN_P7_5,
    HAL_IOMUX_PIN_P7_6,
    HAL_IOMUX_PIN_P7_7,

    HAL_IOMUX_PIN_P8_0,
    HAL_IOMUX_PIN_P8_1,
    HAL_IOMUX_PIN_P8_2,
    HAL_IOMUX_PIN_P8_3,
    HAL_IOMUX_PIN_P8_4,
    HAL_IOMUX_PIN_P8_5,
    HAL_IOMUX_PIN_P8_6,
    HAL_IOMUX_PIN_P8_7,

    HAL_IOMUX_PIN_P9_0,
    HAL_IOMUX_PIN_P9_1,
    HAL_IOMUX_PIN_P9_2,
    HAL_IOMUX_PIN_P9_3,
    HAL_IOMUX_PIN_P9_4,
    HAL_IOMUX_PIN_P9_5,
    HAL_IOMUX_PIN_P9_6,
    HAL_IOMUX_PIN_P9_7,

    HAL_IOMUX_PIN_NUM,

    HAL_IOMUX_PIN_LED1 = HAL_IOMUX_PIN_NUM,
    HAL_IOMUX_PIN_LED2,

    HAL_IOMUX_PIN_LED_NUM,
};

enum HAL_GPIO_PIN_T {
    HAL_GPIO_PIN_P0_0 = HAL_IOMUX_PIN_P0_0,
    HAL_GPIO_PIN_P0_1 = HAL_IOMUX_PIN_P0_1,
    HAL_GPIO_PIN_P0_2 = HAL_IOMUX_PIN_P0_2,
    HAL_GPIO_PIN_P0_3 = HAL_IOMUX_PIN_P0_3,
    HAL_GPIO_PIN_P0_4 = HAL_IOMUX_PIN_P0_4,
    HAL_GPIO_PIN_P0_5 = HAL_IOMUX_PIN_P0_5,
    HAL_GPIO_PIN_P0_6 = HAL_IOMUX_PIN_P0_6,
    HAL_GPIO_PIN_P0_7 = HAL_IOMUX_PIN_P0_7,

    HAL_GPIO_PIN_P1_0 = HAL_IOMUX_PIN_P1_0,
    HAL_GPIO_PIN_P1_1 = HAL_IOMUX_PIN_P1_1,
    HAL_GPIO_PIN_P1_2 = HAL_IOMUX_PIN_P1_2,
    HAL_GPIO_PIN_P1_3 = HAL_IOMUX_PIN_P1_3,
    HAL_GPIO_PIN_P1_4 = HAL_IOMUX_PIN_P1_4,
    HAL_GPIO_PIN_P1_5 = HAL_IOMUX_PIN_P1_5,
    HAL_GPIO_PIN_P1_6 = HAL_IOMUX_PIN_P1_6,
    HAL_GPIO_PIN_P1_7 = HAL_IOMUX_PIN_P1_7,

    HAL_GPIO_PIN_P2_0 = HAL_IOMUX_PIN_P2_0,
    HAL_GPIO_PIN_P2_1 = HAL_IOMUX_PIN_P2_1,
    HAL_GPIO_PIN_P2_2 = HAL_IOMUX_PIN_P2_2,
    HAL_GPIO_PIN_P2_3 = HAL_IOMUX_PIN_P2_3,
    HAL_GPIO_PIN_P2_4 = HAL_IOMUX_PIN_P2_4,
    HAL_GPIO_PIN_P2_5 = HAL_IOMUX_PIN_P2_5,
    HAL_GPIO_PIN_P2_6 = HAL_IOMUX_PIN_P2_6,
    HAL_GPIO_PIN_P2_7 = HAL_IOMUX_PIN_P2_7,

    HAL_GPIO_PIN_P3_0 = HAL_IOMUX_PIN_P3_0,
    HAL_GPIO_PIN_P3_1 = HAL_IOMUX_PIN_P3_1,
    HAL_GPIO_PIN_P3_2 = HAL_IOMUX_PIN_P3_2,
    HAL_GPIO_PIN_P3_3 = HAL_IOMUX_PIN_P3_3,
    HAL_GPIO_PIN_P3_4 = HAL_IOMUX_PIN_P3_4,
    HAL_GPIO_PIN_P3_5 = HAL_IOMUX_PIN_P3_5,
    HAL_GPIO_PIN_P3_6 = HAL_IOMUX_PIN_P3_6,
    HAL_GPIO_PIN_P3_7 = HAL_IOMUX_PIN_P3_7,

    HAL_GPIO_PIN_P4_0 = HAL_IOMUX_PIN_P4_0,
    HAL_GPIO_PIN_P4_1 = HAL_IOMUX_PIN_P4_1,
    HAL_GPIO_PIN_P4_2 = HAL_IOMUX_PIN_P4_2,
    HAL_GPIO_PIN_P4_3 = HAL_IOMUX_PIN_P4_3,
    HAL_GPIO_PIN_P4_4 = HAL_IOMUX_PIN_P4_4,
    HAL_GPIO_PIN_P4_5 = HAL_IOMUX_PIN_P4_5,
    HAL_GPIO_PIN_P4_6 = HAL_IOMUX_PIN_P4_6,
    HAL_GPIO_PIN_P4_7 = HAL_IOMUX_PIN_P4_7,

    HAL_GPIO_PIN_P5_0 = HAL_IOMUX_PIN_P5_0,
    HAL_GPIO_PIN_P5_1 = HAL_IOMUX_PIN_P5_1,
    HAL_GPIO_PIN_P5_2 = HAL_IOMUX_PIN_P5_2,
    HAL_GPIO_PIN_P5_3 = HAL_IOMUX_PIN_P5_3,
    HAL_GPIO_PIN_P5_4 = HAL_IOMUX_PIN_P5_4,
    HAL_GPIO_PIN_P5_5 = HAL_IOMUX_PIN_P5_5,
    HAL_GPIO_PIN_P5_6 = HAL_IOMUX_PIN_P5_6,
    HAL_GPIO_PIN_P5_7 = HAL_IOMUX_PIN_P5_7,

    HAL_GPIO_PIN_P6_0 = HAL_IOMUX_PIN_P6_0,
    HAL_GPIO_PIN_P6_1 = HAL_IOMUX_PIN_P6_1,
    HAL_GPIO_PIN_P6_2 = HAL_IOMUX_PIN_P6_2,
    HAL_GPIO_PIN_P6_3 = HAL_IOMUX_PIN_P6_3,
    HAL_GPIO_PIN_P6_4 = HAL_IOMUX_PIN_P6_4,
    HAL_GPIO_PIN_P6_5 = HAL_IOMUX_PIN_P6_5,
    HAL_GPIO_PIN_P6_6 = HAL_IOMUX_PIN_P6_6,
    HAL_GPIO_PIN_P6_7 = HAL_IOMUX_PIN_P6_7,

    HAL_GPIO_PIN_P7_0 = HAL_IOMUX_PIN_P7_0,
    HAL_GPIO_PIN_P7_1 = HAL_IOMUX_PIN_P7_1,
    HAL_GPIO_PIN_P7_2 = HAL_IOMUX_PIN_P7_2,
    HAL_GPIO_PIN_P7_3 = HAL_IOMUX_PIN_P7_3,
    HAL_GPIO_PIN_P7_4 = HAL_IOMUX_PIN_P7_4,
    HAL_GPIO_PIN_P7_5 = HAL_IOMUX_PIN_P7_5,
    HAL_GPIO_PIN_P7_6 = HAL_IOMUX_PIN_P7_6,
    HAL_GPIO_PIN_P7_7 = HAL_IOMUX_PIN_P7_7,

    HAL_GPIO_PIN_P8_0 = HAL_IOMUX_PIN_P8_0,
    HAL_GPIO_PIN_P8_1 = HAL_IOMUX_PIN_P8_1,
    HAL_GPIO_PIN_P8_2 = HAL_IOMUX_PIN_P8_2,
    HAL_GPIO_PIN_P8_3 = HAL_IOMUX_PIN_P8_3,
    HAL_GPIO_PIN_P8_4 = HAL_IOMUX_PIN_P8_4,
    HAL_GPIO_PIN_P8_5 = HAL_IOMUX_PIN_P8_5,
    HAL_GPIO_PIN_P8_6 = HAL_IOMUX_PIN_P8_6,
    HAL_GPIO_PIN_P8_7 = HAL_IOMUX_PIN_P8_7,

    HAL_GPIO_PIN_P9_0 = HAL_IOMUX_PIN_P9_0,
    HAL_GPIO_PIN_P9_1 = HAL_IOMUX_PIN_P9_1,
    HAL_GPIO_PIN_P9_2 = HAL_IOMUX_PIN_P9_2,
    HAL_GPIO_PIN_P9_3 = HAL_IOMUX_PIN_P9_3,
    HAL_GPIO_PIN_P9_4 = HAL_IOMUX_PIN_P9_4,
    HAL_GPIO_PIN_P9_5 = HAL_IOMUX_PIN_P9_5,
    HAL_GPIO_PIN_P9_6 = HAL_IOMUX_PIN_P9_6,
    HAL_GPIO_PIN_P9_7 = HAL_IOMUX_PIN_P9_7,

    HAL_GPIO_PIN_NUM  = HAL_IOMUX_PIN_NUM,

    HAL_GPIO_PIN_LED1 = HAL_IOMUX_PIN_LED1,
    HAL_GPIO_PIN_LED2 = HAL_IOMUX_PIN_LED2,

    HAL_GPIO_PIN_LED_NUM = HAL_IOMUX_PIN_LED_NUM,
};

enum HAL_IOMUX_FUNCTION_T {
    HAL_IOMUX_FUNC_NONE = 0,
    HAL_IOMUX_FUNC_GPIO,
    HAL_IOMUX_FUNC_AS_GPIO = HAL_IOMUX_FUNC_GPIO,
    HAL_IOMUX_FUNC_BT_UART_CTS,
    HAL_IOMUX_FUNC_BT_UART_RTS,
    HAL_IOMUX_FUNC_BT_UART_RX,
    HAL_IOMUX_FUNC_BT_UART_TX,
    HAL_IOMUX_FUNC_BT_SWRX,
    HAL_IOMUX_FUNC_BT_SWTX,
    HAL_IOMUX_FUNC_BT_SMP_PIN0,
    HAL_IOMUX_FUNC_BT_SMP_PIN1,
    HAL_IOMUX_FUNC_BT_SMP_VLD,
    HAL_IOMUX_FUNC_BT_ACTIVE,
    HAL_IOMUX_FUNC_BT_PRIO,
    HAL_IOMUX_FUNC_BT_FREQ,
    HAL_IOMUX_FUNC_BT_WIFI_SW,
    HAL_IOMUX_FUNC_NBT_BLE,
    HAL_IOMUX_FUNC_WF_ACTIVE,
    HAL_IOMUX_FUNC_WCI_BTC_UART_RX,
    HAL_IOMUX_FUNC_WCI_BTC_UART_TX,
    HAL_IOMUX_FUNC_CLK_32K_IN,
    HAL_IOMUX_FUNC_CLK_REQ_IN,
    HAL_IOMUX_FUNC_CLK_REQ_OUT,
    HAL_IOMUX_FUNC_CLK_OUT,
    HAL_IOMUX_FUNC_I2C_SCL,
    HAL_IOMUX_FUNC_I2C_SDA,
    HAL_IOMUX_FUNC_I2S_MCLK,
    HAL_IOMUX_FUNC_LCD_TE,
    HAL_IOMUX_FUNC_LCD_PWM,
    HAL_IOMUX_FUNC_LCD_PCLK,
    HAL_IOMUX_FUNC_LCD_VSYNC,
    HAL_IOMUX_FUNC_LCD_HSYNC,
    HAL_IOMUX_FUNC_LCD_DATAEN,
    HAL_IOMUX_FUNC_LCD_DATA0,
    HAL_IOMUX_FUNC_LCD_DATA1,
    HAL_IOMUX_FUNC_LCD_DATA2,
    HAL_IOMUX_FUNC_LCD_DATA3,
    HAL_IOMUX_FUNC_LCD_DATA4,
    HAL_IOMUX_FUNC_LCD_DATA5,
    HAL_IOMUX_FUNC_LCD_DATA6,
    HAL_IOMUX_FUNC_LCD_DATA7,
    HAL_IOMUX_FUNC_LCD_DATA8,
    HAL_IOMUX_FUNC_LCD_DATA9,
    HAL_IOMUX_FUNC_LCD_DATA10,
    HAL_IOMUX_FUNC_LCD_DATA11,
    HAL_IOMUX_FUNC_LCD_DATA12,
    HAL_IOMUX_FUNC_LCD_DATA13,
    HAL_IOMUX_FUNC_LCD_DATA14,
    HAL_IOMUX_FUNC_LCD_DATA15,
    HAL_IOMUX_FUNC_LCD_DATA16,
    HAL_IOMUX_FUNC_LCD_DATA17,
    HAL_IOMUX_FUNC_LCD_DATA18,
    HAL_IOMUX_FUNC_LCD_DATA19,
    HAL_IOMUX_FUNC_LCD_DATA20,
    HAL_IOMUX_FUNC_LCD_DATA21,
    HAL_IOMUX_FUNC_LCD_DATA22,
    HAL_IOMUX_FUNC_LCD_DATA23,
    HAL_IOMUX_FUNC_MCU_I2C_M0_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M0_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M1_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M1_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M2_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M2_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M3_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M3_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M4_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M4_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M5_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M5_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M6_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M6_SDA,
    HAL_IOMUX_FUNC_MCU_I2C_M7_SCL,
    HAL_IOMUX_FUNC_MCU_I2C_M7_SDA,
    HAL_IOMUX_FUNC_MCU_I2S0_SCK,
    HAL_IOMUX_FUNC_MCU_I2S0_SDI0,
    HAL_IOMUX_FUNC_MCU_I2S0_SDO,
    HAL_IOMUX_FUNC_MCU_I2S0_WS,
    HAL_IOMUX_FUNC_MCU_I2S1_SCK,
    HAL_IOMUX_FUNC_MCU_I2S1_SDI0,
    HAL_IOMUX_FUNC_MCU_I2S1_SDO,
    HAL_IOMUX_FUNC_MCU_I2S1_WS,
    HAL_IOMUX_FUNC_MCU_SPI_CLK,
    HAL_IOMUX_FUNC_MCU_SPI_CS0,
    HAL_IOMUX_FUNC_MCU_SPI_CS1,
    HAL_IOMUX_FUNC_MCU_SPI_DI0,
    HAL_IOMUX_FUNC_MCU_SPI_DI1,
    HAL_IOMUX_FUNC_MCU_SPI_DIO,
    HAL_IOMUX_FUNC_MCU_SPILCD_CLK,
    HAL_IOMUX_FUNC_MCU_SPILCD_CS0,
    HAL_IOMUX_FUNC_MCU_SPILCD_DI0,
    HAL_IOMUX_FUNC_MCU_SPILCD_DIO,
    HAL_IOMUX_FUNC_MCU_SPI2_CLK,
    HAL_IOMUX_FUNC_MCU_SPI2_CS0,
    HAL_IOMUX_FUNC_MCU_SPI2_CS1,
    HAL_IOMUX_FUNC_MCU_SPI2_DI0,
    HAL_IOMUX_FUNC_MCU_SPI2_DI1,
    HAL_IOMUX_FUNC_MCU_SPI2_DIO,
    HAL_IOMUX_FUNC_MCU_UART0_RX,
    HAL_IOMUX_FUNC_MCU_UART0_TX,
    HAL_IOMUX_FUNC_MCU_UART1_CTS,
    HAL_IOMUX_FUNC_MCU_UART1_RTS,
    HAL_IOMUX_FUNC_MCU_UART1_RX,
    HAL_IOMUX_FUNC_MCU_UART1_TX,
    HAL_IOMUX_FUNC_MCU_UART2_CTS,
    HAL_IOMUX_FUNC_MCU_UART2_RTS,
    HAL_IOMUX_FUNC_MCU_UART2_RX,
    HAL_IOMUX_FUNC_MCU_UART2_TX,
    HAL_IOMUX_FUNC_MCU_UART3_CTS,
    HAL_IOMUX_FUNC_MCU_UART3_RTS,
    HAL_IOMUX_FUNC_MCU_UART3_RX,
    HAL_IOMUX_FUNC_MCU_UART3_TX,
    HAL_IOMUX_FUNC_MCU_UART4_CTS,
    HAL_IOMUX_FUNC_MCU_UART4_RTS,
    HAL_IOMUX_FUNC_MCU_UART4_RX,
    HAL_IOMUX_FUNC_MCU_UART5_CTS,
    HAL_IOMUX_FUNC_MCU_UART4_TX,
    HAL_IOMUX_FUNC_MCU_UART5_RTS,
    HAL_IOMUX_FUNC_MCU_UART5_RX,
    HAL_IOMUX_FUNC_MCU_UART5_TX,
    HAL_IOMUX_FUNC_SLV_SPI0_CLK,
    HAL_IOMUX_FUNC_SLV_SPI0_CS0,
    HAL_IOMUX_FUNC_SLV_SPI0_DI0,
    HAL_IOMUX_FUNC_SLV_SPI0_DIO,
    HAL_IOMUX_FUNC_PCM_CLK,
    HAL_IOMUX_FUNC_PCM_DI,
    HAL_IOMUX_FUNC_PCM_DO,
    HAL_IOMUX_FUNC_PCM_FSYNC,
    HAL_IOMUX_FUNC_PDM0_CK,
    HAL_IOMUX_FUNC_PDM0_D,
    HAL_IOMUX_FUNC_PDM1_CK,
    HAL_IOMUX_FUNC_PDM1_D,
    HAL_IOMUX_FUNC_PDM2_CK,
    HAL_IOMUX_FUNC_PDM2_D,
    HAL_IOMUX_FUNC_PWM0,
    HAL_IOMUX_FUNC_PWM1,
    HAL_IOMUX_FUNC_PWM2,
    HAL_IOMUX_FUNC_PWM3,
    HAL_IOMUX_FUNC_PWM4,
    HAL_IOMUX_FUNC_PWM5,
    HAL_IOMUX_FUNC_PWM6,
    HAL_IOMUX_FUNC_PWM7,
    HAL_IOMUX_FUNC_SDMMC0_CLK,
    HAL_IOMUX_FUNC_SDMMC0_CMD,
    HAL_IOMUX_FUNC_SDMMC0_DATA0,
    HAL_IOMUX_FUNC_SDMMC0_DATA1,
    HAL_IOMUX_FUNC_SDMMC0_DATA2,
    HAL_IOMUX_FUNC_SDMMC0_DATA3,
    HAL_IOMUX_FUNC_SDMMC0_DATA4,
    HAL_IOMUX_FUNC_SDMMC0_DATA5,
    HAL_IOMUX_FUNC_SDMMC0_DATA6,
    HAL_IOMUX_FUNC_SDMMC0_DATA7,
    HAL_IOMUX_FUNC_SPDIF0_DI,
    HAL_IOMUX_FUNC_SPDIF0_DO,
    HAL_IOMUX_FUNC_QSPI_NAND_CLK,
    HAL_IOMUX_FUNC_QSPI_NAND_CS,
    HAL_IOMUX_FUNC_QSPI_NAND_D0,
    HAL_IOMUX_FUNC_QSPI_NAND_D1,
    HAL_IOMUX_FUNC_QSPI_NAND_D2,
    HAL_IOMUX_FUNC_QSPI_NAND_D3,
    HAL_IOMUX_FUNC_QSPILCD_CS0,
    HAL_IOMUX_FUNC_QSPILCD_CLK,
    HAL_IOMUX_FUNC_QSPILCD_DIO0,
    HAL_IOMUX_FUNC_QSPILCD_DIO1,
    HAL_IOMUX_FUNC_QSPILCD_DIO2,
    HAL_IOMUX_FUNC_QSPILCD_DIO3,
    HAL_IOMUX_FUNC_PPI_PORT0,
    HAL_IOMUX_FUNC_PPI_PORT1,
    HAL_IOMUX_FUNC_JTRST,
    HAL_IOMUX_FUNC_JTCK,
    HAL_IOMUX_FUNC_JTMS,
    HAL_IOMUX_FUNC_JTDI,
    HAL_IOMUX_FUNC_JTDO,
    HAL_IOMUX_FUNC_SWCK,
    HAL_IOMUX_FUNC_SWDIO,
    HAL_IOMUX_FUNC_PU_OSC,
    HAL_IOMUX_FUNC_PU_RC,
    HAL_IOMUX_FUNC_MCU_FLG_EXC_GPIO,
    HAL_IOMUX_FUNC_DISPLAY_REFRESH,
    HAL_IOMUX_FUNC_ANTENNA_SWITCH,

    HAL_IOMUX_FUNC_END
};

enum HAL_IOMUX_ISPI_ACCESS_T {
    HAL_IOMUX_ISPI_BT_RF            = (1 << 0),
    HAL_IOMUX_ISPI_BT_PMU           = (1 << 1),
    HAL_IOMUX_ISPI_BT_ANA           = (1 << 2),
    HAL_IOMUX_ISPI_MCU_RF           = (1 << 3),
    HAL_IOMUX_ISPI_MCU_PMU          = (1 << 4),
    HAL_IOMUX_ISPI_MCU_ANA          = (1 << 5),
    HAL_IOMUX_ISPI_SENS_PMU         = (1 << 6),
    HAL_IOMUX_ISPI_SENS_ANA         = (1 << 7),
    HAL_IOMUX_ISPI_SENS_RF          = (1 << 8),
    HAL_IOMUX_ISPI_SENS_PMU1        = (1 << 9),
    HAL_IOMUX_ISPI_SENS_DPA         = (1 << 10),
};

void hal_iomux_set_default_iodrv(void);

void hal_iomux_set_mcu_clock_out(void);

void hal_iomux_set_bt_clock_out(void);

int hal_iomux_tportopen(void);

int hal_iomux_tportclr(int port);

int hal_iomux_tportset(int port);

void hal_iomux_set_spi_slave(void);

void hal_iomux_clear_spi_slave(void);

void hal_iomux_set_i2c6(void);
void hal_iomux_set_i2c7(void);

void hal_iomux_set_spi2(void);

void hal_iomux_set_uart4(void);
void hal_iomux_set_uart5(void);

void hal_iomux_clear_pmu_uart(void);

void hal_iomux_set_flash_qspi(void);

void hal_iomux_set_dsi_te(void);

void hal_iomux_set_pu_osc(void);

void hal_iomux_set_pu_rc(void);

void hal_iomux_clear_sdmmc0(void);

#ifdef __cplusplus
}
#endif

#endif
