/***************************************************************************
 * Copyright 2015-2024 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 ***************************************************************************/
/* config.h -- Autogenerated! Do not edit. */

#ifndef __AOS_FS_CONFIG_H
#define __AOS_FS_CONFIG_H

#include "hal_trace.h"
#ifdef RTOS
#include "cmsis_os.h"
#endif

/****************************************************************************
 * newlibc hook interface
 ****************************************************************************/
#define BES_AOS_FS_LIBC_ADAPTER 1

/****************************************************************************
 * POSIX-like OS return values:
 ****************************************************************************/
enum
{
    FS_ERROR = -1,
    FS_OK = 0,
};


/****************************************************************************
 * Debug
 ****************************************************************************/
#define FAR
#define CODE
#ifndef DEBUGASSERT
#define DEBUGASSERT(x) ASSERT((x), "%s %d", __func__, __LINE__)
#endif
extern uint32_t g_fs_trmask;
#define FS_ERR_TAG "[%s:%d:ERROR] "
#define FS_DEBUG_TAG "[%s:%d:DEBUG] "
#define __FS_ERR_WHERE__ __FUNCTION__, __LINE__
#define __FS_DEBUG_WHERE__ __FUNCTION__, __LINE__
#define __FS_TR_INFO(attr, str, ...) \
    NORM_LOG(((attr) & ~TR_ATTR_LEVEL_MASK) | TR_ATTR_LEVEL(TR_LEVEL_INFO), str, ##__VA_ARGS__)
#define AOS_FS_TRACE(mask, str, ...) \
    { \
        if ((g_fs_trmask & (1 << mask)) || mask == 0) \
            {\
                __FS_TR_INFO(TR_MOD(AOSFS), str, ##__VA_ARGS__);\
            }\
    }

/****************************************************************************
 * fixed parameter
 ****************************************************************************/
#define CONFIG_DISABLE_PSEUDOFS_OPERATIONS   /*DISABLE PSEUDOFS*/
#define CONFIG_DISABLE_ENVIRON               /*DISABLE ENVIRON*/
#define CONFIG_MTD                           /*MTD*/
#define CONFIG_NFILE_DESCRIPTORS_PER_BLOCK 8 /* Used to represent the values of tristate options */
#define NODFS_SUPPORT                      1
#define CONFIG_PSEUDOFS_SOFTLINKS          1
#define SYMLOOP_MAX                        8
#define CONFIG_FS_HEAP_DEFAULT_SIZE        30*1024

/****************************************************************************
 * fixed parameter for rpmsgfs
 ****************************************************************************/
#define CONFIG_FS_RPMSGFS 1


/****************************************************************************
 * fixed parameter for LITTLEFS
 ****************************************************************************/
#define CONFIG_FS_LITTLEFS                     1
#define CONFIG_FS_LITTLEFS_PROGRAM_SIZE_FACTOR 1
#define CONFIG_FS_LITTLEFS_READ_SIZE_FACTOR    CONFIG_FS_LITTLEFS_PROGRAM_SIZE_FACTOR
#define CONFIG_FS_LITTLEFS_BLOCK_SIZE_FACTOR   (2 * CONFIG_FS_LITTLEFS_PROGRAM_SIZE_FACTOR)
#define CONFIG_FS_LITTLEFS_CACHE_SIZE_FACTOR   (2 * CONFIG_FS_LITTLEFS_PROGRAM_SIZE_FACTOR)
#define CONFIG_FS_LITTLEFS_LOOKAHEAD_SIZE      0
#define CONFIG_FS_LITTLEFS_BLOCK_CYCLE         200
#define CONFIG_FS_LITTLEFS_NAME_MAX            96
#define CONFIG_FS_LITTLEFS_FILE_MAX            2147483647
#define CONFIG_FS_LITTLEFS_ATTR_MAX            1022

/****************************************************************************
 * fixed parameter for FATFS
 ****************************************************************************/
#define CONFIG_FS_FATFS                  1
#define CONFIG_FS_FATFS_SECTOR_RATIO     1


/****************************************************************************
 * fixed parameter for YAFFS
 ****************************************************************************/
#define CONFIG_YAFFS_DEBUG               1
#define CONFIG_FS_YAFFS_RESERVED_BLOCKS  5
#define CONFIG_FS_YAFFS_CHUNK_CACHE      20
#define CONFIG_FS_YAFFS_REFRESH_PERIOD   1000

/****************************************************************************
 * fixed parameter for PARTITION
 ****************************************************************************/
#define CONFIG_GPT_PARTITION
#define CONFIG_TXTABLE_DEFAULT_PARTITION 0
#define CONFIG_TXTABLE_PARTITION_MAX_NUM 3

/****************************************************************************
 * fixed parameter for Nand DHARA
 ****************************************************************************/
#define CONFIG_MTD_DHARA
#define CONFIG_DHARA_READ_NCACHES 2  /* Read cache for accelerate read dhara meta data */
#define CONFIG_DHARA_GC_RATIO     4

/****************************************************************************
 * fixed parameter for RAM file system
 ****************************************************************************/
#define CONFIG_RAMMTD_BLOCKSIZE 256
#define CONFIG_RAMMTD_ERASESIZE 512


/****************************************************************************
 * file system cache conf to improve performance
 ****************************************************************************/
#define CONFIG_FS_CACHE_SEGMENTATION_NUM_MAX    5

/****************************************************************************
 * file system cache conf for emmc
 ****************************************************************************/
#define CONFIG_FS_EMMC_CACHE_LEN     32*1024
#define CONFIG_FS_EMMC_CACHE_SEG_NUM 2
#define CONFIG_FS_EMMC_CACHE_CODE(cache_seg) {cache_seg[0] = 10000; cache_seg[1] = 10000;}

/****************************************************************************
 * file system cache conf for sdmmc
 ****************************************************************************/
#define CONFIG_FS_SDMMC_CACHE_LEN     32*1024
#define CONFIG_FS_SDMMC_CACHE_SEG_NUM 2
#define CONFIG_FS_SDMMC_CACHE_CODE(cache_seg) {cache_seg[0] = 3866624; cache_seg[1] = 3866624;}


/****************************************************************************
 * Pre-processor Compiler
 ****************************************************************************/
#if defined(__GNUC__)
#define ALIAS_OF(of) __attribute__((alias(#of)))
#define FUNC_ALIAS(real_func, new_alias, args_list, return_type) \
    return_type new_alias args_list ALIAS_OF(real_func)
#else
#define FUNC_ALIAS(real_func, new_alias, args_list, return_type)
#endif /* __GNUC__ */

#undef CONFIG_C99_BOOL
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#define CONFIG_C99_BOOL 1
#endif /* ISO C99 supports _Bool */

#endif /* __AOS_FS_CONFIG_H */
