/***************************************************************************
 *
 * Copyright 2015-2023 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __CHARGER_BEST1503_H__
#define __CHARGER_BEST1503_H__

#ifdef __cplusplus
extern "C" {
#endif

#define ISPI_CHG_REG(reg)                                   (((reg) & 0xFFF) | 0x4000)

#define CHARGER_IRQ_CAUSE_CHRG                              (1 << 0)
#define CHARGER_IRQ_CAUSE_AC_ON_DET_IN                      (1 << 1)
#define CHARGER_IRQ_CAUSE_AC_ON_DET_OUT                     (1 << 2)
#define CHARGER_IRQ_CAUSE_TRIPRE_TIMEOUT                    (1 << 5)
#define CHARGER_IRQ_CAUSE_FAST_TIMEOUT                      (1 << 6)
#define CHARGER_IRQ_CAUSE_ACIN_OV                           (1 << 12)
#define CHARGER_IRQ_CAUSE_OTP                               (1 << 14)
#define CHARGER_IRQ_CAUSE_CHARGE_TRICKLE                    (1 << 26)
#define CHARGER_IRQ_CAUSE_CHARGE_PRE                        (1 << 27)
#define CHARGER_IRQ_CAUSE_CHARGE_FAST                       (1 << 28)
#define CHARGER_IRQ_CAUSE_CHARGE_OFF                        (1 << 29)
#define CHARGER_IRQ_CAUSE_CHARGE_DONE                       (1 << 30)

enum CHARGER_ACIN_STATUS_TYPE_E {
    CHARGER_ACIN_STATUS_PLUGIN  = 0,
    CHARGER_ACIN_STATUS_PLUGOUT = 1,
};

enum CHARGER_CHARGE_STATUE_E {
    CHARGER_CHARGE_STATUS_IDLE    = 0,
    CHARGER_CHARGE_STATUS_TRICKLE = 1,
    CHARGER_CHARGE_STATUS_FAST    = 2,
    CHARGER_CHARGE_STATUS_PRE     = 3,
    CHARGER_CHARGE_STATUS_FAULT   = 5,
    CHARGER_CHARGE_STATUS_OFF     = 6,
    CHARGER_CHARGE_STATUS_DONE    = 7,

    CHARGER_CHARGE_STATUS_QTY,
};

enum CHARGER_CHARGE_PRECHARGE_VOLTAGE_E {
    CHARGER_CHARGE_PRECHARGE_VOLTAGE_2600MV  = 0,
    CHARGER_CHARGE_PRECHARGE_VOLTAGE_2800MV  = 1, // default
    CHARGER_CHARGE_PRECHARGE_VOLTAGE_3000MV  = 2,
    CHARGER_CHARGE_PRECHARGE_VOLTAGE_3200MV  = 3,

    CHARGER_CHARGE_PRECHARGE_VOLTAGE_QTY,
};

enum CHARGER_CHARGE_PRECHARGE_CURRENT_E {
    CHARGER_CHARGE_PRECHARGE_CURRENT_2MA  = 0,
    CHARGER_CHARGE_PRECHARGE_CURRENT_4MA  = 1,
    CHARGER_CHARGE_PRECHARGE_CURRENT_6MA  = 2,
    CHARGER_CHARGE_PRECHARGE_CURRENT_8MA  = 3, // default
    CHARGER_CHARGE_PRECHARGE_CURRENT_10MA = 4,
    CHARGER_CHARGE_PRECHARGE_CURRENT_12MA = 5,
    CHARGER_CHARGE_PRECHARGE_CURRENT_14MA = 6,
    CHARGER_CHARGE_PRECHARGE_CURRENT_16MA = 7,
    CHARGER_CHARGE_PRECHARGE_CURRENT_18MA = 8,
    CHARGER_CHARGE_PRECHARGE_CURRENT_20MA = 9,
    CHARGER_CHARGE_PRECHARGE_CURRENT_22MA = 10,
    CHARGER_CHARGE_PRECHARGE_CURRENT_24MA = 11,
    CHARGER_CHARGE_PRECHARGE_CURRENT_26MA = 12,
    CHARGER_CHARGE_PRECHARGE_CURRENT_28MA = 13,
    CHARGER_CHARGE_PRECHARGE_CURRENT_30MA = 14,
    CHARGER_CHARGE_PRECHARGE_CURRENT_32MA = 15,

    CHARGER_CHARGE_PRECHARGE_CURRENT_QTY,
};

enum CHARGER_CHARGE_CONSTANT_CURRENT_E {
    CHARGER_CHARGE_CONSTANT_CURRENT_20MA  = 0,
    CHARGER_CHARGE_CONSTANT_CURRENT_40MA  = 1,
    CHARGER_CHARGE_CONSTANT_CURRENT_60MA  = 2, // default
    CHARGER_CHARGE_CONSTANT_CURRENT_80MA  = 3,
    CHARGER_CHARGE_CONSTANT_CURRENT_100MA = 4,
    CHARGER_CHARGE_CONSTANT_CURRENT_120MA = 5,
    CHARGER_CHARGE_CONSTANT_CURRENT_140MA = 6,
    CHARGER_CHARGE_CONSTANT_CURRENT_160MA = 7,
    CHARGER_CHARGE_CONSTANT_CURRENT_180MA = 8,
    CHARGER_CHARGE_CONSTANT_CURRENT_200MA = 9,
    CHARGER_CHARGE_CONSTANT_CURRENT_220MA = 10,
    CHARGER_CHARGE_CONSTANT_CURRENT_240MA = 11,
    CHARGER_CHARGE_CONSTANT_CURRENT_260MA = 12,
    CHARGER_CHARGE_CONSTANT_CURRENT_280MA = 13,
    CHARGER_CHARGE_CONSTANT_CURRENT_300MA = 14,
    CHARGER_CHARGE_CONSTANT_CURRENT_320MA = 15,

    CHARGER_CHARGE_CONSTANT_CURRENT_QTY,
};

enum CHARGER_CHARGE_STOP_CURRENT_E {
    CHARGER_CHARGE_STOP_CURRENT_2MA  = 0,
    CHARGER_CHARGE_STOP_CURRENT_4MA  = 1, // default
    CHARGER_CHARGE_STOP_CURRENT_6MA  = 2,
    CHARGER_CHARGE_STOP_CURRENT_8MA  = 3,
    CHARGER_CHARGE_STOP_CURRENT_10MA = 4,
    CHARGER_CHARGE_STOP_CURRENT_12MA = 5,
    CHARGER_CHARGE_STOP_CURRENT_14MA = 6,
    CHARGER_CHARGE_STOP_CURRENT_16MA = 7,
    CHARGER_CHARGE_STOP_CURRENT_18MA = 8,
    CHARGER_CHARGE_STOP_CURRENT_20MA = 9,
    CHARGER_CHARGE_STOP_CURRENT_22MA = 10,
    CHARGER_CHARGE_STOP_CURRENT_24MA = 11,
    CHARGER_CHARGE_STOP_CURRENT_26MA = 12,
    CHARGER_CHARGE_STOP_CURRENT_28MA = 13,
    CHARGER_CHARGE_STOP_CURRENT_30MA = 14,
    CHARGER_CHARGE_STOP_CURRENT_32MA = 15,

    CHARGER_CHARGE_STOP_CURRENT_QTY,
};

enum CHARGER_CHARGE_CONSTANT_VOLTAGE_E {
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3600MV = 0,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3650MV = 1,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3700MV = 2,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3750MV = 3,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3800MV = 4,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3850MV = 5,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3900MV = 6,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_3950MV = 7,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4000MV = 8,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4050MV = 9,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4100MV = 10,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4150MV = 11,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4200MV = 12, // default
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4250MV = 13,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4300MV = 14,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4350MV = 15,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4400MV = 16,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4450MV = 17,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4500MV = 18,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4550MV = 19,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4600MV = 20,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4650MV = 21,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4700MV = 22,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4750MV = 23,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4800MV = 24,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4850MV = 25,
    // VCHG >= 6V
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4900MV = 26,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4950MV = 27,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_5000MV = 28,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_5050MV = 29,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_5100MV = 30,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_5150MV = 31,

    CHARGER_CHARGING_CONSTANT_VOLTAGE_QTY,
};

// rechg-volt=vbat-cv-volt
enum CHARGER_CHARGE_RECHARGE_VOLTAGE_E {
    CHARGER_CHARGE_RECHARGE_VOLTAGE_300MV = 0,
    CHARGER_CHARGE_RECHARGE_VOLTAGE_250MV = 1,
    CHARGER_CHARGE_RECHARGE_VOLTAGE_150MV = 2, // default
    CHARGER_CHARGE_RECHARGE_VOLTAGE_80MV  = 3,

    CHARGER_CHARGE_RECHARGE_VOLTAGE_QTY,
};

struct CHARGER_CHARGE_MODULE_CFG_T {
    enum CHARGER_CHARGE_PRECHARGE_VOLTAGE_E prechg_volt;
    enum CHARGER_CHARGE_PRECHARGE_CURRENT_E prechg_current;
    enum CHARGER_CHARGE_CONSTANT_CURRENT_E cc_current;
    enum CHARGER_CHARGE_STOP_CURRENT_E stop_current;
    enum CHARGER_CHARGE_CONSTANT_VOLTAGE_E cv_volt;
    enum CHARGER_CHARGE_RECHARGE_VOLTAGE_E rechg_volt;
    bool rechg_en;
    bool chg_en;
};

typedef void (*CHARGER_CHARGE_IRQ_HANDLER_T)(uint32_t status);

void charger_charge_pattern_disable(void);

void charger_charge_irq_handler_set(CHARGER_CHARGE_IRQ_HANDLER_T handler);

enum CHARGER_CHARGE_STATUE_E charger_charge_status_get(void);

void charger_charge_module_cfg_get(struct CHARGER_CHARGE_MODULE_CFG_T *cfg);

int charger_charge_module_cfg_set(struct CHARGER_CHARGE_MODULE_CFG_T *cfg);

void charger_charge_enable(void);

void charger_charge_disable(void);

void charger_charge_open(void);

enum CHARGER_ACIN_STATUS_TYPE_E charger_acin_status_get(void);

void charger_charge_half_icc_current_enable(void);

void charger_charge_half_icc_current_disable(void);

#ifdef __cplusplus
}
#endif

#endif

