/***************************************************************************
 *
 * Copyright 2015-2025 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __CHARGER_BEST1306P_H__
#define __CHARGER_BEST1306P_H__

#include "pmu.h"
#ifdef __cplusplus
extern "C" {
#endif

#define CHARGER_IRQ_CAUSE_CHARGE_DONE    (1 << 0)
#define CHARGER_IRQ_CAUSE_VIN_OV         (1 << 1)
#define CHARGER_IRQ_CAUSE_VIN_OC         (1 << 2)

enum CHARGER_RET_E {
    CHARGER_RET_OK              = 0,
    CHARGER_RET_INVALID_OPTION  = 1,
    CHARGER_RET_INVALID_CHIP    = 2,
    CHARGER_RET_NOT_OPENED      = 3,
    CHARGER_RET_I2C_ERROR       = 4,
};

enum CHARGER_CHIP_TYPE_E {
    CHARGER_CHIP_TYPE_NONE  = 0,
    CHARGER_CHIP_TYPE_1620  = 1,
    CHARGER_CHIP_TYPE_1622  = 2,
};

enum CHARGER_CHARGE_STATUE_E {
    CHARGER_CHARGE_STATUS_IDLE    = 0,
    CHARGER_CHARGE_STATUS_PRE     = 2,
    CHARGER_CHARGE_STATUS_FAST    = 3,
    CHARGER_CHARGE_STATUS_FAULT   = 5,
    CHARGER_CHARGE_STATUS_DONE    = 7,

    CHARGER_CHARGE_STATUS_QTY,
};

enum CHARGER_CHARGE_PRE2CC_VOLTAGE_E {
    CHARGER_CHARGE_PRE2CC_VOLTAGE_2800MV = 0,
    CHARGER_CHARGE_PRE2CC_VOLTAGE_2900MV = 1,
    CHARGER_CHARGE_PRE2CC_VOLTAGE_3000MV = 2, // default
    CHARGER_CHARGE_PRE2CC_VOLTAGE_3100MV = 3,

    CHARGER_CHARGE_PRE2CC_VOLTAGE_QTY,
};

enum CHARGER_CHARGE_PRE2CC_CURRENT_E {
    CHARGER_CHARGE_PRE2CC_CURRENT_1MA  = 5,
    CHARGER_CHARGE_PRE2CC_CURRENT_2MA  = 10,
    CHARGER_CHARGE_PRE2CC_CURRENT_3MA  = 15,
    CHARGER_CHARGE_PRE2CC_CURRENT_4MA  = 20,
    CHARGER_CHARGE_PRE2CC_CURRENT_5MA  = 25,
    CHARGER_CHARGE_PRE2CC_CURRENT_6MA  = 30,
    CHARGER_CHARGE_PRE2CC_CURRENT_7MA  = 35, // default
    CHARGER_CHARGE_PRE2CC_CURRENT_8MA  = 40,
    CHARGER_CHARGE_PRE2CC_CURRENT_9MA  = 45,
    CHARGER_CHARGE_PRE2CC_CURRENT_10MA = 50,
    CHARGER_CHARGE_PRE2CC_CURRENT_11MA = 55,
    CHARGER_CHARGE_PRE2CC_CURRENT_12MA = 60,
    CHARGER_CHARGE_PRE2CC_CURRENT_14MA = 67,
    CHARGER_CHARGE_PRE2CC_CURRENT_16MA = 72,
    CHARGER_CHARGE_PRE2CC_CURRENT_18MA = 77,
    CHARGER_CHARGE_PRE2CC_CURRENT_20MA = 82,
    CHARGER_CHARGE_PRE2CC_CURRENT_22MA = 87,
    CHARGER_CHARGE_PRE2CC_CURRENT_24MA = 92,
    CHARGER_CHARGE_PRE2CC_CURRENT_26MA = 97,
    CHARGER_CHARGE_PRE2CC_CURRENT_28MA = 102,
    CHARGER_CHARGE_PRE2CC_CURRENT_30MA = 107,

    CHARGER_CHARGE_PRE2CC_CURRENT_QTY,
};

enum CHARGER_CHARGE_CONSTANT_CURRENT_E {
    CHARGER_CHARGE_CONSTANT_CURRENT_2MA   = 1,
    CHARGER_CHARGE_CONSTANT_CURRENT_4MA   = 2,
    CHARGER_CHARGE_CONSTANT_CURRENT_6MA   = 3,
    CHARGER_CHARGE_CONSTANT_CURRENT_8MA   = 4,
    CHARGER_CHARGE_CONSTANT_CURRENT_10MA  = 5,
    CHARGER_CHARGE_CONSTANT_CURRENT_14MA  = 7, // default(ver>0)
    CHARGER_CHARGE_CONSTANT_CURRENT_20MA  = 10,
    CHARGER_CHARGE_CONSTANT_CURRENT_30MA  = 15, // default
    CHARGER_CHARGE_CONSTANT_CURRENT_40MA  = 20,
    CHARGER_CHARGE_CONSTANT_CURRENT_50MA  = 25,
    CHARGER_CHARGE_CONSTANT_CURRENT_60MA  = 30,
    CHARGER_CHARGE_CONSTANT_CURRENT_70MA  = 35,
    CHARGER_CHARGE_CONSTANT_CURRENT_80MA  = 40,
    CHARGER_CHARGE_CONSTANT_CURRENT_90MA  = 45,
    CHARGER_CHARGE_CONSTANT_CURRENT_100MA = 50,
    CHARGER_CHARGE_CONSTANT_CURRENT_110MA = 55,
    CHARGER_CHARGE_CONSTANT_CURRENT_120MA = 60,
    CHARGER_CHARGE_CONSTANT_CURRENT_140MA = 67,
    CHARGER_CHARGE_CONSTANT_CURRENT_160MA = 72,
    CHARGER_CHARGE_CONSTANT_CURRENT_180MA = 77,
    CHARGER_CHARGE_CONSTANT_CURRENT_200MA = 82,
    CHARGER_CHARGE_CONSTANT_CURRENT_220MA = 87,
    CHARGER_CHARGE_CONSTANT_CURRENT_240MA = 92,
    CHARGER_CHARGE_CONSTANT_CURRENT_260MA = 97,
    CHARGER_CHARGE_CONSTANT_CURRENT_280MA = 102,
    CHARGER_CHARGE_CONSTANT_CURRENT_300MA = 107,

    CHARGER_CHARGE_CONSTANT_CURRENT_QTY,
};

enum CHARGER_CHARGE_STOP_CURRENT_E {
    CHARGER_CHARGE_STOP_CURRENT_1MA  = 5,
    CHARGER_CHARGE_STOP_CURRENT_2MA  = 10, // default
    CHARGER_CHARGE_STOP_CURRENT_3MA  = 15,
    CHARGER_CHARGE_STOP_CURRENT_4MA  = 20,
    CHARGER_CHARGE_STOP_CURRENT_5MA  = 25,
    CHARGER_CHARGE_STOP_CURRENT_6MA  = 30,
    CHARGER_CHARGE_STOP_CURRENT_7MA  = 35,
    CHARGER_CHARGE_STOP_CURRENT_8MA  = 40 ,
    CHARGER_CHARGE_STOP_CURRENT_9MA  = 45,
    CHARGER_CHARGE_STOP_CURRENT_10MA = 50,
    CHARGER_CHARGE_STOP_CURRENT_11MA = 55,
    CHARGER_CHARGE_STOP_CURRENT_12MA = 60,
    CHARGER_CHARGE_STOP_CURRENT_14MA = 67,
    CHARGER_CHARGE_STOP_CURRENT_16MA = 72,
    CHARGER_CHARGE_STOP_CURRENT_18MA = 77,
    CHARGER_CHARGE_STOP_CURRENT_20MA = 82,
    CHARGER_CHARGE_STOP_CURRENT_22MA = 87,
    CHARGER_CHARGE_STOP_CURRENT_24MA = 92,
    CHARGER_CHARGE_STOP_CURRENT_26MA = 97,
    CHARGER_CHARGE_STOP_CURRENT_28MA = 102,
    CHARGER_CHARGE_STOP_CURRENT_30MA = 107,

    CHARGER_CHARGE_STOP_CURRENT_QTY,
};

enum CHARGER_CHARGE_CONSTANT_VOLTAGE_E {
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4000MV = 0,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4010MV = 1,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4020MV = 2,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4030MV = 3,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4040MV = 4,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4050MV = 5,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4060MV = 6,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4070MV = 7,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4080MV = 8,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4090MV = 9,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4100MV = 10,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4110MV = 11,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4120MV = 12,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4130MV = 13,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4140MV = 14,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4150MV = 15,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4160MV = 16,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4170MV = 17,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4180MV = 18,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4190MV = 19,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4200MV = 20, // default
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4210MV = 21,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4220MV = 22,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4230MV = 23,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4240MV = 24,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4250MV = 25,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4260MV = 26,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4270MV = 27,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4280MV = 28,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4290MV = 29,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4300MV = 30,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4310MV = 31,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4320MV = 32,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4330MV = 33,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4340MV = 34,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4350MV = 35,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4360MV = 36,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4370MV = 37,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4380MV = 38,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4390MV = 39,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4400MV = 40,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4410MV = 41,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4420MV = 42,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4430MV = 43,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4440MV = 44,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4450MV = 45,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4460MV = 46,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4470MV = 47,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4480MV = 48,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4490MV = 49,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4500MV = 50,
    CHARGER_CHARGE_CONSTANT_VOLTAGE_4600MV = 60,

    CHARGER_CHARGE_CONSTANT_VOLTAGE_QTY,
};

enum CHARGER_ACIN2VSYS_LIMIT_CURRENT_E {
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_50MA  = 2,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_100MA = 4,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_150MA = 6,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_200MA = 8, // default
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_250MA = 10,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_300MA = 12,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_400MA = 16,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_500MA = 20,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_600MA = 24,
    CHARGER_ACIN2VSYS_LIMIT_CURRENT_700MA = 28,

    CHARGER_ACIN2VSYS_LIMIT_CURRENT_QTY,
};

enum CHARGER_ACIN2VSYS_VSYS_VOLTAGE_E {
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4200MV = 0,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4300MV = 1,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4400MV = 2,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4500MV = 3,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4600MV = 4, // default
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4700MV = 5,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4800MV = 6,
    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_4900MV = 7,

    CHARGER_ACIN2VSYS_VSYS_VOLTAGE_QTY,
};

enum CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_E {
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3300MV = 0,
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3400MV = 1,
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3500MV = 2,
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3600MV = 3,
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3700MV = 4,
    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_3800MV = 5, // default

    CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_QTY,
};

typedef void (*CHARGER_CHARGE_IRQ_HANDLER_T)(uint32_t status);

enum CHARGER_CHARGE_STATUE_E charger_charge_status_get(void);

int charger_charge_pre2cc_volt_set(enum CHARGER_CHARGE_PRE2CC_VOLTAGE_E pre2cc_volt);

int charger_charge_pre2cc_current_set(enum CHARGER_CHARGE_PRE2CC_CURRENT_E pre2cc_current);

int charger_charge_cc_current_set(enum CHARGER_CHARGE_CONSTANT_CURRENT_E cc_current);

int charger_charge_stop_current_set(enum CHARGER_CHARGE_STOP_CURRENT_E stop_current);

int charger_charge_cv_volt_set(enum CHARGER_CHARGE_CONSTANT_VOLTAGE_E cv_volt);

int charger_acin2vsys_limit_current_set(enum CHARGER_ACIN2VSYS_LIMIT_CURRENT_E  limit_current);

int charger_acin2vsys_vsys_volt_set(enum CHARGER_ACIN2VSYS_VSYS_VOLTAGE_E vsys_volt);

int charger_acin2vsys_vsys_min_volt_set(enum CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_E vsys_min_volt);

enum CHARGER_CHARGE_PRE2CC_VOLTAGE_E charger_charge_pre2cc_volt_get(void);

enum CHARGER_CHARGE_PRE2CC_CURRENT_E charger_charge_pre2cc_current_get(void);

enum CHARGER_CHARGE_CONSTANT_CURRENT_E charger_charge_cc_current_get(void);

enum CHARGER_CHARGE_STOP_CURRENT_E charger_charge_stop_current_get(void);

enum CHARGER_CHARGE_CONSTANT_VOLTAGE_E charger_charge_cv_volt_get(void);

enum CHARGER_ACIN2VSYS_LIMIT_CURRENT_E charger_acin2vsys_limit_current_get(void);

enum CHARGER_ACIN2VSYS_VSYS_VOLTAGE_E charger_acin2vsys_vsys_volt_get(void);

enum CHARGER_ACIN2VSYS_VSYS_MIN_VOLTAGE_E charger_acin2vsys_vsys_min_volt_get(void);

int charger_charge_forward_enable(void);

int charger_charge_forward_disable(void);

int charger_charge_recharge_enable(void);

int charger_charge_recharge_disable(void);

int charger_charge_enable(void);

int charger_charge_disable(void);

int charger_charge_open(void);

int charger_charge_close(void);

enum CHARGER_CHIP_TYPE_E charger_get_charger_type(void);

int charger_charge_irq_handler_set(CHARGER_CHARGE_IRQ_HANDLER_T handler);

void charger_shipmode(void);

void charger_reboot(void);

#ifdef __cplusplus
}
#endif

#endif
