/***************************************************************************
 *
 * Copyright 2015-2023 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __REG_ANALOG_BEST1306P_H__
#define __REG_ANALOG_BEST1306P_H__

#include "plat_types.h"

enum ANA_REG_T {
    ANA_REG_00 = 0x00,
    ANA_REG_01,
    ANA_REG_02,
    ANA_REG_03,
    ANA_REG_04,
    ANA_REG_05,
    ANA_REG_06,
    ANA_REG_07,
    ANA_REG_08,
    ANA_REG_09,
    ANA_REG_0A,
    ANA_REG_0B,
    ANA_REG_0C,
    ANA_REG_0D,
    ANA_REG_0E,
    ANA_REG_0F,
    ANA_REG_10,
    ANA_REG_11,
    ANA_REG_12,
    ANA_REG_13,
    ANA_REG_14,
    ANA_REG_15,
    ANA_REG_16,
    ANA_REG_17,
    ANA_REG_18,
    ANA_REG_19,
    ANA_REG_1A,
    ANA_REG_1B,
    ANA_REG_1C,
    ANA_REG_1D,
    ANA_REG_1E,
    ANA_REG_1F,
    ANA_REG_20,
    ANA_REG_21,
    ANA_REG_22,
    ANA_REG_23,
    ANA_REG_24,
    ANA_REG_25,
    ANA_REG_26,
    ANA_REG_27,
    ANA_REG_28,
    ANA_REG_29,
    ANA_REG_2A,
    ANA_REG_2B,
    ANA_REG_2C,
    ANA_REG_2D,
    ANA_REG_2E,
    ANA_REG_2F,
    ANA_REG_30,
    ANA_REG_31,
    ANA_REG_32,
    ANA_REG_33,
    ANA_REG_34,
    ANA_REG_35,
    ANA_REG_36,
    ANA_REG_37,
    ANA_REG_38,
    ANA_REG_39,
    ANA_REG_3A,
    ANA_REG_3B,
    ANA_REG_3C,
    ANA_REG_3D,
    ANA_REG_3E,
    ANA_REG_3F,
    ANA_REG_40,
    ANA_REG_41,
    ANA_REG_42,
    ANA_REG_43,
    ANA_REG_44,
    ANA_REG_45,
    ANA_REG_46,
    ANA_REG_47,
    ANA_REG_48,
    ANA_REG_49,
    ANA_REG_4A,
    ANA_REG_4B,
    ANA_REG_4C,
    ANA_REG_4D,
    ANA_REG_4E,
    ANA_REG_4F,
    ANA_REG_50,
    ANA_REG_51,
    ANA_REG_52,
    ANA_REG_53,
    ANA_REG_54,
    ANA_REG_55,
    ANA_REG_56,
    ANA_REG_57,
    ANA_REG_58,
    ANA_REG_59,
    ANA_REG_5A,
    ANA_REG_5B,
    ANA_REG_5C,
    ANA_REG_5D,
    ANA_REG_5E,
    ANA_REG_5F,
    ANA_REG_60,
    ANA_REG_61,
    ANA_REG_62,
    ANA_REG_63,
    ANA_REG_64,
    ANA_REG_65,
    ANA_REG_66,
    ANA_REG_67,
    ANA_REG_68,
    ANA_REG_69,
    ANA_REG_6A,
    ANA_REG_6B,
    ANA_REG_6C,
    ANA_REG_6D,
    ANA_REG_6E,
    ANA_REG_6F,
    ANA_REG_70,
    ANA_REG_71,
    ANA_REG_72,
    ANA_REG_73,
    ANA_REG_74,
    ANA_REG_75,
    ANA_REG_76,
    ANA_REG_77,
    ANA_REG_78,
    ANA_REG_79,
    ANA_REG_7A,
    ANA_REG_7B,
    ANA_REG_7C,
    ANA_REG_7D,
    ANA_REG_7E,
    ANA_REG_7F,
    ANA_REG_80,
    ANA_REG_81,
    ANA_REG_82,
    ANA_REG_83,
    ANA_REG_84,
    ANA_REG_85,
    ANA_REG_86,
    ANA_REG_87,
    ANA_REG_88,
    ANA_REG_89,
    ANA_REG_8A,
    ANA_REG_8B,
    ANA_REG_8C,
    ANA_REG_8D,
    ANA_REG_8E,
    ANA_REG_8F,

};

// REG_00
#define REVID_SHIFT                         0
#define REVID_MASK                          (0xF << REVID_SHIFT)
#define REVID(n)                            BITFIELD_VAL(REVID, n)
#define CHIPID_SHIFT                        4
#define CHIPID_MASK                         (0xFFF << CHIPID_SHIFT)
#define CHIPID(n)                           BITFIELD_VAL(CHIPID, n)


// REG_01
#define REG_CODEC_ADCA_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCA_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCA_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCA_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCA_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCA                (1 << 3)
#define CFG_RESET_ADCA_DR                   (1 << 4)
#define REG_CODEC_IDETA_EN                  (1 << 5)
#define REG_CODEC_ADCA_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCA_DITHER_BIT_EN        (1 << 7)
#define CFG_ADCA_DITHER_CLK_INV             (1 << 8)
#define REG_CODEC_ADCA_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCA_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCA_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCA_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCA_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_GAIN_BIT, n)
#define REG_CODEC_ADCA_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCA_DR              (1 << 14)
#define REG_CODEC_ADCA_EN_ZERO_DET          (1 << 15)

// REG_02
#define REG_CODEC_ADCA_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCA_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCA_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCA_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCA_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCA_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT1, n)
#define REG_CODEC_ADCA_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCA_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCA_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT2, n)
#define REG_RC_OSC_CLK_GATE_EN              (1 << 15)

// REG_03
#define REG_CODEC_ADCA_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCA_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCA_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT3, n)
#define REG_CODEC_ADCA_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCA_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP1_IBIT, n)
#define REG_CODEC_ADCA_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCA_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP2_IBIT, n)
#define REG_CODEC_ADCA_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCA_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP3_IBIT, n)
#define REG_CODEC_ADCA_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCA_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP4_IBIT, n)
#define REG_CODEC_ADCA_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCA_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCA_REG_VSEL_SHIFT)
#define REG_CODEC_ADCA_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCA_REG_VSEL, n)

// REG_04
#define REG_CODEC_ADCA_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCA_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCA_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OFFSET, n)
#define REG_CODEC_ADCA_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCA_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP1, n)
#define REG_CODEC_ADCA_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCA_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP2, n)
#define REG_CODEC_ADCA_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCA_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP3, n)

// REG_05
#define REG_CODEC_ADCA_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCA_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP4, n)
#define REG_CODEC_ADCA_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCA_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCA_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCA_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_REG, n)
#define REG_CODEC_ADCA_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCA_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCA_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VCOMP, n)
#define REG_CODEC_ADCA_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCA_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCA_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VREF, n)

// REG_06
#define REG_CODEC_ADCA_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCA_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCA_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCA_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCA_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCA_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCA_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_IDAC2, n)
#define REG_CODEC_ADCA_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCA_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCA_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCA_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCA_OFFSET_CAL_S, n)
#define REG_CODEC_ADCA_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCA_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCA_OFFSET_SW_EN         (1 << 15)

// REG_07
#define REG_CODEC_ADCA_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCA_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCA_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCA_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCA_OFFSET_BIT, n)
#define REG_CODEC_ADCA_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCA_PU_REG               (1 << 15)

// REG_08
#define REG_CODEC_ADCA_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCA_VREF_SEL_MASK        (0xF << REG_CODEC_ADCA_VREF_SEL_SHIFT)
#define REG_CODEC_ADCA_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCA_VREF_SEL, n)
#define REG_CODEC_ADCA_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCA_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCA_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCA_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCA_VREFBUF_BIT, n)
#define ADCA_TIMER_RSTN_DLY_SHIFT           8
#define ADCA_TIMER_RSTN_DLY_MASK            (0x3F << ADCA_TIMER_RSTN_DLY_SHIFT)
#define ADCA_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCA_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCA_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCA_IBP25U_SEL           (1 << 15)

// REG_09
#define REG_CODEC_ADCA_CH_SEL_INT_SHIFT     0
#define REG_CODEC_ADCA_CH_SEL_INT_MASK      (0xF << REG_CODEC_ADCA_CH_SEL_INT_SHIFT)
#define REG_CODEC_ADCA_CH_SEL_INT(n)        BITFIELD_VAL(REG_CODEC_ADCA_CH_SEL_INT, n)
#define ADCA_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCA_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCA_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCA_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCA_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCA_HP_MODE              (1 << 12)
#define REG_CODEC_ADCA_OP1_HP_MODE          (1 << 15)





// REG_11
#define REG_CODEC_ADCB_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCB_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCB_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCB_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCB_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCB                (1 << 3)
#define CFG_RESET_ADCB_DR                   (1 << 4)
#define REG_CODEC_IDETB_EN                  (1 << 5)
#define REG_CODEC_ADCB_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCB_DITHER_BIT_EN        (1 << 7)
#define CFG_ADCB_DITHER_CLK_INV             (1 << 8)
#define REG_CODEC_ADCB_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCB_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCB_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCB_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCB_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_GAIN_BIT, n)
#define REG_CODEC_ADCB_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCB_DR              (1 << 14)
#define REG_CODEC_ADCB_EN_ZERO_DET          (1 << 15)

// REG_12
#define REG_CODEC_ADCB_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCB_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCB_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCB_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCB_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCB_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT1, n)
#define REG_CODEC_ADCB_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCB_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCB_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT2, n)

// REG_13
#define REG_CODEC_ADCB_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCB_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCB_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT3, n)
#define REG_CODEC_ADCB_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCB_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP1_IBIT, n)
#define REG_CODEC_ADCB_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCB_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP2_IBIT, n)
#define REG_CODEC_ADCB_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCB_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP3_IBIT, n)
#define REG_CODEC_ADCB_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCB_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP4_IBIT, n)
#define REG_CODEC_ADCB_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCB_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCB_REG_VSEL_SHIFT)
#define REG_CODEC_ADCB_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCB_REG_VSEL, n)

// REG_14
#define REG_CODEC_ADCB_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCB_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCB_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OFFSET, n)
#define REG_CODEC_ADCB_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCB_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP1, n)
#define REG_CODEC_ADCB_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCB_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP2, n)
#define REG_CODEC_ADCB_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCB_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP3, n)

// REG_15
#define REG_CODEC_ADCB_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCB_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP4, n)
#define REG_CODEC_ADCB_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCB_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCB_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCB_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_REG, n)
#define REG_CODEC_ADCB_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCB_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCB_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VCOMP, n)
#define REG_CODEC_ADCB_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCB_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCB_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VREF, n)

// REG_16
#define REG_CODEC_ADCB_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCB_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCB_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCB_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCB_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCB_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCB_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_IDAC2, n)
#define REG_CODEC_ADCB_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCB_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCB_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCB_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCB_OFFSET_CAL_S, n)
#define REG_CODEC_ADCB_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCB_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCB_OFFSET_SW_EN         (1 << 15)

// REG_17
#define REG_CODEC_ADCB_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCB_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCB_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCB_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCB_OFFSET_BIT, n)
#define REG_CODEC_ADCB_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCB_PU_REG               (1 << 15)

// REG_18
#define REG_CODEC_ADCB_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCB_VREF_SEL_MASK        (0xF << REG_CODEC_ADCB_VREF_SEL_SHIFT)
#define REG_CODEC_ADCB_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCB_VREF_SEL, n)
#define REG_CODEC_ADCB_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCB_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCB_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCB_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCB_VREFBUF_BIT, n)
#define ADCB_TIMER_RSTN_DLY_SHIFT           8
#define ADCB_TIMER_RSTN_DLY_MASK            (0x3F << ADCB_TIMER_RSTN_DLY_SHIFT)
#define ADCB_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCB_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCB_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCB_IBP25U_SEL           (1 << 15)

// REG_19
#define REG_CODEC_ADCB_CH_SEL_SHIFT         0
#define REG_CODEC_ADCB_CH_SEL_MASK          (0xF << REG_CODEC_ADCB_CH_SEL_SHIFT)
#define REG_CODEC_ADCB_CH_SEL(n)            BITFIELD_VAL(REG_CODEC_ADCB_CH_SEL, n)
#define ADCB_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCB_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCB_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCB_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCB_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCB_HP_MODE              (1 << 12)
#define REG_CODEC_ADCB_OP1_HP_MODE          (1 << 15)



// REG_21
#define REG_CODEC_ADCC_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCC_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCC_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCC_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCC_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCC                (1 << 3)
#define CFG_RESET_ADCC_DR                   (1 << 4)
#define REG_CODEC_IDETC_EN                  (1 << 5)
#define REG_CODEC_ADCC_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCC_DITHER_BIT_EN        (1 << 7)
#define CFG_ADCC_DITHER_CLK_INV             (1 << 8)
#define REG_CODEC_ADCC_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCC_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCC_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCC_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCC_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_GAIN_BIT, n)
#define REG_CODEC_ADCC_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCC_DR              (1 << 14)
#define REG_CODEC_ADCC_EN_ZERO_DET          (1 << 15)

// REG_22
#define REG_CODEC_ADCC_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCC_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCC_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCC_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCC_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCC_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT1, n)
#define REG_CODEC_ADCC_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCC_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCC_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT2, n)

// REG_23
#define REG_CODEC_ADCC_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCC_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCC_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT3, n)
#define REG_CODEC_ADCC_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCC_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP1_IBIT, n)
#define REG_CODEC_ADCC_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCC_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP2_IBIT, n)
#define REG_CODEC_ADCC_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCC_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP3_IBIT, n)
#define REG_CODEC_ADCC_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCC_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP4_IBIT, n)
#define REG_CODEC_ADCC_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCC_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCC_REG_VSEL_SHIFT)
#define REG_CODEC_ADCC_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCC_REG_VSEL, n)

// REG_24
#define REG_CODEC_ADCC_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCC_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCC_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OFFSET, n)
#define REG_CODEC_ADCC_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCC_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP1, n)
#define REG_CODEC_ADCC_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCC_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP2, n)
#define REG_CODEC_ADCC_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCC_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP3, n)

// REG_25
#define REG_CODEC_ADCC_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCC_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP4, n)
#define REG_CODEC_ADCC_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCC_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCC_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCC_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_REG, n)
#define REG_CODEC_ADCC_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCC_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCC_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VCOMP, n)
#define REG_CODEC_ADCC_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCC_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCC_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VREF, n)

// REG_26
#define REG_CODEC_ADCC_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCC_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCC_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCC_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCC_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCC_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCC_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_IDAC2, n)
#define REG_CODEC_ADCC_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCC_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCC_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCC_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCC_OFFSET_CAL_S, n)
#define REG_CODEC_ADCC_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCC_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCC_OFFSET_SW_EN         (1 << 15)

// REG_27
#define REG_CODEC_ADCC_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCC_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCC_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCC_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCC_OFFSET_BIT, n)
#define REG_CODEC_ADCC_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCC_PU_REG               (1 << 15)

// REG_28
#define REG_CODEC_ADCC_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCC_VREF_SEL_MASK        (0xF << REG_CODEC_ADCC_VREF_SEL_SHIFT)
#define REG_CODEC_ADCC_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCC_VREF_SEL, n)
#define REG_CODEC_ADCC_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCC_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCC_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCC_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCC_VREFBUF_BIT, n)
#define ADCC_TIMER_RSTN_DLY_SHIFT           8
#define ADCC_TIMER_RSTN_DLY_MASK            (0x3F << ADCC_TIMER_RSTN_DLY_SHIFT)
#define ADCC_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCC_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCC_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCC_IBP25U_SEL           (1 << 15)

// REG_29
#define REG_CODEC_ADCC_CH_SEL_SHIFT         0
#define REG_CODEC_ADCC_CH_SEL_MASK          (0xF << REG_CODEC_ADCC_CH_SEL_SHIFT)
#define REG_CODEC_ADCC_CH_SEL(n)            BITFIELD_VAL(REG_CODEC_ADCC_CH_SEL, n)
#define ADCC_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCC_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCC_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCC_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCC_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCC_HP_MODE              (1 << 12)
#define REG_CODEC_ADCC_OP1_HP_MODE          (1 << 15)

// REG_41
#define REG_CODEC_TX_EN_LDAC                (1 << 0)
#define CFG_TX_CLK_INV                      (1 << 1)
#define REG_CODEC_TX_EN_RDAC                (1 << 2)

// REG_42
#define REG_PU_OSC_PLL24MDAC                (1 << 0)
#define REG_PU_OSC_PLL24MADC                (1 << 1)

// REG_50
#define REG_CODEC_ADC_CAP_BIT               (1 << 0)
#define REG_CODEC_ADC_DITHER0P5_EN          (1 << 1)
#define REG_CODEC_ADC_DITHER0P25_EN         (1 << 2)
#define REG_CODEC_ADC_DITHER1_EN            (1 << 3)
#define REG_CODEC_ADC_DITHER2_EN            (1 << 4)
#define REG_CODEC_ADC_DITHER_PHASE_SEL      (1 << 5)
#define REG_CODEC_ADC_OP1_R_SEL             (1 << 6)
#define REG_CODEC_ADC_OP2_R_SEL             (1 << 7)
#define REG_CODEC_ADC_OP3_R_SEL             (1 << 8)
#define REG_CODEC_ADC_OP4_R_SEL             (1 << 9)
#define REG_CODEC_ADC_RES_SEL_SHIFT         10
#define REG_CODEC_ADC_RES_SEL_MASK          (0x7 << REG_CODEC_ADC_RES_SEL_SHIFT)
#define REG_CODEC_ADC_RES_SEL(n)            BITFIELD_VAL(REG_CODEC_ADC_RES_SEL, n)

// REG_51
#define REG_SEL_CAPSENSOR_OSC               (1 << 0)
#define REG_CFG_CAPSENSOR_DIV_SHIFT         1
#define REG_CFG_CAPSENSOR_DIV_MASK          (0x7FF << REG_CFG_CAPSENSOR_DIV_SHIFT)
#define REG_CFG_CAPSENSOR_DIV(n)            BITFIELD_VAL(REG_CFG_CAPSENSOR_DIV, n)
#define REG_CLK_CAPSENSOR_GATE_EN           (1 << 12)
#define REG_CLK_32K_CAPSENSOR_GATE_EN       (1 << 13)
#define SOFT_RESETN_CAPSENSOR               (1 << 14)
#define SOFT_RESETN_CAPSENSOR_REG           (1 << 15)

// REG_5D
#define REG_IDETLEAR_EN                     (1 << 9)
#define REG_CODEC_TX_REGULATOR_BIT_SHIFT    12
#define REG_CODEC_TX_REGULATOR_BIT_MASK     (0xF << REG_CODEC_TX_REGULATOR_BIT_SHIFT)
#define REG_CODEC_TX_REGULATOR_BIT(n)       BITFIELD_VAL(REG_CODEC_TX_REGULATOR_BIT, n)

// REG_5E
#define REG_CODEC_TX_EAR_DRE_GAIN_L_UPDATE  (1 << 1)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_SHIFT   3
#define REG_CODEC_TX_EAR_DRE_GAIN_L_MASK    (0x1F << REG_CODEC_TX_EAR_DRE_GAIN_L_SHIFT)
#define REG_CODEC_TX_EAR_DRE_GAIN_L(n)      BITFIELD_VAL(REG_CODEC_TX_EAR_DRE_GAIN_L, n)
#define REG_CODEC_TX_EAR_ENBIAS             (1 << 13)
#define REG_CODEC_TX_EAR_LPBIAS             (1 << 14)
#define REG_CODEC_TX_EAR_OCEN_L             (1 << 15)

// REG_5F
#define REG_CODEC_TEST_SEL_SHIFT            0
#define REG_CODEC_TEST_SEL_MASK             (0xF << REG_CODEC_TEST_SEL_SHIFT)
#define REG_CODEC_TEST_SEL(n)               BITFIELD_VAL(REG_CODEC_TEST_SEL, n)
#define REG_CODEC_TX_DAC_VREF_L_SHIFT       8
#define REG_CODEC_TX_DAC_VREF_L_MASK        (0xF << REG_CODEC_TX_DAC_VREF_L_SHIFT)
#define REG_CODEC_TX_DAC_VREF_L(n)          BITFIELD_VAL(REG_CODEC_TX_DAC_VREF_L, n)

// REG_60
#define REG_CODEC_TX_EAR_COMP1_L_SHIFT      0
#define REG_CODEC_TX_EAR_COMP1_L_MASK       (0xFF << REG_CODEC_TX_EAR_COMP1_L_SHIFT)
#define REG_CODEC_TX_EAR_COMP1_L(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_COMP1_L, n)
#define REG_CODEC_TX_DRV_05_L               (1 << 8)

// REG_61
#define REG_CODEC_TX_EAR_LOWGAINL_SHIFT     0
#define REG_CODEC_TX_EAR_LOWGAINL_MASK      (0x3F << REG_CODEC_TX_EAR_LOWGAINL_SHIFT)
#define REG_CODEC_TX_EAR_LOWGAINL(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_LOWGAINL, n)
#define REG_CODEC_TX_EAR_IBSEL_L_SHIFT      12
#define REG_CODEC_TX_EAR_IBSEL_L_MASK       (0x3 << REG_CODEC_TX_EAR_IBSEL_L_SHIFT)
#define REG_CODEC_TX_EAR_IBSEL_L(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_IBSEL_L, n)

// REG_62
#define REG_CODEC_TX_EAR_OFF_BITL_SHIFT     0
#define REG_CODEC_TX_EAR_OFF_BITL_MASK      (0x3FFF << REG_CODEC_TX_EAR_OFF_BITL_SHIFT)
#define REG_CODEC_TX_EAR_OFF_BITL(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_OFF_BITL, n)
#define REG_CODEC_TX_EAR_OFFEN_L            (1 << 14)
#define REG_CODEC_TX_EN_DACLDO              (1 << 15)

// REG_63
#define REG_CODEC_TX_EAR_DIS_SHIFT          14
#define REG_CODEC_TX_EAR_DIS_MASK           (0x3 << REG_CODEC_TX_EAR_DIS_SHIFT)
#define REG_CODEC_TX_EAR_DIS(n)             BITFIELD_VAL(REG_CODEC_TX_EAR_DIS, n)

// REG_64
#define REG_CODEC_TX_EAR_SOFTSTART_SHIFT    0
#define REG_CODEC_TX_EAR_SOFTSTART_MASK     (0x3F << REG_CODEC_TX_EAR_SOFTSTART_SHIFT)
#define REG_CODEC_TX_EAR_SOFTSTART(n)       BITFIELD_VAL(REG_CODEC_TX_EAR_SOFTSTART, n)
#define REG_CODEC_TX_EAR_OUTPUTSEL_L_SHIFT  6
#define REG_CODEC_TX_EAR_OUTPUTSEL_L_MASK   (0x1F << REG_CODEC_TX_EAR_OUTPUTSEL_L_SHIFT)
#define REG_CODEC_TX_EAR_OUTPUTSEL_L(n)     BITFIELD_VAL(REG_CODEC_TX_EAR_OUTPUTSEL_L, n)
#define REG_OCP_SEL_L_SHIFT                 13
#define REG_OCP_SEL_L_MASK                  (0x3 << REG_OCP_SEL_L_SHIFT)
#define REG_OCP_SEL_L(n)                    BITFIELD_VAL(REG_OCP_SEL_L, n)

// REG_65
#define REG_CODEC_TX_EN_EARPA_L             (1 << 0)
#define REG_CODEC_TX_EN_LCLK                (1 << 2)
#define REG_OCP_DET_EN_L                    (1 << 5)
#define REG_CODEC_TX_EN_S1PA_L              (1 << 6)
#define REG_CODEC_TX_EN_S2PA_L              (1 << 7)
#define REG_CODEC_TX_EN_S3PA_L              (1 << 8)
#define REG_CODEC_TX_EN_S4PA_L              (1 << 9)
#define REG_CODEC_TX_EN_S5PA_L              (1 << 10)
#define REG_PU_CODEC_TX_REGULATOR           (1 << 11)
#define REG_BYPASS_CODEC_TX_REGULATOR       (1 << 12)
#define REG_CODEC_DAC_CLK_EDGE_SEL          (1 << 13)
#define REG_CODEC_TX_EAR_GAIN_L             (1 << 14)

// REG_66
#define REG_CODEC_TX_EN_LPPA                (1 << 0)
#define REG_CODEC_TX_SW_MODE_L              (1 << 1)
#define DRE_GAIN_SEL_L                      (1 << 2)
#define REG_CODEC_TX_REG_LOWGAIN            (1 << 3)
#define CFG_TX_CH0_MUTE                     (1 << 5)
#define CFG_TX_CH1_MUTE                     (1 << 6)
#define CFG_CODEC_DIN_L_RST                 (1 << 8)
#define REG_CODEC_TX_EAR_VCM_L_SHIFT        9
#define REG_CODEC_TX_EAR_VCM_L_MASK         (0x7 << REG_CODEC_TX_EAR_VCM_L_SHIFT)
#define REG_CODEC_TX_EAR_VCM_L(n)           BITFIELD_VAL(REG_CODEC_TX_EAR_VCM_L, n)
#define CFG_TX_TREE_EN                      (1 << 4)
#define CFG_ADC_CODEC_CLK_INV               (1 << 12)
#define CFG_CODEC_DIN_R_RST                 (1 << 13)

// REG_67
#define CODEC_DIN_L_HI_RSTVAL_SHIFT         0
#define CODEC_DIN_L_HI_RSTVAL_MASK          (0xFFFF << CODEC_DIN_L_HI_RSTVAL_SHIFT)
#define CODEC_DIN_L_HI_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_L_HI_RSTVAL, n)

// REG_68
#define CODEC_DIN_L_LO_RSTVAL_SHIFT         0
#define CODEC_DIN_L_LO_RSTVAL_MASK          (0xFFFF << CODEC_DIN_L_LO_RSTVAL_SHIFT)
#define CODEC_DIN_L_LO_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_L_LO_RSTVAL, n)

// REG_69
#define CODEC_DIN_R_HI_RSTVAL_SHIFT         0
#define CODEC_DIN_R_HI_RSTVAL_MASK          (0xFFFF << CODEC_DIN_R_HI_RSTVAL_SHIFT)
#define CODEC_DIN_R_HI_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_R_HI_RSTVAL, n)

// REG_6A
#define CODEC_DIN_R_LO_RSTVAL_SHIFT         0
#define CODEC_DIN_R_LO_RSTVAL_MASK          (0xFFFF << CODEC_DIN_R_LO_RSTVAL_SHIFT)
#define CODEC_DIN_R_LO_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_R_LO_RSTVAL, n)

// REG_6B
#define REG_CODEC_TX_CASN_L_SHIFT           0
#define REG_CODEC_TX_CASN_L_MASK            (0x3 << REG_CODEC_TX_CASN_L_SHIFT)
#define REG_CODEC_TX_CASN_L(n)              BITFIELD_VAL(REG_CODEC_TX_CASN_L, n)
#define REG_CODEC_TX_CASP_L_SHIFT           4
#define REG_CODEC_TX_CASP_L_MASK            (0x3 << REG_CODEC_TX_CASP_L_SHIFT)
#define REG_CODEC_TX_CASP_L(n)              BITFIELD_VAL(REG_CODEC_TX_CASP_L, n)
#define REG_CODEC_TX_IB_SEL_ST2_L_SHIFT     8
#define REG_CODEC_TX_IB_SEL_ST2_L_MASK      (0x7 << REG_CODEC_TX_IB_SEL_ST2_L_SHIFT)
#define REG_CODEC_TX_IB_SEL_ST2_L(n)        BITFIELD_VAL(REG_CODEC_TX_IB_SEL_ST2_L, n)
#define REG_CODEC_TX_OC_PATH_L              (1 << 11)
#define REG_CODEC_TX_OFF_RANGE_X2_L         (1 << 12)
#define REG_PU_LPO48MADC_INT                (1 << 15)

// REG_6C
#define REG_CODEC_TX_VREFBUF_CAS_L_SHIFT    0
#define REG_CODEC_TX_VREFBUF_CAS_L_MASK     (0x3 << REG_CODEC_TX_VREFBUF_CAS_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_CAS_L(n)       BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CAS_L, n)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L_SHIFT 2
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L_MASK (0x3 << REG_CODEC_TX_VREFBUF_LOWGAIN_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L(n)   BITFIELD_VAL(REG_CODEC_TX_VREFBUF_LOWGAIN_L, n)
#define REG_CODEC_TX_VREFBUF_ISEL_L_SHIFT   4
#define REG_CODEC_TX_VREFBUF_ISEL_L_MASK    (0x7 << REG_CODEC_TX_VREFBUF_ISEL_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_ISEL_L(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_ISEL_L, n)
#define REG_CODEC_TX_VREF_RZ_L              (1 << 11)
#define REG_CODEC_TX_VREFBUF_CSEL_L_SHIFT   12
#define REG_CODEC_TX_VREFBUF_CSEL_L_MASK    (0xF << REG_CODEC_TX_VREFBUF_CSEL_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_CSEL_L(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CSEL_L, n)

// REG_6D
#define REG_ZERO_DETECT_CHANGE              (1 << 2)
#define REG_CODEC_TX_VCMO_SEL               (1 << 4)
#define REG_ZERO_DETECT_POWER_DOWN_DIRECT   (1 << 7)
#define REG_ZERO_DETECT_POWER_DOWN          (1 << 8)
#define REG_CLOSE_PA                        (1 << 9)
#define REG_CLOSE_PA_DIRECT                 (1 << 10)
#define REG_CLOSE_SPA                       (1 << 11)
#define REG_CODEC_TX_COMP_CM1_L             (1 << 13)

// REG_6E
#define DIG_CODEC_TX_EN_LDAC_ANA            (1 << 9)
#define REG_CODEC_TX_EAR_GAIN_CHANGE        (1 << 11)

// REG_6F
#define OCP_DET_L_STATUS                    (1 << 5)
#define REG_OCP_DET_L_CLR                   (1 << 7)

// REG_70
#define REG_IDETREAR_EN                     (1 << 0)
#define REG_CODEC_TX_EAR_LOWGAINR_SHIFT     1
#define REG_CODEC_TX_EAR_LOWGAINR_MASK      (0x3F << REG_CODEC_TX_EAR_LOWGAINR_SHIFT)
#define REG_CODEC_TX_EAR_LOWGAINR(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_LOWGAINR, n)
#define REG_CODEC_TX_EAR_OCEN_R             (1 << 7)
#define REG_CODEC_TX_EAR_VCM_R_SHIFT        8
#define REG_CODEC_TX_EAR_VCM_R_MASK         (0x7 << REG_CODEC_TX_EAR_VCM_R_SHIFT)
#define REG_CODEC_TX_EAR_VCM_R(n)           BITFIELD_VAL(REG_CODEC_TX_EAR_VCM_R, n)
#define REG_CODEC_TX_DRV_05_R               (1 << 11)

// REG_71
#define REG_CODEC_TX_EAR_COMP1_R_SHIFT      0
#define REG_CODEC_TX_EAR_COMP1_R_MASK       (0xFF << REG_CODEC_TX_EAR_COMP1_R_SHIFT)
#define REG_CODEC_TX_EAR_COMP1_R(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_COMP1_R, n)
#define REG_CODEC_TX_COMP_CM1_R             (1 << 8)

// REG_72
#define REG_CODEC_TX_EAR_OFF_BITR_SHIFT     0
#define REG_CODEC_TX_EAR_OFF_BITR_MASK      (0x3FFF << REG_CODEC_TX_EAR_OFF_BITR_SHIFT)
#define REG_CODEC_TX_EAR_OFF_BITR(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_OFF_BITR, n)
#define REG_CODEC_TX_EAR_OFFEN_R            (1 << 14)

// REG_73
#define REG_CODEC_TX_EAR_OUTPUTSEL_R_SHIFT  0
#define REG_CODEC_TX_EAR_OUTPUTSEL_R_MASK   (0x1F << REG_CODEC_TX_EAR_OUTPUTSEL_R_SHIFT)
#define REG_CODEC_TX_EAR_OUTPUTSEL_R(n)     BITFIELD_VAL(REG_CODEC_TX_EAR_OUTPUTSEL_R, n)
#define REG_CODEC_TX_EAR_IBSEL_R_SHIFT      5
#define REG_CODEC_TX_EAR_IBSEL_R_MASK       (0x3 << REG_CODEC_TX_EAR_IBSEL_R_SHIFT)
#define REG_CODEC_TX_EAR_IBSEL_R(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_IBSEL_R, n)
#define REG_CODEC_TX_EAR_DRE_GAIN_R_UPDATE  (1 << 7)
#define REG_CODEC_TX_EAR_DRE_GAIN_R_SHIFT   8
#define REG_CODEC_TX_EAR_DRE_GAIN_R_MASK    (0x1F << REG_CODEC_TX_EAR_DRE_GAIN_R_SHIFT)
#define REG_CODEC_TX_EAR_DRE_GAIN_R(n)      BITFIELD_VAL(REG_CODEC_TX_EAR_DRE_GAIN_R, n)
#define DRE_GAIN_SEL_R                      (1 << 13)

// REG_74
#define REG_CODEC_TX_DAC_VREF_R_SHIFT       0
#define REG_CODEC_TX_DAC_VREF_R_MASK        (0xF << REG_CODEC_TX_DAC_VREF_R_SHIFT)
#define REG_CODEC_TX_DAC_VREF_R(n)          BITFIELD_VAL(REG_CODEC_TX_DAC_VREF_R, n)
#define REG_CODEC_TX_SW_MODE_R              (1 << 4)
#define REG_OCP_SEL_R_SHIFT                 5
#define REG_OCP_SEL_R_MASK                  (0x3 << REG_OCP_SEL_R_SHIFT)
#define REG_OCP_SEL_R(n)                    BITFIELD_VAL(REG_OCP_SEL_R, n)
#define REG_CODEC_TX_CASN_R_SHIFT           7
#define REG_CODEC_TX_CASN_R_MASK            (0x3 << REG_CODEC_TX_CASN_R_SHIFT)
#define REG_CODEC_TX_CASN_R(n)              BITFIELD_VAL(REG_CODEC_TX_CASN_R, n)
#define REG_CODEC_TX_CASP_R_SHIFT           9
#define REG_CODEC_TX_CASP_R_MASK            (0x3 << REG_CODEC_TX_CASP_R_SHIFT)
#define REG_CODEC_TX_CASP_R(n)              BITFIELD_VAL(REG_CODEC_TX_CASP_R, n)
#define REG_CODEC_TX_IB_SEL_ST2_R_SHIFT     11
#define REG_CODEC_TX_IB_SEL_ST2_R_MASK      (0x7 << REG_CODEC_TX_IB_SEL_ST2_R_SHIFT)
#define REG_CODEC_TX_IB_SEL_ST2_R(n)        BITFIELD_VAL(REG_CODEC_TX_IB_SEL_ST2_R, n)
#define REG_CODEC_TX_OC_PATH_R              (1 << 14)
#define REG_CODEC_TX_OFF_RANGE_X2_R         (1 << 15)

// REG_75
#define REG_CODEC_TX_VREFBUF_CAS_R_SHIFT    0
#define REG_CODEC_TX_VREFBUF_CAS_R_MASK     (0x3 << REG_CODEC_TX_VREFBUF_CAS_R_SHIFT)
#define REG_CODEC_TX_VREFBUF_CAS_R(n)       BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CAS_R, n)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_R_SHIFT 2
#define REG_CODEC_TX_VREFBUF_LOWGAIN_R_MASK (0x3 << REG_CODEC_TX_VREFBUF_LOWGAIN_R_SHIFT)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_R(n)   BITFIELD_VAL(REG_CODEC_TX_VREFBUF_LOWGAIN_R, n)
#define REG_CODEC_TX_VREFBUF_ISEL_R_SHIFT   4
#define REG_CODEC_TX_VREFBUF_ISEL_R_MASK    (0x7 << REG_CODEC_TX_VREFBUF_ISEL_R_SHIFT)
#define REG_CODEC_TX_VREFBUF_ISEL_R(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_ISEL_R, n)
#define REG_CODEC_TX_VREF_RZ_R              (1 << 11)
#define REG_CODEC_TX_VREFBUF_CSEL_R_SHIFT   12
#define REG_CODEC_TX_VREFBUF_CSEL_R_MASK    (0xF << REG_CODEC_TX_VREFBUF_CSEL_R_SHIFT)
#define REG_CODEC_TX_VREFBUF_CSEL_R(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CSEL_R, n)

// REG_76
#define DIG_CODEC_TX_EN_RDAC_ANA            (1 << 0)
#define REG_CODEC_TX_EN_EARPA_R             (1 << 1)
#define REG_CODEC_TX_EN_RCLK                (1 << 2)
#define REG_OCP_DET_EN_R                    (1 << 3)
#define REG_CODEC_TX_EN_S1PA_R              (1 << 4)
#define REG_CODEC_TX_EN_S2PA_R              (1 << 5)
#define REG_CODEC_TX_EN_S3PA_R              (1 << 6)
#define REG_CODEC_TX_EN_S4PA_R              (1 << 7)
#define REG_CODEC_TX_EN_S5PA_R              (1 << 8)
#define REG_CODEC_TX_EAR_GAIN_R             (1 << 9)
#define OCP_DET_R_STATUS                    (1 << 11)
#define REG_OCP_DET_R_CLR                   (1 << 12)

// REG_80
#define REG_CODEC_EN_ADCA                   (1 << 0)
#define REG_CODEC_EN_ADCB                   (1 << 1)
#define REG_CODEC_EN_ADCC                   (1 << 2)
#define REG_CODEC_BIAS_IBSEL_LP_RSEL_SHIFT  3
#define REG_CODEC_BIAS_IBSEL_LP_RSEL_MASK   (0x3 << REG_CODEC_BIAS_IBSEL_LP_RSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL_LP_RSEL(n)     BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_LP_RSEL, n)
#define REG_CODEC_BIAS_IBSEL_RSEL_SHIFT     5
#define REG_CODEC_BIAS_IBSEL_RSEL_MASK      (0x3 << REG_CODEC_BIAS_IBSEL_RSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL_RSEL(n)        BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_RSEL, n)
#define REG_LPO_SEL                         (1 << 7)
#define CFG_VOICE2OSC                       (1 << 8)
#define REG_CODEC_EN_BIAS                   (1 << 13)
#define REG_CODEC_EN_BIAS_LP                (1 << 14)
#define REG_CODEC_EN_RX_EXT                 (1 << 15)

// REG_81
#define REG_CODEC_BIAS_IBSEL_SHIFT          0
#define REG_CODEC_BIAS_IBSEL_MASK           (0xF << REG_CODEC_BIAS_IBSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL(n)             BITFIELD_VAL(REG_CODEC_BIAS_IBSEL, n)
#define REG_CODEC_BIAS_IBSEL_TX_SHIFT       4
#define REG_CODEC_BIAS_IBSEL_TX_MASK        (0xF << REG_CODEC_BIAS_IBSEL_TX_SHIFT)
#define REG_CODEC_BIAS_IBSEL_TX(n)          BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_TX, n)
#define REG_CODEC_BIAS_IBSEL_VOICE_SHIFT    8
#define REG_CODEC_BIAS_IBSEL_VOICE_MASK     (0xF << REG_CODEC_BIAS_IBSEL_VOICE_SHIFT)
#define REG_CODEC_BIAS_IBSEL_VOICE(n)       BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_VOICE, n)
#define CFG_ADC_START                       (1 << 12)
#define CFG_REG_CLKMUX_DVDD_SEL             (1 << 13)


// REG_82
#define REG_CODEC_EN_VCM                    (1 << 0)
#define REG_CODEC_EN_VCM_BUFFER             (1 << 1)
#define REG_CODEC_LP_VCM                    (1 << 2)
#define REG_CODEC_VCM_LOW_VCM_SHIFT         4
#define REG_CODEC_VCM_LOW_VCM_MASK          (0xF << REG_CODEC_VCM_LOW_VCM_SHIFT)
#define REG_CODEC_VCM_LOW_VCM(n)            BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM, n)
#define REG_CODEC_VCM_LOW_VCM_LP_SHIFT      8
#define REG_CODEC_VCM_LOW_VCM_LP_MASK       (0xF << REG_CODEC_VCM_LOW_VCM_LP_SHIFT)
#define REG_CODEC_VCM_LOW_VCM_LP(n)         BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM_LP, n)
#define REG_CODEC_VCM_LOW_VCM_LPF_SHIFT     12
#define REG_CODEC_VCM_LOW_VCM_LPF_MASK      (0xF << REG_CODEC_VCM_LOW_VCM_LPF_SHIFT)
#define REG_CODEC_VCM_LOW_VCM_LPF(n)        BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM_LPF, n)

// REG_83
#define REG_CODEC_VCM_EN_LPF                (1 << 0)
#define REG_CODEC_BIAS_LOWV                 (1 << 1)
#define REG_CODEC_BIAS_LOWV_LP_SHIFT        8
#define REG_CODEC_BIAS_LOWV_LP_MASK         (0x3 << REG_CODEC_BIAS_LOWV_LP_SHIFT)
#define REG_CODEC_BIAS_LOWV_LP(n)           BITFIELD_VAL(REG_CODEC_BIAS_LOWV_LP, n)
#define REG_CODEC_BUF_LOWPOWER              (1 << 3)
#define REG_CODEC_BUF_LOWPOWER2             (1 << 4)
#define REG_CODEC_BUF_LOWVCM_SHIFT          5
#define REG_CODEC_BUF_LOWVCM_MASK           (0x7 << REG_CODEC_BUF_LOWVCM_SHIFT)
#define REG_CODEC_BUF_LOWVCM(n)             BITFIELD_VAL(REG_CODEC_BUF_LOWVCM, n)
#define REG_CLKMUX_LDO_HP                   (1 << 10)
#define REG_CLKMUX_LDO_VSEL_SHIFT           11
#define REG_CLKMUX_LDO_VSEL_MASK            (0x7 << REG_CLKMUX_LDO_VSEL_SHIFT)
#define REG_CLKMUX_LDO_VSEL(n)              BITFIELD_VAL(REG_CLKMUX_LDO_VSEL, n)



// REG_84
#define CFG_VOICE2ADCE                      (1 << 0)
#define ADC_SEL_VAD_DIG_SHIFT               1
#define ADC_SEL_VAD_DIG_MASK                (0x7 << ADC_SEL_VAD_DIG_SHIFT)
#define ADC_SEL_VAD_DIG(n)                  BITFIELD_VAL(ADC_SEL_VAD_DIG, n)
#define DIG_PU_CLKMUX_LDO0P9                (1 << 5)
#define REG_PU_OSC                          (1 << 6)
#define REG_CLKMUX_DVDD_SEL                 (1 << 7)
#define REG_CRYSTAL_SEL_LV                  (1 << 8)
#define REG_EXTPLL_SEL                      (1 << 9)
#define REG_CODEC_BUF_IBIT_SHIFT            10
#define REG_CODEC_BUF_IBIT_MASK             (0x7 << REG_CODEC_BUF_IBIT_SHIFT)
#define REG_CODEC_BUF_IBIT(n)               BITFIELD_VAL(REG_CODEC_BUF_IBIT, n)
#define REG_CLKMUX_LOWF_IN                  (1 << 13)
#define REG_CODEC_BUF_RSEL                  (1 << 14)



// REG_85
#define RESERVED_ANA_15_0_SHIFT             0
#define RESERVED_ANA_15_0_MASK              (0xFFFF << RESERVED_ANA_15_0_SHIFT)
#define RESERVED_ANA_15_0(n)                BITFIELD_VAL(RESERVED_ANA_15_0, n)

// REG_86
#define RESERVED_ANA_31_16_SHIFT            0
#define RESERVED_ANA_31_16_MASK             (0xFFFF << RESERVED_ANA_31_16_SHIFT)
#define RESERVED_ANA_31_16(n)               BITFIELD_VAL(RESERVED_ANA_31_16, n)

// REG_87
#define RESERVED_ANA_47_32_SHIFT            0
#define RESERVED_ANA_47_32_MASK             (0xFFFF << RESERVED_ANA_47_32_SHIFT)
#define RESERVED_ANA_47_32(n)               BITFIELD_VAL(RESERVED_ANA_47_32, n)

// REG_88
#define RESERVED_ANA_55_48_SHIFT            0
#define RESERVED_ANA_55_48_MASK             (0xFF << RESERVED_ANA_55_48_SHIFT)
#define RESERVED_ANA_55_48(n)               BITFIELD_VAL(RESERVED_ANA_55_48, n)
#define POWER_STATE_SHIFT                   8
#define POWER_STATE_MASK                    (0x7 << POWER_STATE_SHIFT)
#define POWER_STATE(n)                      BITFIELD_VAL(POWER_STATE, n)

// REG_89
#define CHIP_ADDR_I2C_SHIFT                 0
#define CHIP_ADDR_I2C_MASK                  (0x7F << CHIP_ADDR_I2C_SHIFT)
#define CHIP_ADDR_I2C(n)                    BITFIELD_VAL(CHIP_ADDR_I2C, n)

// REG_8A
#define REG_POWER_TIMER1_SHIFT              0
#define REG_POWER_TIMER1_MASK               (0x3F << REG_POWER_TIMER1_SHIFT)
#define REG_POWER_TIMER1(n)                 BITFIELD_VAL(REG_POWER_TIMER1, n)
#define REG_POWER_TIMER2_SHIFT              6
#define REG_POWER_TIMER2_MASK               (0x3F << REG_POWER_TIMER2_SHIFT)
#define REG_POWER_TIMER2(n)                 BITFIELD_VAL(REG_POWER_TIMER2, n)
#define REG_POWERUP                         (1 << 12)
#define REG_PU_CAP_MEM                      (1 << 13)
#define REG_ISO_EN_ANA2CORE_DR              (1 << 14)
#define REG_ISO_EN_ANA2CORE                 (1 << 15)

// REG_8B
#define REG_POWER_TIMER3_SHIFT              0
#define REG_POWER_TIMER3_MASK               (0x3F << REG_POWER_TIMER3_SHIFT)
#define REG_POWER_TIMER3(n)                 BITFIELD_VAL(REG_POWER_TIMER3, n)
#define REG_POWER_TIMER4_SHIFT              6
#define REG_POWER_TIMER4_MASK               (0x3F << REG_POWER_TIMER4_SHIFT)
#define REG_POWER_TIMER4(n)                 BITFIELD_VAL(REG_POWER_TIMER4, n)
#define REG_ISO_EN_DR                       (1 << 12)
#define REG_PSW_EN_DR                       (1 << 13)
#define REG_ISO_EN                          (1 << 14)
#define REG_PSW_EN                          (1 << 15)

// REG_8C
#define REG_POWER_TIMER5_SHIFT              0
#define REG_POWER_TIMER5_MASK               (0x3F << REG_POWER_TIMER5_SHIFT)
#define REG_POWER_TIMER5(n)                 BITFIELD_VAL(REG_POWER_TIMER5, n)
#define REG_POWER_TIMER6_SHIFT              6
#define REG_POWER_TIMER6_MASK               (0x3F << REG_POWER_TIMER6_SHIFT)
#define REG_POWER_TIMER6(n)                 BITFIELD_VAL(REG_POWER_TIMER6, n)
#define REG_RESET_ASSERT_DR                 (1 << 12)
#define REG_RESET_ASSERT                    (1 << 13)
#define REG_ISO_EN_ANA_INF_DR               (1 << 14)
#define REG_ISO_EN_ANA_INF                  (1 << 15)

// REG_8D
#define REG_CLK_DAC_CODEC_DIG_GATE          (1 << 0)
#define REG_CLK_ADC_6M_CODEC_GATE           (1 << 1)
#define REG_RC_OSC_CLK_ADC_DIG_GATE         (1 << 2)
#define REG_CLK_DAC_CODEC_ANA_GATE          (1 << 3)
#define REG_CLK_OSC_PD_GATE                 (1 << 4)
#define REG_CLK_OSC_AON_GATE                (1 << 5)
#define REG_PU_ANA_MASK                     (1 << 6)

#endif

