#### LE-Audio related feature ####
export BLE := 1
export BLE_PERIPHERAL_ONLY := 1
export BLE_AUDIO_ENABLED := 1
export CTKD_ENABLE := 1
export HOST_GEN_FULL_ECDH_KEY := 1
export IS_CTKD_OVER_BR_EDR_ENABLED := 1
export BT_BLEAUDIO_COEXIST ?= 0
export APP_BLE_BIS_DELEG_ENABLE :=0 
export APP_BLE_BIS_SINK_ENABLE :=0 
export APP_BLE_BIS_ASSIST_ENABLE :=0 
export APP_BLE_BIS_SRC_ENABLE :=0

#lea call algo
export GAF_CONVERSATIONAL_STREAM_PROCESS_ENABLE := 1
