# These are macros that will be escaped
export ANC_ASSIST_PROCESS_THREAD ?= 0
export ANC_ASSIST_ALGO_CORE_M55 ?= 0
export ANC_ASSIST_ALGO_CORE_BTH ?= 0

export ANC_ASSIST_LE_AUDIO_SUPPORT ?= 0
export ANC_ASSIST_VPU       ?= 0

# DEMO
export VOICE_ASSIST_DEMO ?= BTH

export VOICE_ASSIST_DEMO_STREAM_ENABLED ?= 0
export VOICE_ASSIST_DEMO_DSP_ENABLED ?= 0

ifneq ($(VOICE_ASSIST_DEMO),0)
export VOICE_ASSIST_DEMO_STREAM_ENABLED := 1
endif

ifeq ($(VOICE_ASSIST_DEMO),BTH)
export VOICE_ASSIST_DEMO_DSP_ENABLED := 1
export ANC_ASSIST_ALGO_CORE_BTH := 1
else ifeq ($(VOICE_ASSIST_DEMO),M55)
export ANC_ASSIST_ALGO_CORE_M55 := 1
endif

ifeq ($(VOICE_ASSIST_DEMO_DSP_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_DEMO_DSP_ENABLED
endif

ifeq ($(VOICE_ASSIST_DEMO_STREAM_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_DEMO_STREAM_ENABLED
endif

# ANC
export VOICE_ASSIST_ANC ?= BTH
export VOICE_ASSIST_ANC_DSP_ENABLED ?= 0
export VOICE_ASSIST_ANC_STREAM_ENABLED ?= 0

ifneq ($(VOICE_ASSIST_ANC),0)
export VOICE_ASSIST_ANC_STREAM_ENABLED := 1
endif

ifeq ($(VOICE_ASSIST_ANC),BTH)
export VOICE_ASSIST_ANC_DSP_ENABLED := 1
export ANC_ASSIST_ALGO_CORE_BTH := 1
else ifeq ($(VOICE_ASSIST_ANC),M55)
export ANC_ASSIST_ALGO_CORE_M55 := 1
endif

ifeq ($(VOICE_ASSIST_ANC_DSP_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_ANC_DSP_ENABLED
endif

ifeq ($(VOICE_ASSIST_ANC_STREAM_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_ANC_STREAM_ENABLED
endif

# ADD USER MACRO
export VOICE_ASSIST_CUSTOM_LEAK_DETECT_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_CUSTOM_LEAK_DETECT_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_CUSTOM_LEAK_DETECT_ENABLED
endif

export VOICE_ASSIST_RECORD_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_RECORD_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_RECORD_ENABLED
endif

ifeq ($(AUDIO_ADJ_EQ),1)
KBUILD_CPPFLAGS += -DAUDIO_ADJ_EQ
endif

export VOICE_ASSIST_AUTO_EQ_SELECTION_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_AUTO_EQ_SELECTION_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_AUTO_EQ_SELECTION_ENABLED
endif

export VOICE_ASSIST_ULTRASOUND_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_ULTRASOUND_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_ULTRASOUND_ENABLED
endif

export VOICE_ASSIST_AI_KWS_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_AI_KWS_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_AI_KWS_ENABLED
endif

export VOICE_ASSIST_FIR_LMS_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_FIR_LMS_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_FIR_LMS_ENABLED
endif

export VOICE_ASSIST_PSAP_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_PSAP_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_PSAP_ENABLED
endif

export VOICE_ASSIST_PSAP_SW_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_PSAP_SW_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_PSAP_SW_ENABLED
endif

export VOICE_ASSIST_AI_VOICE_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_AI_VOICE_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_AI_VOICE_ENABLED
endif

export VOICE_ASSIST_PROMPT_LEAK_DETECT_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_PROMPT_LEAK_DETECT_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_PROMPT_LEAK_DETECT_ENABLED
endif

export VOICE_ASSIST_ONESHOT_ADAPT_ANC_ENABLED ?= 1
ifeq ($(VOICE_ASSIST_ONESHOT_ADAPT_ANC_ENABLED),1)
KBUILD_CPPFLAGS += -DVOICE_ASSIST_ONESHOT_ADAPT_ANC_ENABLED
endif

ifeq ($(ANC_ASSIST_ALGO_CORE_BTH),1)
#
endif

ifeq ($(ANC_ASSIST_ALGO_CORE_M55),1)
export ANC_ASSIST_ALGO_ON_DSP := 1
export ANC_ASSIST_ON_DSP ?= M55
endif