#pragma once
#ifndef __SMF_EVENT_H__
#define __SMF_EVENT_H__
#include <stdint.h>
///
typedef enum {//event id
	//0xAABBCCDD
	// AA: type
	SMF_EVENT_TYPE_DMA = 0x01000000,// DD:device id
	SMF_EVENT_TYPE_ALGO = 0x02000000,
	// BB
	SMF_EVENT_SUB_SILENCE = 0x00010000,
	SMF_EVENT_SUB_NO_DATA = 0x00020000,
	SMF_EVENT_SUB_NO_IRQ = 0x00030000,
	// CC
	SMF_EVENT_ALGO_PA = 0x00000100,
	SMF_EVENT_ALGO_SCO_UP = 0x00000200,
	SMF_EVENT_ALGO_SCO_DOWN = 0x00000300,
	// DD
	SMF_EVENT_DMA_CODEC_RX = 50,
	SMF_EVENT_DMA_CODEC_TX = 51,
	SMF_EVENT_DMA_BTPCM_RX = 52,
	SMF_EVENT_DMA_BTPCM_TX = 53,
	SMF_EVENT_DMA_I2S0_RX = 54,
	SMF_EVENT_DMA_I2S0_TX = 55,
	SMF_EVENT_DMA_I2S1_RX = 72,
	SMF_EVENT_DMA_I2S1_TX = 73,
	SMF_EVENT_DMA_MIC = 51,
	SMF_EVENT_DMA_SPK = 50,
	SMF_EVENT_DMA_SCO_UP = 52,
	SMF_EVENT_DMA_SCO_DOWN = 53,
	SMF_EVENT_DMA_PA = 55,
	SMF_EVENT_DMA_IV = 54,
	SMF_EVENT_DMA_AP_UP = 72,
	SMF_EVENT_DMA_AP_DOWN = 73,
	SMF_EVENT_ALGO_IN = 0x01,
	SMF_EVENT_ALGO_OUT = 0X02,

	//
	SMF_EVENT_DMA_MIC_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_MIC,
	SMF_EVENT_DMA_SPK_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_SPK,
	SMF_EVENT_DMA_SCO_UP_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_SCO_UP,
	SMF_EVENT_DMA_SCO_DOWN_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_SCO_DOWN,
	SMF_EVENT_DMA_PA_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_PA,
	SMF_EVENT_DMA_IV_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_IV,
	SMF_EVENT_DMA_AP_UP_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_AP_UP,
	SMF_EVENT_DMA_AP_DOWN_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_AP_DOWN,
	//
	SMF_EVENT_DMA_CODEC_RX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_CODEC_RX,
	SMF_EVENT_DMA_CODEC_TX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_CODEC_TX,
	SMF_EVENT_DMA_BTPCM_RX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_BTPCM_RX,
	SMF_EVENT_DMA_BTPCM_TX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_BTPCM_TX,
	SMF_EVENT_DMA_I2S0_RX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_I2S0_RX,
	SMF_EVENT_DMA_I2S0_TX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_I2S0_TX,
	SMF_EVENT_DMA_I2S1_RX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_I2S1_RX,
	SMF_EVENT_DMA_I2S1_TX_SILENCE = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_SILENCE | SMF_EVENT_DMA_I2S1_TX,

	SMF_EVENT_DMA_CODEC_RX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_CODEC_RX,
	SMF_EVENT_DMA_CODEC_TX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_CODEC_TX,
	SMF_EVENT_DMA_BTPCM_RX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_BTPCM_RX,
	SMF_EVENT_DMA_BTPCM_TX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_BTPCM_TX,
	SMF_EVENT_DMA_I2S0_RX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_I2S0_RX,
	SMF_EVENT_DMA_I2S0_TX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_I2S0_TX,
	SMF_EVENT_DMA_I2S1_RX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_I2S1_RX,
	SMF_EVENT_DMA_I2S1_TX_NO_DATA = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_DATA | SMF_EVENT_DMA_I2S1_TX,

	SMF_EVENT_DMA_CODEC_RX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_CODEC_RX,
	SMF_EVENT_DMA_CODEC_TX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_CODEC_TX,
	SMF_EVENT_DMA_BTPCM_RX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_BTPCM_RX,
	SMF_EVENT_DMA_BTPCM_TX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_BTPCM_TX,
	SMF_EVENT_DMA_I2S0_RX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_I2S0_RX,
	SMF_EVENT_DMA_I2S0_TX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_I2S0_TX,
	SMF_EVENT_DMA_I2S1_RX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_I2S1_RX,
	SMF_EVENT_DMA_I2S1_TX_NO_IRQ = SMF_EVENT_TYPE_DMA | SMF_EVENT_SUB_NO_IRQ | SMF_EVENT_DMA_I2S1_TX,
	//
	SMF_EVENT_ALGO_PA_IN_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_PA | SMF_EVENT_ALGO_IN,
	SMF_EVENT_ALGO_PA_OUT_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_PA | SMF_EVENT_ALGO_OUT,
	SMF_EVENT_ALGO_SCO_UP_IN_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_SCO_UP | SMF_EVENT_ALGO_IN,
	SMF_EVENT_ALGO_SCO_UP_OUT_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_SCO_UP | SMF_EVENT_ALGO_OUT,
	SMF_EVENT_ALGO_SCO_DOWN_IN_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_SCO_DOWN | SMF_EVENT_ALGO_IN,
	SMF_EVENT_ALGO_SCO_DOWN_OUT_SILENCE = SMF_EVENT_TYPE_ALGO | SMF_EVENT_SUB_SILENCE | SMF_EVENT_ALGO_SCO_DOWN | SMF_EVENT_ALGO_OUT
}smf_event_e;

typedef struct {
	uint32_t event;
	uint32_t position;
	uint32_t params[2];
}smf_event_t;

#endif
