export ANC_ASSIST_ENABLED   ?= 1

### ANC ASSIST CONFIG ###
export VOICE_ASSIST_NOISE               ?= 1
export VOICE_ASSIST_CUSTOM_LEAK_DETECT  ?= 1
export VOICE_ASSIST_PROMPT_LEAK_DETECT  ?= 0
export VOICE_ASSIST_PSAP_NS ?= 0
export VOICE_ASSIST_FF_FIR_LMS ?= 0
export ASSIST_FIR_ANC_OPEN_AGAIN_DETECT ?= 0
export VOICE_ASSIST_ONESHOT_ADAPTIVE_ANC ?=0
export VOICE_ASSIST_NOISE_CLASSIFY ?= 0
export VOICE_ASSIST_ADA_IIR ?= 0
export POWER_KEY_IN_IIR ?= 0
export DEBUG_TEST_ADA_IIR ?= 0
export ASSIST_LOW_RAM_MOD   ?= 0
##### ANC ASSIST DEFINE END ######