#### LE-Audio related feature ####
export BLE := 1
export BLE_PERIPHERAL_ONLY := 1
export BLE_AUDIO_ENABLED := 1
export CTKD_ENABLE := 1
export HOST_GEN_FULL_ECDH_KEY := 1
export IS_CTKD_OVER_BR_EDR_ENABLED := 1
export BT_BLEAUDIO_COEXIST ?= 0
export APP_BLE_BIS_DELEG_ENABLE :=0 
export APP_BLE_BIS_SINK_ENABLE :=0 
export APP_BLE_BIS_ASSIST_ENABLE :=0 
export APP_BLE_BIS_SRC_ENABLE :=0

#lea call algo
export GAF_CONVERSATIONAL_STREAM_PROCESS_ENABLE := 1
export IS_USE_NEW_LC3_CODEC := 1
export AOB_LOW_LATENCY_MODE := 0
export AOB_MOBILE_ENABLED := 0

export CHIP_HAS_CP := 1
export AOB_CODEC_CP := 0
export FAST_RAM_RUN_LC3_CODEC := 1

ifeq ($(BLE_AUDIO_24BIT),1)
KBUILD_CPPFLAGS += -D__BLE_AUDIO_24BIT__
endif

ifeq ($(ALIGNED_WITH_FINAL_AOB_SPEC),1)
KBUILD_CPPFLAGS += -DALIGNED_WITH_FINAL_AOB_SPEC
endif

ifeq ($(AOB_CODEC_CP),1)
KBUILD_CPPFLAGS += -DAOB_CODEC_CP
CHIP_HAS_CP ?= 1
endif

export GAF_CODEC_CROSS_CORE ?= 0
ifeq ($(GAF_CODEC_CROSS_CORE),1)
KBUILD_CPPFLAGS += -DGAF_CODEC_CROSS_CORE

export GAF_ENCODER_CROSS_CORE_USE_M55 ?= 0
ifeq ($(GAF_ENCODER_CROSS_CORE_USE_M55),1)
KBUILD_CPPFLAGS += -DGAF_ENCODER_CROSS_CORE_USE_M55
endif

export GAF_DECODER_CROSS_CORE_USE_M55 ?= 0
ifeq ($(GAF_DECODER_CROSS_CORE_USE_M55),1)
KBUILD_CPPFLAGS += -DGAF_DECODER_CROSS_CORE_USE_M55
endif

export GAF_CODEC_CROSS_CORE_USE_SENS ?= 0
ifeq ($(GAF_CODEC_CROSS_CORE_USE_SENS),1)
KBUILD_CPPFLAGS += -DGAF_CODEC_CROSS_CORE_USE_SENS
endif
endif

ifeq ($(BLE_AUDIO_CSIP_SUPPORT),1)
KBUILD_CPPFLAGS += -DBLE_AUDIO_CSIP_SUPPORT
endif
#### LE-Audio related feature end####
