cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

obj-y := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.c $(cur_dir)*.cpp $(cur_dir)*.S))
obj-y := $(obj-y:.c=.o)
obj-y := $(obj-y:.cpp=.o)
obj-y := $(obj-y:.S=.o)

subdir-ccflags-y += -Iplatform/drivers/ana \
                    $(BLUETOOTH_ADAPTER_INCLUDES)


ifeq ($(VOICE_PROMPT),1)
CFLAGS_app_battery.o += -DMEDIA_PLAYER_SUPPORT
endif

ifeq ($(CHARGER_1802),1)
CFLAGS_app_battery.o += -DCHARGER_1802
endif

subdir-ccflags-y += \
    $(BLUETOOTH_ADAPTER_INCLUDES) \
    $(BT_SERVICE_UX_INCLUDES) \
    -Iutils/cqueue \
    $(BT_BLE_AUDIO_POLICY_INCLUDES) \
    -Iservices/audio_bt \
    -Iplatform/drivers/bt

ifeq ($(BESUI_TWS_EN),1)
subdir-ccflags-y += -Iapps/besui/tws_ui \
	                -Iapps/besui \
                    -Iservices/communication
endif
ifeq ($(BESUI_STEREO_EN),1)
subdir-ccflags-y += -Iapps/besui \
		            -Iapps/besui/stereo_ui
endif

