cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

obj_s := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.S))
obj_c := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.c))
obj_cpp := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.cpp))

obj-y := $(obj_c:.c=.o) $(obj_s:.S=.o) $(obj_cpp:.cpp=.o)

subdir-ccflags-y += \
    -Iservices/audio_bt \
    -Iapps/audioplayers \
    $(BLUETOOTH_ADAPTER_INCLUDES) \
    $(BT_SERVICE_UX_INCLUDES) \
    -Iplatform/drivers/bt \
    -Iutils/cqueue \
    -Iapps/main \
    -Iapps/key \
    -Iapps/common \
    -Iservices/bt_app/ \
    -Iservices/osif/ \
    $(BLE_APP_INCLUDES) \
    $(BT_STACK_INCLUDES) \
    -Iutils/list \
    -Iservices/audio_manager
