obj-y := template/

ifeq ($(SNDP_BUS_MGR),1)
obj-y += bus/
endif

ifeq ($(SNDP_BATTERY_MGR),1)
obj-y += bat_pwr/
endif

ifeq ($(SNDP_CHARGER_PLUG_MGR),1)
obj-y += charger_plug/
endif

ifeq ($(SNDP_CHARGER_MGR),1)
obj-y += charger/
endif

ifeq ($(SNDP_TEMPERATURE_MGR),1)
obj-y += temperature/
endif

ifeq ($(SNDP_COVER_SWITCH_MGR),1)
obj-y += cover_switch/
endif

ifeq ($(SNDP_IOBOX_MGR),1)
obj-y += iobox/
endif

ifeq ($(SNDP_GSENSOR_SUPPORT),1)
obj-y += gsensor/
endif

ifeq ($(SNDP_COMM_POGOPIN),1)
obj-y += pogopin_comm/
endif

ifeq ($(SNDP_HRSENSOR_MGR),1)
obj-y += hrsensor/
endif