cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

obj_s := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.S))
obj_c := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.c))
obj_cpp := $(patsubst $(cur_dir)%,%,$(wildcard $(cur_dir)*.cpp))

obj-y := $(obj_c:.c=.o) $(obj_s:.S=.o) $(obj_cpp:.cpp=.o)

ccflags-y +=  \
	-Iplatform/hal \
	-Iplatform/drivers/sensor/st \
	-Iplatform/drivers/bt \
	-Iapps/common \
	-Imultimedia/algorithms/inc/audio/process/head_track \
	-Iservices/audio_bt \
	-Iapps/dsp_m55 \
