export FAST_XRAM_SECTION_SIZE ?= 0x400

ifeq ($(USE_BASIC_THREADS),1)
ifeq ($(or $(BESUI_APP_EN), $(ANC_APP)), 1)
BESBT_STACK_SIZE := 1024*7
else
BESBT_STACK_SIZE := 1024*3
endif
KBUILD_CPPFLAGS += -DAF_STACK_SIZE=1024*3
KBUILD_CPPFLAGS += -DAPP_THREAD_STACK_SIZE=1024*2
KBUILD_CPPFLAGS += -DINTERSYS_STACK_SIZE=1024
export OS_TIMER_THREAD_STACK_SIZE ?= 0x800
export OS_DYNAMIC_MEM_SIZE ?= 0x5000
endif

KBUILD_CPPFLAGS += -DFAST_XRAM_SECTION_SIZE=$(FAST_XRAM_SECTION_SIZE)
