/***************************************************************************
 *
 * Copyright 2015-2026 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 ****************************************************************************/
#ifndef __REG_ANALOG_BEST1307PH_H__
#define __REG_ANALOG_BEST1307PH_H__

#include "plat_types.h"

enum ANA_REG_T {
    ANA_REG_00 = 0x00,
    ANA_REG_01,
    ANA_REG_02,
    ANA_REG_03,
    ANA_REG_04,
    ANA_REG_05,
    ANA_REG_06,
    ANA_REG_07,
    ANA_REG_08,
    ANA_REG_09,
    ANA_REG_0A,
    ANA_REG_0B,
    ANA_REG_0C,
    ANA_REG_0D,
    ANA_REG_0E,
    ANA_REG_0F,
    ANA_REG_10,
    ANA_REG_11,
    ANA_REG_12,
    ANA_REG_13,
    ANA_REG_14,
    ANA_REG_15,
    ANA_REG_16,
    ANA_REG_17,
    ANA_REG_18,
    ANA_REG_19,
    ANA_REG_1A,
    ANA_REG_1B,
    ANA_REG_1C,
    ANA_REG_1D,
    ANA_REG_1E,
    ANA_REG_1F,
    ANA_REG_20,
    ANA_REG_21,
    ANA_REG_22,
    ANA_REG_23,
    ANA_REG_24,
    ANA_REG_25,
    ANA_REG_26,
    ANA_REG_27,
    ANA_REG_28,
    ANA_REG_29,
    ANA_REG_2A,
    ANA_REG_2B,
    ANA_REG_2C,
    ANA_REG_2D,
    ANA_REG_2E,
    ANA_REG_2F,
    ANA_REG_30,
    ANA_REG_31,
    ANA_REG_32,
    ANA_REG_33,
    ANA_REG_34,
    ANA_REG_35,
    ANA_REG_36,
    ANA_REG_37,
    ANA_REG_38,
    ANA_REG_39,
    ANA_REG_3A,
    ANA_REG_3B,
    ANA_REG_3C,
    ANA_REG_3D,
    ANA_REG_3E,
    ANA_REG_3F,
    ANA_REG_40,
    ANA_REG_41,
    ANA_REG_42,
    ANA_REG_43,
    ANA_REG_44,
    ANA_REG_45,
    ANA_REG_46,
    ANA_REG_47,
    ANA_REG_48,
    ANA_REG_49,
    ANA_REG_4A,
    ANA_REG_4B,
    ANA_REG_4C,
    ANA_REG_4D,
    ANA_REG_4E,
    ANA_REG_4F,
    ANA_REG_50,
    ANA_REG_58 = 0x58,
    ANA_REG_5A = 0x5A,

    ANA_REG_60 = 0x60,
    ANA_REG_61,
    ANA_REG_62,
    ANA_REG_63,
    ANA_REG_64,
    ANA_REG_65,
    ANA_REG_66,
    ANA_REG_67,
    ANA_REG_68,
    ANA_REG_69,
    ANA_REG_6A,
    ANA_REG_6B,
    ANA_REG_6C,
    ANA_REG_6D,
    ANA_REG_6E,
    ANA_REG_6F,
    ANA_REG_70,
    ANA_REG_71,
    ANA_REG_72,
    ANA_REG_73,
    ANA_REG_74,
    ANA_REG_75,
    ANA_REG_76,
    ANA_REG_77,
    ANA_REG_78,
    ANA_REG_79,
    ANA_REG_7A,
    ANA_REG_7B,
    ANA_REG_7C,
    ANA_REG_7D,
    ANA_REG_7E,
    ANA_REG_7F,
    ANA_REG_80,
    ANA_REG_81,
    ANA_REG_82,
    ANA_REG_83,
    ANA_REG_84,
    ANA_REG_85,
    ANA_REG_86,
    ANA_REG_87,
    ANA_REG_88,
    ANA_REG_89,
    ANA_REG_8A,
    ANA_REG_8B,
    ANA_REG_8C,
    ANA_REG_8D,
    ANA_REG_8E,
    ANA_REG_8F,
    ANA_REG_90,
    ANA_REG_91,
    ANA_REG_92,
    ANA_REG_93,
    ANA_REG_94,
    ANA_REG_95,
    ANA_REG_96,
    ANA_REG_97,
    ANA_REG_98,
    ANA_REG_99,
    ANA_REG_9A,
    ANA_REG_9B,
    ANA_REG_9C,
    ANA_REG_9D,
    ANA_REG_9E,
    ANA_REG_9F,
    ANA_REG_A0,
    ANA_REG_A1,
    ANA_REG_A2,
    ANA_REG_A3,
    ANA_REG_A4,
    ANA_REG_A5,
    ANA_REG_A6,
    ANA_REG_A7,
    ANA_REG_A8,
    ANA_REG_A9,
    ANA_REG_AA,
    ANA_REG_AB,
    ANA_REG_AC,
    ANA_REG_AD,
    ANA_REG_AE,
    ANA_REG_AF,
    ANA_REG_B0,
    ANA_REG_B1,
    ANA_REG_B2,

    ANA_REG_101 = 0x101,
    ANA_REG_102,
    ANA_REG_103,
    ANA_REG_104,
    ANA_REG_105,
    ANA_REG_106,
    ANA_REG_107,
    ANA_REG_108,
    ANA_REG_109,
    ANA_REG_10A,
    ANA_REG_10B,
    ANA_REG_10C,
    ANA_REG_10D,
    ANA_REG_10E,
    ANA_REG_10F,
    ANA_REG_110,
    ANA_REG_111,
    ANA_REG_112,
    ANA_REG_113,
    ANA_REG_114,
    ANA_REG_115,
    ANA_REG_116,
    ANA_REG_117,
    ANA_REG_118,
    ANA_REG_119,
    ANA_REG_11A,
    ANA_REG_11B,
    ANA_REG_11C,
    ANA_REG_11D,
    ANA_REG_11E,
    ANA_REG_11F,
    ANA_REG_120,
    ANA_REG_121,
    ANA_REG_122,
    ANA_REG_123,
    ANA_REG_124,
    ANA_REG_125,
    ANA_REG_126,
    ANA_REG_127,
    ANA_REG_128,
    ANA_REG_129,
    ANA_REG_12A,
    ANA_REG_12B,
    ANA_REG_12C,
    ANA_REG_12D,
    ANA_REG_12E,
    ANA_REG_12F,
    ANA_REG_130,
    ANA_REG_131,
    ANA_REG_132,
    ANA_REG_133,
    ANA_REG_134,
    ANA_REG_135,
    ANA_REG_136,
    ANA_REG_137,
    ANA_REG_138,
    ANA_REG_139,
    ANA_REG_13A,
    ANA_REG_13B,
    ANA_REG_13C,
    ANA_REG_13D,
    ANA_REG_13E,
    ANA_REG_13F,
    ANA_REG_140,
    ANA_REG_141,
    ANA_REG_142,
    ANA_REG_143,
    ANA_REG_144,
    ANA_REG_145,
    ANA_REG_146,
    ANA_REG_147,
    ANA_REG_148,
    ANA_REG_149,
    ANA_REG_14A,
    ANA_REG_14B,
    ANA_REG_14C,
    ANA_REG_14D,
    ANA_REG_14E,
    ANA_REG_14F,
    ANA_REG_150,
    ANA_REG_151,
    ANA_REG_152,
    ANA_REG_153,
    ANA_REG_154,
    ANA_REG_155,
    ANA_REG_156,
    ANA_REG_157,
    ANA_REG_158,
    ANA_REG_159,
    ANA_REG_15A,
    ANA_REG_15B,
    ANA_REG_15C,
    ANA_REG_15D,
    ANA_REG_15E,
    ANA_REG_15F,
    ANA_REG_160,
    ANA_REG_161,
    ANA_REG_162,
    ANA_REG_163,
    ANA_REG_164,
    ANA_REG_165,
    ANA_REG_166,
    ANA_REG_167,
    ANA_REG_168,
    ANA_REG_169,
    ANA_REG_16A,
    ANA_REG_16B,
    ANA_REG_16C,
    ANA_REG_16D,
    ANA_REG_16E,
    ANA_REG_16F,
    ANA_REG_170,
    ANA_REG_171,
    ANA_REG_172,
};

// REG_00
#define REVID_SHIFT                         0
#define REVID_MASK                          (0xF << REVID_SHIFT)
#define REVID(n)                            BITFIELD_VAL(REVID, n)
#define CHIPID_SHIFT                        4
#define CHIPID_MASK                         (0xFFF << CHIPID_SHIFT)
#define CHIPID(n)                           BITFIELD_VAL(CHIPID, n)


// REG_01
#define REG_CODEC_ADCA_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCA_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCA_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCA_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCA_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCA                (1 << 3)
#define CFG_RESET_ADCA_DR                   (1 << 4)
#define REG_CODEC_IDETA_EN                  (1 << 5)
#define REG_CODEC_ADCA_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCA_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCA_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCA_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCA_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCA_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_GAIN_BIT, n)
#define REG_CODEC_ADCA_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCA_DR              (1 << 14)
#define REG_CODEC_ADCA_EN_ZERO_DET          (1 << 15)

// REG_02
#define REG_CODEC_ADCA_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCA_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCA_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCA_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCA_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCA_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT1, n)
#define REG_CODEC_ADCA_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCA_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCA_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT2, n)
#define REG_RC_OSC_CLK_GATE_EN              (1 << 15)

// REG_03
#define REG_CODEC_ADCA_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCA_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCA_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCA_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCA_CAP_BIT3, n)
#define REG_CODEC_ADCA_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCA_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP1_IBIT, n)
#define REG_CODEC_ADCA_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCA_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP2_IBIT, n)
#define REG_CODEC_ADCA_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCA_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP3_IBIT, n)
#define REG_CODEC_ADCA_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCA_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCA_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCA_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCA_OP4_IBIT, n)
#define REG_CODEC_ADCA_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCA_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCA_REG_VSEL_SHIFT)
#define REG_CODEC_ADCA_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCA_REG_VSEL, n)

// REG_04
#define REG_CODEC_ADCA_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCA_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCA_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OFFSET, n)
#define REG_CODEC_ADCA_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCA_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP1, n)
#define REG_CODEC_ADCA_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCA_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP2, n)
#define REG_CODEC_ADCA_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCA_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP3, n)

// REG_05
#define REG_CODEC_ADCA_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCA_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCA_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCA_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_OP4, n)
#define REG_CODEC_ADCA_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCA_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCA_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCA_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_REG, n)
#define REG_CODEC_ADCA_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCA_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCA_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VCOMP, n)
#define REG_CODEC_ADCA_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCA_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCA_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VREF, n)

// REG_06
#define REG_CODEC_ADCA_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCA_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCA_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCA_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCA_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCA_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCA_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCA_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCA_IBSEL_IDAC2, n)
#define REG_CODEC_ADCA_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCA_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCA_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCA_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCA_OFFSET_CAL_S, n)
#define REG_CODEC_ADCA_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCA_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCA_OFFSET_SW_EN         (1 << 15)

// REG_07
#define REG_CODEC_ADCA_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCA_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCA_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCA_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCA_OFFSET_BIT, n)
#define REG_CODEC_ADCA_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCA_PU_REG               (1 << 15)

// REG_08
#define REG_CODEC_ADCA_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCA_VREF_SEL_MASK        (0xF << REG_CODEC_ADCA_VREF_SEL_SHIFT)
#define REG_CODEC_ADCA_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCA_VREF_SEL, n)
#define REG_CODEC_ADCA_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCA_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCA_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCA_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCA_VREFBUF_BIT, n)
#define ADCA_TIMER_RSTN_DLY_SHIFT           8
#define ADCA_TIMER_RSTN_DLY_MASK            (0x3F << ADCA_TIMER_RSTN_DLY_SHIFT)
#define ADCA_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCA_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCA_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCA_IBP25U_SEL           (1 << 15)

// REG_09
#define REG_CODEC_ADCA_CH_SEL_INT_SHIFT     0
#define REG_CODEC_ADCA_CH_SEL_INT_MASK      (0xF << REG_CODEC_ADCA_CH_SEL_INT_SHIFT)
#define REG_CODEC_ADCA_CH_SEL_INT(n)        BITFIELD_VAL(REG_CODEC_ADCA_CH_SEL_INT, n)
#define ADCA_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCA_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCA_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCA_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCA_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCA_HP_MODE              (1 << 12)
#define REG_CODEC_ADCA_OP1_HP_MODE          (1 << 15)

// REG_0A
#define REG_CODEC_ADCA_CAP_BIT              (1 << 0)
#define REG_CODEC_ADCA_OP1_R_SEL            (1 << 1)
#define REG_CODEC_ADCA_OP2_R_SEL            (1 << 2)
#define REG_CODEC_ADCA_OP3_R_SEL            (1 << 3)
#define REG_CODEC_ADCA_OP4_R_SEL            (1 << 4)
#define REG_CODEC_ADCA_RES_SEL_SHIFT        5
#define REG_CODEC_ADCA_RES_SEL_MASK         (0x7 << REG_CODEC_ADCA_RES_SEL_SHIFT)
#define REG_CODEC_ADCA_RES_SEL(n)           BITFIELD_VAL(REG_CODEC_ADCA_RES_SEL, n)

// REG_11
#define REG_CODEC_ADCB_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCB_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCB_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCB_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCB_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCB                (1 << 3)
#define CFG_RESET_ADCB_DR                   (1 << 4)
#define REG_CODEC_IDETB_EN                  (1 << 5)
#define REG_CODEC_ADCB_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCB_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCB_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCB_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCB_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCB_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_GAIN_BIT, n)
#define REG_CODEC_ADCB_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCB_DR              (1 << 14)
#define REG_CODEC_ADCB_EN_ZERO_DET          (1 << 15)

// REG_12
#define REG_CODEC_ADCB_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCB_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCB_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCB_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCB_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCB_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT1, n)
#define REG_CODEC_ADCB_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCB_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCB_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT2, n)

// REG_13
#define REG_CODEC_ADCB_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCB_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCB_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCB_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCB_CAP_BIT3, n)
#define REG_CODEC_ADCB_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCB_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP1_IBIT, n)
#define REG_CODEC_ADCB_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCB_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP2_IBIT, n)
#define REG_CODEC_ADCB_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCB_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP3_IBIT, n)
#define REG_CODEC_ADCB_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCB_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCB_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCB_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCB_OP4_IBIT, n)
#define REG_CODEC_ADCB_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCB_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCB_REG_VSEL_SHIFT)
#define REG_CODEC_ADCB_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCB_REG_VSEL, n)

// REG_14
#define REG_CODEC_ADCB_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCB_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCB_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OFFSET, n)
#define REG_CODEC_ADCB_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCB_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP1, n)
#define REG_CODEC_ADCB_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCB_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP2, n)
#define REG_CODEC_ADCB_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCB_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP3, n)

// REG_15
#define REG_CODEC_ADCB_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCB_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCB_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCB_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_OP4, n)
#define REG_CODEC_ADCB_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCB_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCB_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCB_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_REG, n)
#define REG_CODEC_ADCB_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCB_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCB_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VCOMP, n)
#define REG_CODEC_ADCB_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCB_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCB_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VREF, n)

// REG_16
#define REG_CODEC_ADCB_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCB_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCB_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCB_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCB_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCB_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCB_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCB_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCB_IBSEL_IDAC2, n)
#define REG_CODEC_ADCB_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCB_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCB_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCB_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCB_OFFSET_CAL_S, n)
#define REG_CODEC_ADCB_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCB_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCB_OFFSET_SW_EN         (1 << 15)

// REG_17
#define REG_CODEC_ADCB_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCB_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCB_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCB_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCB_OFFSET_BIT, n)
#define REG_CODEC_ADCB_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCB_PU_REG               (1 << 15)

// REG_18
#define REG_CODEC_ADCB_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCB_VREF_SEL_MASK        (0xF << REG_CODEC_ADCB_VREF_SEL_SHIFT)
#define REG_CODEC_ADCB_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCB_VREF_SEL, n)
#define REG_CODEC_ADCB_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCB_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCB_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCB_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCB_VREFBUF_BIT, n)
#define ADCB_TIMER_RSTN_DLY_SHIFT           8
#define ADCB_TIMER_RSTN_DLY_MASK            (0x3F << ADCB_TIMER_RSTN_DLY_SHIFT)
#define ADCB_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCB_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCB_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCB_IBP25U_SEL           (1 << 15)

// REG_19
#define REG_CODEC_ADCB_CH_SEL_INT_SHIFT     0
#define REG_CODEC_ADCB_CH_SEL_INT_MASK      (0xF << REG_CODEC_ADCB_CH_SEL_INT_SHIFT)
#define REG_CODEC_ADCB_CH_SEL_INT(n)        BITFIELD_VAL(REG_CODEC_ADCB_CH_SEL_INT, n)
#define ADCB_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCB_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCB_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCB_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCB_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCB_HP_MODE              (1 << 12)
#define REG_CODEC_ADCB_OP1_HP_MODE          (1 << 15)

// REG_1A
#define REG_CODEC_ADCB_CAP_BIT              (1 << 0)
#define REG_CODEC_ADCB_OP1_R_SEL            (1 << 1)
#define REG_CODEC_ADCB_OP2_R_SEL            (1 << 2)
#define REG_CODEC_ADCB_OP3_R_SEL            (1 << 3)
#define REG_CODEC_ADCB_OP4_R_SEL            (1 << 4)
#define REG_CODEC_ADCB_RES_SEL_SHIFT        5
#define REG_CODEC_ADCB_RES_SEL_MASK         (0x7 << REG_CODEC_ADCB_RES_SEL_SHIFT)
#define REG_CODEC_ADCB_RES_SEL(n)           BITFIELD_VAL(REG_CODEC_ADCB_RES_SEL, n)

// REG_21
#define REG_CODEC_ADCC_INPUT_CURRENT_SHIFT  0
#define REG_CODEC_ADCC_INPUT_CURRENT_MASK   (0x7 << REG_CODEC_ADCC_INPUT_CURRENT_SHIFT)
#define REG_CODEC_ADCC_INPUT_CURRENT(n)     BITFIELD_VAL(REG_CODEC_ADCC_INPUT_CURRENT, n)
#define REG_CODEC_RESET_ADCC                (1 << 3)
#define CFG_RESET_ADCC_DR                   (1 << 4)
#define REG_CODEC_IDETC_EN                  (1 << 5)
#define REG_CODEC_ADCC_CLK_SEL              (1 << 6)
#define REG_CODEC_ADCC_GAIN_UPDATE          (1 << 9)
#define REG_CODEC_ADCC_GAIN_BIT_SHIFT       10
#define REG_CODEC_ADCC_GAIN_BIT_MASK        (0x7 << REG_CODEC_ADCC_GAIN_BIT_SHIFT)
#define REG_CODEC_ADCC_GAIN_BIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_GAIN_BIT, n)
#define REG_CODEC_ADCC_PRE_CHARGE           (1 << 13)
#define CFG_PRE_CHARGE_ADCC_DR              (1 << 14)
#define REG_CODEC_ADCC_EN_ZERO_DET          (1 << 15)

// REG_22
#define REG_CODEC_ADCC_RES_2P5K_DR          (1 << 0)
#define REG_CODEC_ADCC_RES_2P5K_UPDATE      (1 << 1)
#define REG_CODEC_ADCC_RES_2P5K             (1 << 2)
#define REG_CODEC_ADCC_CAP_BIT1_SHIFT       3
#define REG_CODEC_ADCC_CAP_BIT1_MASK        (0x7F << REG_CODEC_ADCC_CAP_BIT1_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT1(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT1, n)
#define REG_CODEC_ADCC_CAP_BIT2_SHIFT       10
#define REG_CODEC_ADCC_CAP_BIT2_MASK        (0x1F << REG_CODEC_ADCC_CAP_BIT2_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT2(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT2, n)

// REG_23
#define REG_CODEC_ADCC_CAP_BIT3_SHIFT       0
#define REG_CODEC_ADCC_CAP_BIT3_MASK        (0x1F << REG_CODEC_ADCC_CAP_BIT3_SHIFT)
#define REG_CODEC_ADCC_CAP_BIT3(n)          BITFIELD_VAL(REG_CODEC_ADCC_CAP_BIT3, n)
#define REG_CODEC_ADCC_OP1_IBIT_SHIFT       5
#define REG_CODEC_ADCC_OP1_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP1_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP1_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP1_IBIT, n)
#define REG_CODEC_ADCC_OP2_IBIT_SHIFT       7
#define REG_CODEC_ADCC_OP2_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP2_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP2_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP2_IBIT, n)
#define REG_CODEC_ADCC_OP3_IBIT_SHIFT       9
#define REG_CODEC_ADCC_OP3_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP3_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP3_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP3_IBIT, n)
#define REG_CODEC_ADCC_OP4_IBIT_SHIFT       11
#define REG_CODEC_ADCC_OP4_IBIT_MASK        (0x3 << REG_CODEC_ADCC_OP4_IBIT_SHIFT)
#define REG_CODEC_ADCC_OP4_IBIT(n)          BITFIELD_VAL(REG_CODEC_ADCC_OP4_IBIT, n)
#define REG_CODEC_ADCC_REG_VSEL_SHIFT       13
#define REG_CODEC_ADCC_REG_VSEL_MASK        (0x7 << REG_CODEC_ADCC_REG_VSEL_SHIFT)
#define REG_CODEC_ADCC_REG_VSEL(n)          BITFIELD_VAL(REG_CODEC_ADCC_REG_VSEL, n)

// REG_24
#define REG_CODEC_ADCC_IBSEL_OFFSET_SHIFT   0
#define REG_CODEC_ADCC_IBSEL_OFFSET_MASK    (0xF << REG_CODEC_ADCC_IBSEL_OFFSET_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OFFSET(n)      BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OFFSET, n)
#define REG_CODEC_ADCC_IBSEL_OP1_SHIFT      4
#define REG_CODEC_ADCC_IBSEL_OP1_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP1_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP1(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP1, n)
#define REG_CODEC_ADCC_IBSEL_OP2_SHIFT      8
#define REG_CODEC_ADCC_IBSEL_OP2_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP2_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP2(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP2, n)
#define REG_CODEC_ADCC_IBSEL_OP3_SHIFT      12
#define REG_CODEC_ADCC_IBSEL_OP3_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP3_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP3(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP3, n)

// REG_25
#define REG_CODEC_ADCC_IBSEL_OP4_SHIFT      0
#define REG_CODEC_ADCC_IBSEL_OP4_MASK       (0xF << REG_CODEC_ADCC_IBSEL_OP4_SHIFT)
#define REG_CODEC_ADCC_IBSEL_OP4(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_OP4, n)
#define REG_CODEC_ADCC_IBSEL_REG_SHIFT      4
#define REG_CODEC_ADCC_IBSEL_REG_MASK       (0xF << REG_CODEC_ADCC_IBSEL_REG_SHIFT)
#define REG_CODEC_ADCC_IBSEL_REG(n)         BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_REG, n)
#define REG_CODEC_ADCC_IBSEL_VCOMP_SHIFT    8
#define REG_CODEC_ADCC_IBSEL_VCOMP_MASK     (0xF << REG_CODEC_ADCC_IBSEL_VCOMP_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VCOMP(n)       BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VCOMP, n)
#define REG_CODEC_ADCC_IBSEL_VREF_SHIFT     12
#define REG_CODEC_ADCC_IBSEL_VREF_MASK      (0xF << REG_CODEC_ADCC_IBSEL_VREF_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VREF(n)        BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VREF, n)

// REG_26
#define REG_CODEC_ADCC_IBSEL_VREFBUF_SHIFT  0
#define REG_CODEC_ADCC_IBSEL_VREFBUF_MASK   (0xF << REG_CODEC_ADCC_IBSEL_VREFBUF_SHIFT)
#define REG_CODEC_ADCC_IBSEL_VREFBUF(n)     BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_VREFBUF, n)
#define REG_CODEC_ADCC_IBSEL_IDAC2_SHIFT    4
#define REG_CODEC_ADCC_IBSEL_IDAC2_MASK     (0xF << REG_CODEC_ADCC_IBSEL_IDAC2_SHIFT)
#define REG_CODEC_ADCC_IBSEL_IDAC2(n)       BITFIELD_VAL(REG_CODEC_ADCC_IBSEL_IDAC2, n)
#define REG_CODEC_ADCC_OFFSET_CAL_S_SHIFT   8
#define REG_CODEC_ADCC_OFFSET_CAL_S_MASK    (0x1F << REG_CODEC_ADCC_OFFSET_CAL_S_SHIFT)
#define REG_CODEC_ADCC_OFFSET_CAL_S(n)      BITFIELD_VAL(REG_CODEC_ADCC_OFFSET_CAL_S, n)
#define REG_CODEC_ADCC_OFFSET_CURRENT_EN    (1 << 13)
#define REG_CODEC_ADCC_OFFSET_CURRENT_SEL   (1 << 14)
#define REG_CODEC_ADCC_OFFSET_SW_EN         (1 << 15)

// REG_27
#define REG_CODEC_ADCC_OFFSET_BIT_SHIFT     0
#define REG_CODEC_ADCC_OFFSET_BIT_MASK      (0x3FFF << REG_CODEC_ADCC_OFFSET_BIT_SHIFT)
#define REG_CODEC_ADCC_OFFSET_BIT(n)        BITFIELD_VAL(REG_CODEC_ADCC_OFFSET_BIT, n)
#define REG_CODEC_ADCC_DVDD_SEL             (1 << 14)
#define REG_CODEC_ADCC_PU_REG               (1 << 15)

// REG_28
#define REG_CODEC_ADCC_VREF_SEL_SHIFT       0
#define REG_CODEC_ADCC_VREF_SEL_MASK        (0xF << REG_CODEC_ADCC_VREF_SEL_SHIFT)
#define REG_CODEC_ADCC_VREF_SEL(n)          BITFIELD_VAL(REG_CODEC_ADCC_VREF_SEL, n)
#define REG_CODEC_ADCC_VREFBUF_BIT_SHIFT    4
#define REG_CODEC_ADCC_VREFBUF_BIT_MASK     (0xF << REG_CODEC_ADCC_VREFBUF_BIT_SHIFT)
#define REG_CODEC_ADCC_VREFBUF_BIT(n)       BITFIELD_VAL(REG_CODEC_ADCC_VREFBUF_BIT, n)
#define ADCC_TIMER_RSTN_DLY_SHIFT           8
#define ADCC_TIMER_RSTN_DLY_MASK            (0x3F << ADCC_TIMER_RSTN_DLY_SHIFT)
#define ADCC_TIMER_RSTN_DLY(n)              BITFIELD_VAL(ADCC_TIMER_RSTN_DLY, n)
#define REG_CODEC_ADCC_BYPASS_VREFBUFFER    (1 << 14)
#define REG_CODEC_ADCC_IBP25U_SEL           (1 << 15)

// REG_29
#define REG_CODEC_ADCC_CH_SEL_INT_SHIFT     0
#define REG_CODEC_ADCC_CH_SEL_INT_MASK      (0xF << REG_CODEC_ADCC_CH_SEL_INT_SHIFT)
#define REG_CODEC_ADCC_CH_SEL_INT(n)        BITFIELD_VAL(REG_CODEC_ADCC_CH_SEL_INT, n)
#define ADCC_PRE_CHARGE_TIMER_DLY_SHIFT     4
#define ADCC_PRE_CHARGE_TIMER_DLY_MASK      (0xFF << ADCC_PRE_CHARGE_TIMER_DLY_SHIFT)
#define ADCC_PRE_CHARGE_TIMER_DLY(n)        BITFIELD_VAL(ADCC_PRE_CHARGE_TIMER_DLY, n)
#define REG_CODEC_ADCC_HP_MODE              (1 << 12)
#define REG_CODEC_ADCC_OP1_HP_MODE          (1 << 15)

// REG_2A
#define REG_CODEC_ADCC_CAP_BIT              (1 << 0)
#define REG_CODEC_ADCC_OP1_R_SEL            (1 << 1)
#define REG_CODEC_ADCC_OP2_R_SEL            (1 << 2)
#define REG_CODEC_ADCC_OP3_R_SEL            (1 << 3)
#define REG_CODEC_ADCC_OP4_R_SEL            (1 << 4)
#define REG_CODEC_ADCC_RES_SEL_SHIFT        5
#define REG_CODEC_ADCC_RES_SEL_MASK         (0x7 << REG_CODEC_ADCC_RES_SEL_SHIFT)
#define REG_CODEC_ADCC_RES_SEL(n)           BITFIELD_VAL(REG_CODEC_ADCC_RES_SEL, n)

// REG_40
#define REG_CODEC_TX_PEAK_NL_EN             (1 << 0)
#define REG_CODEC_TX_PEAK_PL_EN             (1 << 1)
#define REG_CODEC_TX_PEAK_DET_BIT           (1 << 2)
#define CFG_TX_PEAK_OFF_ADC_EN              (1 << 4)
#define CFG_TX_PEAK_OFF_DAC_EN              (1 << 5)
#define CFG_PEAK_DET_DR                     (1 << 6)
#define CFG_TX_PEAK_OFF_ADC                 (1 << 7)
#define CFG_TX_PEAK_OFF_DAC                 (1 << 8)
#define CFG_PEAK_DET_DB_DELAY_SHIFT         9
#define CFG_PEAK_DET_DB_DELAY_MASK          (0x7 << CFG_PEAK_DET_DB_DELAY_SHIFT)
#define CFG_PEAK_DET_DB_DELAY(n)            BITFIELD_VAL(CFG_PEAK_DET_DB_DELAY, n)
#define TX_PEAK_DET_STATUS                  (1 << 12)
#define TX_PEAK_DET_NL_STATUS               (1 << 13)
#define TX_PEAK_DET_PL_STATUS               (1 << 14)
#define REG_TX_PEAK_INTR_MASK               (1 << 15)

// REG_41
#define REG_CODEC_TX_EN_LDAC                (1 << 0)
#define CFG_TX_CLK_INV                      (1 << 1)

// REG_4E
#define RESERVED_DIG_15_0_SHIFT             0
#define RESERVED_DIG_15_0_MASK              (0xFFFF << RESERVED_DIG_15_0_SHIFT)
#define RESERVED_DIG_15_0(n)                BITFIELD_VAL(RESERVED_DIG_15_0, n)

// REG_4F
#define RESERVED_DIG_31_16_SHIFT            0
#define RESERVED_DIG_31_16_MASK             (0xFFFF << RESERVED_DIG_31_16_SHIFT)
#define RESERVED_DIG_31_16(n)               BITFIELD_VAL(RESERVED_DIG_31_16, n)

// REG_5A
#define REG_SEL_CAPSENSOR_OSC               (1 << 0)
#define REG_CFG_CAPSENSOR_DIV_SHIFT         1
#define REG_CFG_CAPSENSOR_DIV_MASK          (0x7FF << REG_CFG_CAPSENSOR_DIV_SHIFT)
#define REG_CFG_CAPSENSOR_DIV(n)            BITFIELD_VAL(REG_CFG_CAPSENSOR_DIV, n)
#define REG_CLK_CAPSENSOR_GATE_EN           (1 << 12)
#define REG_CLK_32K_CAPSENSOR_GATE_EN       (1 << 13)
#define SOFT_RESETN_CAPSENSOR               (1 << 14)
#define SOFT_RESETN_CAPSENSOR_REG           (1 << 15)

// REG_70
#define REG_BYPASS_COUNTER                  (1 << 0)
#define REG_EN_AGPIO_TEST                   (1 << 1)
#define REG_EN_CLK_ADC_DIG                  (1 << 2)
#define REG_EN_CLK_BT1503_DIG               (1 << 3)
#define REG_EN_CLK_DLATCH                   (1 << 4)
#define REG_EN_CLKADC                       (1 << 5)
#define REG_EN_CLKDAC                       (1 << 6)
#define REG_VOUT_SEL_SHIFT                  7
#define REG_VOUT_SEL_MASK                   (0x7 << REG_VOUT_SEL_SHIFT)
#define REG_VOUT_SEL(n)                     BITFIELD_VAL(REG_VOUT_SEL, n)
#define REG_PWR_BIT_SHIFT                   10
#define REG_PWR_BIT_MASK                    (0x3 << REG_PWR_BIT_SHIFT)
#define REG_PWR_BIT(n)                      BITFIELD_VAL(REG_PWR_BIT, n)
#define REG_OSC_FR_SHIFT                    12
#define REG_OSC_FR_MASK                     (0x7 << REG_OSC_FR_SHIFT)
#define REG_OSC_FR(n)                       BITFIELD_VAL(REG_OSC_FR, n)
#define REG_EN_CLK_CODEC_DIG                (1 << 15)

// REG_71
#define REG_LP_SHIFT                        0
#define REG_LP_MASK                         (0x3 << REG_LP_SHIFT)
#define REG_LP(n)                           BITFIELD_VAL(REG_LP, n)
#define REG_COUNTER_SEL_SHIFT               2
#define REG_COUNTER_SEL_MASK                (0x7 << REG_COUNTER_SEL_SHIFT)
#define REG_COUNTER_SEL(n)                  BITFIELD_VAL(REG_COUNTER_SEL, n)

// REG_72
#define REG_EN_OSC                          (1 << 0)
#define REG_EN_OSC_PU_RC_MASK               (1 << 1)
#define REG_EN_OSC_PU_RC_CAP_MASK           (1 << 2)
#define REG_EN_OSC_PU_RC_CALIB_MASK         (1 << 3)
#define REG_PU_LDO                          (1 << 4)
#define REG_PU_LDO_PU_RC_MASK               (1 << 5)
#define REG_PU_LDO_PU_RC_CAP_MASK           (1 << 6)
#define REG_PU_LDO_PU_RC_CALIB_MASK         (1 << 7)
#define DIG_PU_LPO48M                       (1 << 8)
#define REG_EN_BIAS_LP_PU_RC_MASK           (1 << 9)
#define REG_EN_BIAS_LP_PU_RC_CAP_MASK       (1 << 10)
#define REG_EN_BIAS_LP_PU_RC_CALIB_MASK     (1 << 11)
#define REG_CAP_SENSOR_INTR_MASK            (1 << 12)

// REG_80
#define REG_CODEC_EN_ADCA                   (1 << 0)
#define REG_CODEC_EN_ADCB                   (1 << 1)
#define REG_CODEC_EN_ADCC                   (1 << 2)
#define REG_CODEC_BIAS_IBSEL_LP_RSEL_SHIFT  3
#define REG_CODEC_BIAS_IBSEL_LP_RSEL_MASK   (0x3 << REG_CODEC_BIAS_IBSEL_LP_RSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL_LP_RSEL(n)     BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_LP_RSEL, n)
#define REG_CODEC_BIAS_IBSEL_RSEL_SHIFT     5
#define REG_CODEC_BIAS_IBSEL_RSEL_MASK      (0x3 << REG_CODEC_BIAS_IBSEL_RSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL_RSEL(n)        BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_RSEL, n)
#define REG_LPO_SEL                         (1 << 7)
#define CFG_VOICE2OSC                       (1 << 8)
#define REG_CODEC_EN_BIAS                   (1 << 13)
#define REG_CODEC_EN_BIAS_LP                (1 << 14)
#define REG_CODEC_EN_RX_EXT                 (1 << 15)

// REG_81
#define REG_CODEC_BIAS_IBSEL_SHIFT          0
#define REG_CODEC_BIAS_IBSEL_MASK           (0xF << REG_CODEC_BIAS_IBSEL_SHIFT)
#define REG_CODEC_BIAS_IBSEL(n)             BITFIELD_VAL(REG_CODEC_BIAS_IBSEL, n)
#define REG_CODEC_BIAS_IBSEL_TX_SHIFT       4
#define REG_CODEC_BIAS_IBSEL_TX_MASK        (0xF << REG_CODEC_BIAS_IBSEL_TX_SHIFT)
#define REG_CODEC_BIAS_IBSEL_TX(n)          BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_TX, n)
#define REG_CODEC_BIAS_IBSEL_VOICE_SHIFT    8
#define REG_CODEC_BIAS_IBSEL_VOICE_MASK     (0xF << REG_CODEC_BIAS_IBSEL_VOICE_SHIFT)
#define REG_CODEC_BIAS_IBSEL_VOICE(n)       BITFIELD_VAL(REG_CODEC_BIAS_IBSEL_VOICE, n)
#define CFG_ADC_START                       (1 << 12)
#define CFG_REG_CLKMUX_DVDD_SEL             (1 << 13)


// REG_82
#define REG_CODEC_EN_VCM                    (1 << 0)
#define REG_CODEC_EN_VCM_BUFFER             (1 << 1)
#define REG_CODEC_LP_VCM                    (1 << 2)
#define REG_CODEC_VCM_LOW_VCM_SHIFT         4
#define REG_CODEC_VCM_LOW_VCM_MASK          (0xF << REG_CODEC_VCM_LOW_VCM_SHIFT)
#define REG_CODEC_VCM_LOW_VCM(n)            BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM, n)
#define REG_CODEC_VCM_LOW_VCM_LP_SHIFT      8
#define REG_CODEC_VCM_LOW_VCM_LP_MASK       (0xF << REG_CODEC_VCM_LOW_VCM_LP_SHIFT)
#define REG_CODEC_VCM_LOW_VCM_LP(n)         BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM_LP, n)
#define REG_CODEC_VCM_LOW_VCM_LPF_SHIFT     12
#define REG_CODEC_VCM_LOW_VCM_LPF_MASK      (0xF << REG_CODEC_VCM_LOW_VCM_LPF_SHIFT)
#define REG_CODEC_VCM_LOW_VCM_LPF(n)        BITFIELD_VAL(REG_CODEC_VCM_LOW_VCM_LPF, n)

// REG_83
#define REG_CODEC_VCM_EN_LPF                (1 << 0)
#define REG_CODEC_BIAS_LOWV                 (1 << 1)
#define REG_CODEC_BIAS_LOWV_LP_SHIFT        8
#define REG_CODEC_BIAS_LOWV_LP_MASK         (0x3 << REG_CODEC_BIAS_LOWV_LP_SHIFT)
#define REG_CODEC_BIAS_LOWV_LP(n)           BITFIELD_VAL(REG_CODEC_BIAS_LOWV_LP, n)
#define REG_CODEC_BUF_LOWPOWER              (1 << 3)
#define REG_CODEC_BUF_LOWPOWER2             (1 << 4)
#define REG_CODEC_BUF_LOWVCM_SHIFT          5
#define REG_CODEC_BUF_LOWVCM_MASK           (0x7 << REG_CODEC_BUF_LOWVCM_SHIFT)
#define REG_CODEC_BUF_LOWVCM(n)             BITFIELD_VAL(REG_CODEC_BUF_LOWVCM, n)
#define REG_CLKMUX_LDO_HP                   (1 << 10)
#define REG_CLKMUX_LDO_VSEL_SHIFT           11
#define REG_CLKMUX_LDO_VSEL_MASK            (0x7 << REG_CLKMUX_LDO_VSEL_SHIFT)
#define REG_CLKMUX_LDO_VSEL(n)              BITFIELD_VAL(REG_CLKMUX_LDO_VSEL, n)

// REG_84
#define CFG_VOICE2ADCE                      (1 << 0)
#define ADC_SEL_VAD_DIG_SHIFT               1
#define ADC_SEL_VAD_DIG_MASK                (0x7 << ADC_SEL_VAD_DIG_SHIFT)
#define ADC_SEL_VAD_DIG(n)                  BITFIELD_VAL(ADC_SEL_VAD_DIG, n)
#define DIG_PU_CLKMUX_LDO0P9                (1 << 5)
#define REG_PU_OSC                          (1 << 6)
#define REG_CLKMUX_DVDD_SEL                 (1 << 7)
#define REG_CRYSTAL_SEL_LV                  (1 << 8)
#define REG_EXTPLL_SEL                      (1 << 9)
#define REG_CODEC_BUF_IBIT_SHIFT            10
#define REG_CODEC_BUF_IBIT_MASK             (0x7 << REG_CODEC_BUF_IBIT_SHIFT)
#define REG_CODEC_BUF_IBIT(n)               BITFIELD_VAL(REG_CODEC_BUF_IBIT, n)
#define REG_CLKMUX_LOWF_IN                  (1 << 13)
#define REG_CODEC_BUF_RSEL                  (1 << 14)

// REG_85
#define RESERVED_ANA_15_0_SHIFT             0
#define RESERVED_ANA_15_0_MASK              (0xFFFF << RESERVED_ANA_15_0_SHIFT)
#define RESERVED_ANA_15_0(n)                BITFIELD_VAL(RESERVED_ANA_15_0, n)

// REG_86
#define RESERVED_ANA_31_16_SHIFT            0
#define RESERVED_ANA_31_16_MASK             (0xFFFF << RESERVED_ANA_31_16_SHIFT)
#define RESERVED_ANA_31_16(n)               BITFIELD_VAL(RESERVED_ANA_31_16, n)

// REG_87
#define RESERVED_ANA_LV_15_0_SHIFT          0
#define RESERVED_ANA_LV_15_0_MASK           (0xFFFF << RESERVED_ANA_LV_15_0_SHIFT)
#define RESERVED_ANA_LV_15_0(n)             BITFIELD_VAL(RESERVED_ANA_LV_15_0, n)

// REG_88
#define RESERVED_ANA_LV_24_16_SHIFT         0
#define RESERVED_ANA_LV_24_16_MASK          (0x1FF << RESERVED_ANA_LV_24_16_SHIFT)
#define RESERVED_ANA_LV_24_16(n)            BITFIELD_VAL(RESERVED_ANA_LV_24_16, n)

// REG_89
#define CHIP_ADDR_I2C_SHIFT                 0
#define CHIP_ADDR_I2C_MASK                  (0x7F << CHIP_ADDR_I2C_SHIFT)
#define CHIP_ADDR_I2C(n)                    BITFIELD_VAL(CHIP_ADDR_I2C, n)

// REG_8A
#define REG_CLK_OSC_RC_REF_EN               (1 << 0)
#define REG_CLK_OSC_RC_REF_DIV_SHIFT        1
#define REG_CLK_OSC_RC_REF_DIV_MASK         (0xFF << REG_CLK_OSC_RC_REF_DIV_SHIFT)
#define REG_CLK_OSC_RC_REF_DIV(n)           BITFIELD_VAL(REG_CLK_OSC_RC_REF_DIV, n)
#define REG_REF_RC_CLK_SEL                  (1 << 9)
#define REG_RCOSC_CLK_ADC_DIG_EN            (1 << 10)
#define REG_SOFT_RESETN_RCOSC               (1 << 11)

// REG_8D
#define REG_CLK_DAC_CODEC_DIG_GATE          (1 << 0)
#define REG_CLK_ADC_6M_CODEC_GATE           (1 << 1)
#define REG_RC_OSC_CLK_ADC_DIG_GATE         (1 << 2)
#define REG_CLK_DAC_CODEC_ANA_GATE          (1 << 3)
#define REG_CLK_OSC_GATE                    (1 << 4)
#define REG_PU_ANA_MASK                     (1 << 6)
#define REG_CLK_SAR_RC_EN                   (1 << 7)
#define REG_CLK_SAR_OSC_EN                  (1 << 8)
#define REG_CLK_6M_SAR_CODEC_SEL            (1 << 9)
#define REG_SOFT_RESETN_SAR                 (1 << 10)
#define REG_CLK_SAR_INT_BYPASS              (1 << 11)


// REG_8E
#define REG_IDETLEAR_EN                     (1 << 9)
#define REG_CODEC_TX_REGULATOR_BIT_L_SHIFT  12
#define REG_CODEC_TX_REGULATOR_BIT_L_MASK   (0xF << REG_CODEC_TX_REGULATOR_BIT_L_SHIFT)
#define REG_CODEC_TX_REGULATOR_BIT_L(n)     BITFIELD_VAL(REG_CODEC_TX_REGULATOR_BIT_L, n)

// REG_8F
#define REG_CODEC_TX_EAR_DR_EN              (1 << 0)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_UPDATE  (1 << 1)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_SHIFT   3
#define REG_CODEC_TX_EAR_DRE_GAIN_L_MASK    (0x1F << REG_CODEC_TX_EAR_DRE_GAIN_L_SHIFT)
#define REG_CODEC_TX_EAR_DRE_GAIN_L(n)      BITFIELD_VAL(REG_CODEC_TX_EAR_DRE_GAIN_L, n)
#define REG_CODEC_TEST_SEL_SHIFT            8
#define REG_CODEC_TEST_SEL_MASK             (0xF << REG_CODEC_TEST_SEL_SHIFT)
#define REG_CODEC_TEST_SEL(n)               BITFIELD_VAL(REG_CODEC_TEST_SEL, n)
#define REG_CODEC_TX_EAR_ENBIAS             (1 << 13)
#define REG_CODEC_TX_EAR_LPBIAS             (1 << 14)
#define REG_CODEC_TX_EAR_OCEN_L             (1 << 15)

// REG_90
#define REG_CODEC_TX_EAR_COMP1_L_SHIFT      0
#define REG_CODEC_TX_EAR_COMP1_L_MASK       (0xFF << REG_CODEC_TX_EAR_COMP1_L_SHIFT)
#define REG_CODEC_TX_EAR_COMP1_L(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_COMP1_L, n)
#define REG_CODEC_TX_DAC_VREF_L_SHIFT       8
#define REG_CODEC_TX_DAC_VREF_L_MASK        (0xF << REG_CODEC_TX_DAC_VREF_L_SHIFT)
#define REG_CODEC_TX_DAC_VREF_L(n)          BITFIELD_VAL(REG_CODEC_TX_DAC_VREF_L, n)

// REG_91
#define REG_CODEC_TX_EAR_LOWGAINL_SHIFT     0
#define REG_CODEC_TX_EAR_LOWGAINL_MASK      (0x3F << REG_CODEC_TX_EAR_LOWGAINL_SHIFT)
#define REG_CODEC_TX_EAR_LOWGAINL(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_LOWGAINL, n)
#define REG_CODEC_TX_EAR_IBSEL_L_SHIFT      12
#define REG_CODEC_TX_EAR_IBSEL_L_MASK       (0x3 << REG_CODEC_TX_EAR_IBSEL_L_SHIFT)
#define REG_CODEC_TX_EAR_IBSEL_L(n)         BITFIELD_VAL(REG_CODEC_TX_EAR_IBSEL_L, n)

// REG_92
#define REG_CODEC_TX_EAR_OFF_BITL_SHIFT     0
#define REG_CODEC_TX_EAR_OFF_BITL_MASK      (0x3FFF << REG_CODEC_TX_EAR_OFF_BITL_SHIFT)
#define REG_CODEC_TX_EAR_OFF_BITL(n)        BITFIELD_VAL(REG_CODEC_TX_EAR_OFF_BITL, n)
#define REG_CODEC_TX_EAR_OFFEN_L            (1 << 14)
#define REG_CODEC_TX_EN_DACLDO              (1 << 15)

// REG_93
#define REG_CODEC_TX_ENB_RC_L_SHIFT         0
#define REG_CODEC_TX_ENB_RC_L_MASK          (0x3 << REG_CODEC_TX_ENB_RC_L_SHIFT)
#define REG_CODEC_TX_ENB_RC_L(n)            BITFIELD_VAL(REG_CODEC_TX_ENB_RC_L, n)
#define REG_CODEC_TX_EAR_DIS_SHIFT          14
#define REG_CODEC_TX_EAR_DIS_MASK           (0x3 << REG_CODEC_TX_EAR_DIS_SHIFT)
#define REG_CODEC_TX_EAR_DIS(n)             BITFIELD_VAL(REG_CODEC_TX_EAR_DIS, n)

// REG_94
#define REG_CODEC_TX_EAR_SOFTSTART_SHIFT    0
#define REG_CODEC_TX_EAR_SOFTSTART_MASK     (0x3F << REG_CODEC_TX_EAR_SOFTSTART_SHIFT)
#define REG_CODEC_TX_EAR_SOFTSTART(n)       BITFIELD_VAL(REG_CODEC_TX_EAR_SOFTSTART, n)
#define REG_CODEC_TX_EAR_OUTPUTSEL_L_SHIFT  6
#define REG_CODEC_TX_EAR_OUTPUTSEL_L_MASK   (0x1F << REG_CODEC_TX_EAR_OUTPUTSEL_L_SHIFT)
#define REG_CODEC_TX_EAR_OUTPUTSEL_L(n)     BITFIELD_VAL(REG_CODEC_TX_EAR_OUTPUTSEL_L, n)
#define REG_OCP_SEL_L_SHIFT                 13
#define REG_OCP_SEL_L_MASK                  (0x3 << REG_OCP_SEL_L_SHIFT)
#define REG_OCP_SEL_L(n)                    BITFIELD_VAL(REG_OCP_SEL_L, n)
#define REG_OCP_DET_EN_L                    (1 << 15)

// REG_95
#define REG_CODEC_TX_EN_EARPA_L             (1 << 0)
#define REG_CODEC_TX_EN_LCLK                (1 << 2)
#define REG_CODEC_TX_EAR_GAIN_L_SHIFT       3
#define REG_CODEC_TX_EAR_GAIN_L_MASK        (0x3 << REG_CODEC_TX_EAR_GAIN_L_SHIFT)
#define REG_CODEC_TX_EAR_GAIN_L(n)          BITFIELD_VAL(REG_CODEC_TX_EAR_GAIN_L, n)
#define REG_CODEC_TX_EN_S1PA_L              (1 << 6)
#define REG_CODEC_TX_EN_S2PA_L              (1 << 7)
#define REG_CODEC_TX_EN_S3PA_L              (1 << 8)
#define REG_CODEC_TX_EN_S4PA_L              (1 << 9)
#define REG_CODEC_TX_EN_S5PA_L              (1 << 10)
#define REG_PU_CODEC_TX_REGULATOR_L         (1 << 11)
#define REG_BYPASS_CODEC_TX_REGULATOR       (1 << 12)
#define REG_CODEC_DAC_CLK_EDGE_SEL_L        (1 << 13)
#define REG_OCP_SEL_R_SHIFT                 14
#define REG_OCP_SEL_R_MASK                  (0x3 << REG_OCP_SEL_R_SHIFT)
#define REG_OCP_SEL_R(n)                    BITFIELD_VAL(REG_OCP_SEL_R, n)

// REG_96
#define REG_CODEC_TX_EN_LPPA_L              (1 << 0)
#define REG_CODEC_TX_SW_MODE_L              (1 << 1)
#define DRE_GAIN_SEL_L                      (1 << 2)
#define REG_CODEC_TX_REG_LOWGAIN            (1 << 3)
#define CFG_TX_CH0_MUTE                     (1 << 5)
#define CFG_CODEC_DIN_L_RST                 (1 << 8)
#define REG_CODEC_TX_EAR_VCM_L_SHIFT        9
#define REG_CODEC_TX_EAR_VCM_L_MASK         (0x7 << REG_CODEC_TX_EAR_VCM_L_SHIFT)
#define REG_CODEC_TX_EAR_VCM_L(n)           BITFIELD_VAL(REG_CODEC_TX_EAR_VCM_L, n)
#define CFG_TX_TREE_EN                      (1 << 4)
#define CFG_ADC_CODEC_CLK_INV               (1 << 12)

// REG_97
#define CODEC_DIN_L_HI_RSTVAL_SHIFT         0
#define CODEC_DIN_L_HI_RSTVAL_MASK          (0xFFFF << CODEC_DIN_L_HI_RSTVAL_SHIFT)
#define CODEC_DIN_L_HI_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_L_HI_RSTVAL, n)

// REG_98
#define CODEC_DIN_L_LO_RSTVAL_SHIFT         0
#define CODEC_DIN_L_LO_RSTVAL_MASK          (0xFFFF << CODEC_DIN_L_LO_RSTVAL_SHIFT)
#define CODEC_DIN_L_LO_RSTVAL(n)            BITFIELD_VAL(CODEC_DIN_L_LO_RSTVAL, n)

// REG_99
#define POL_CLK_OSC_ALN                     (1 << 0)
#define REG_CODEC_DIV_EN                    (1 << 1)
#define REG_CODEC_DIV_MODE                  (1 << 2)

// REG_9B
#define REG_CODEC_TX_CASN_L_SHIFT           0
#define REG_CODEC_TX_CASN_L_MASK            (0x3 << REG_CODEC_TX_CASN_L_SHIFT)
#define REG_CODEC_TX_CASN_L(n)              BITFIELD_VAL(REG_CODEC_TX_CASN_L, n)
#define REG_CODEC_TX_CASP_L_SHIFT           4
#define REG_CODEC_TX_CASP_L_MASK            (0x3 << REG_CODEC_TX_CASP_L_SHIFT)
#define REG_CODEC_TX_CASP_L(n)              BITFIELD_VAL(REG_CODEC_TX_CASP_L, n)
#define REG_CODEC_TX_IB_SEL_ST2_L_SHIFT     8
#define REG_CODEC_TX_IB_SEL_ST2_L_MASK      (0x7 << REG_CODEC_TX_IB_SEL_ST2_L_SHIFT)
#define REG_CODEC_TX_IB_SEL_ST2_L(n)        BITFIELD_VAL(REG_CODEC_TX_IB_SEL_ST2_L, n)
#define REG_CODEC_TX_OC_PATH_L              (1 << 11)
#define REG_CODEC_TX_OFF_RANGE_X2_L         (1 << 12)
#define REG_PU_LPO48MADC_INT                (1 << 15)

// REG_9C
#define REG_CODEC_TX_VREFBUF_CAS_L_SHIFT    0
#define REG_CODEC_TX_VREFBUF_CAS_L_MASK     (0x3 << REG_CODEC_TX_VREFBUF_CAS_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_CAS_L(n)       BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CAS_L, n)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L_SHIFT 2
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L_MASK (0x3 << REG_CODEC_TX_VREFBUF_LOWGAIN_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_LOWGAIN_L(n)   BITFIELD_VAL(REG_CODEC_TX_VREFBUF_LOWGAIN_L, n)
#define REG_CODEC_TX_VREFBUF_ISEL_L_SHIFT   4
#define REG_CODEC_TX_VREFBUF_ISEL_L_MASK    (0x7 << REG_CODEC_TX_VREFBUF_ISEL_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_ISEL_L(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_ISEL_L, n)
#define REG_CODEC_TX_VREF_RZ_L              (1 << 11)
#define REG_CODEC_TX_VREFBUF_CSEL_L_SHIFT   12
#define REG_CODEC_TX_VREFBUF_CSEL_L_MASK    (0xF << REG_CODEC_TX_VREFBUF_CSEL_L_SHIFT)
#define REG_CODEC_TX_VREFBUF_CSEL_L(n)      BITFIELD_VAL(REG_CODEC_TX_VREFBUF_CSEL_L, n)


// REG_9D
#define REG_CODEC_TX_OUTPUT_L_LP_DR         (1 << 0)
#define REG_CODEC_TX_OUTPUT_L_LP            (1 << 1)
#define REG_CODEC_TX_HP_DAC_LDO             (1 << 3)
#define REG_CODEC_TX_VCMO_SEL_L             (1 << 4)
#define REG_ZERO_DETECT_POWER_DOWN_DIRECT   (1 << 7)
#define REG_ZERO_DETECT_POWER_DOWN          (1 << 8)
#define REG_CLOSE_PA                        (1 << 9)
#define REG_CLOSE_PA_DIRECT                 (1 << 10)
#define REG_CLOSE_SPA                       (1 << 11)
#define REG_CODEC_TX_OUTPUT_LP_POL          (1 << 12)
#define REG_CODEC_TX_COMP_CM1_L             (1 << 13)
#define REG_CODEC_TX_DRV_05_L               (1 << 14)

// REG_9E
#define DIG_CODEC_TX_EN_LDAC_ANA            (1 << 9)
#define REG_CODEC_TX_EAR_GAIN_CHANGE        (1 << 11)

// REG_9F
#define OCP_DET_L_STATUS                    (1 << 5)
#define REG_OCP_DET_L_CLR                   (1 << 7)

// REG_A0
#define REG_CODEC_TX_EAR_OFF_BITL_1_SHIFT   0
#define REG_CODEC_TX_EAR_OFF_BITL_1_MASK    (0x3FFF << REG_CODEC_TX_EAR_OFF_BITL_1_SHIFT)
#define REG_CODEC_TX_EAR_OFF_BITL_1(n)      BITFIELD_VAL(REG_CODEC_TX_EAR_OFF_BITL_1, n)
#define ANADRE_DC_SEL                       (1 << 14)

// REG_A1
#define REG_CODEC_TX_EAR_OFF_BITL_2_SHIFT   0
#define REG_CODEC_TX_EAR_OFF_BITL_2_MASK    (0x3FFF << REG_CODEC_TX_EAR_OFF_BITL_2_SHIFT)
#define REG_CODEC_TX_EAR_OFF_BITL_2(n)      BITFIELD_VAL(REG_CODEC_TX_EAR_OFF_BITL_2, n)

// REG_A2
#define REG_CODEC_TX_EAR_DRE_GAIN_L_1_SHIFT 0
#define REG_CODEC_TX_EAR_DRE_GAIN_L_1_MASK  (0x1F << REG_CODEC_TX_EAR_DRE_GAIN_L_1_SHIFT)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_1(n)    BITFIELD_VAL(REG_CODEC_TX_EAR_DRE_GAIN_L_1, n)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_2_SHIFT 5
#define REG_CODEC_TX_EAR_DRE_GAIN_L_2_MASK  (0x1F << REG_CODEC_TX_EAR_DRE_GAIN_L_2_SHIFT)
#define REG_CODEC_TX_EAR_DRE_GAIN_L_2(n)    BITFIELD_VAL(REG_CODEC_TX_EAR_DRE_GAIN_L_2, n)
#define ANADRE_GAIN_SEL                     (1 << 10)

// REG_A3
#define RESERVED_DIG_15_0_SHIFT             0
#define RESERVED_DIG_15_0_MASK              (0xFFFF << RESERVED_DIG_15_0_SHIFT)
#define RESERVED_DIG_15_0(n)                BITFIELD_VAL(RESERVED_DIG_15_0, n)

// REG_A4
#define RESERVED_DIG_31_16_SHIFT            0
#define RESERVED_DIG_31_16_MASK             (0xFFFF << RESERVED_DIG_31_16_SHIFT)
#define RESERVED_DIG_31_16(n)               BITFIELD_VAL(RESERVED_DIG_31_16, n)

// REG_A6
#define REG_SEL_RC_TO_CORE_SHIFT            0
#define REG_SEL_RC_TO_CORE_MASK             (0x3 << REG_SEL_RC_TO_CORE_SHIFT)
#define REG_SEL_RC_TO_CORE(n)               BITFIELD_VAL(REG_SEL_RC_TO_CORE, n)
#define REG_SEL_RC_TO_CODEC_SHIFT           2
#define REG_SEL_RC_TO_CODEC_MASK            (0x3 << REG_SEL_RC_TO_CODEC_SHIFT)
#define REG_SEL_RC_TO_CODEC(n)              BITFIELD_VAL(REG_SEL_RC_TO_CODEC, n)

// REG_A8
#define REG_RC_CLK_CALIB_EN                 (1 << 0)
#define REG_RC_CLK_CALIB_POLAR_SEL          (1 << 1)
#define REG_RC_CLK_CALIB_MODE_SHIFT         2
#define REG_RC_CLK_CALIB_MODE_MASK          (0x3 << REG_RC_CLK_CALIB_MODE_SHIFT)
#define REG_RC_CLK_CALIB_MODE(n)            BITFIELD_VAL(REG_RC_CLK_CALIB_MODE, n)
#define REG_FTRIM_ADJ_SHIFT                 4
#define REG_FTRIM_ADJ_MASK                  (0x7 << REG_FTRIM_ADJ_SHIFT)
#define REG_FTRIM_ADJ(n)                    BITFIELD_VAL(REG_FTRIM_ADJ, n)
#define REG_RC_CLK_CALIB_SLOW_CNT_SHIFT     10
#define REG_RC_CLK_CALIB_SLOW_CNT_MASK      (0x3F << REG_RC_CLK_CALIB_SLOW_CNT_SHIFT)
#define REG_RC_CLK_CALIB_SLOW_CNT(n)        BITFIELD_VAL(REG_RC_CLK_CALIB_SLOW_CNT, n)

// REG_A9
#define REG_RC_CLK_CALIB_GOAL_CNT_15_0_SHIFT 0
#define REG_RC_CLK_CALIB_GOAL_CNT_15_0_MASK (0xFFFF << REG_RC_CLK_CALIB_GOAL_CNT_15_0_SHIFT)
#define REG_RC_CLK_CALIB_GOAL_CNT_15_0(n)   BITFIELD_VAL(REG_RC_CLK_CALIB_GOAL_CNT_15_0, n)

// REG_AA
#define REG_RC_CLK_CALIB_GOAL_CNT_16        (1 << 0)
#define REG_RC_CLK_CALIB_REF_CNT_SHIFT      1
#define REG_RC_CLK_CALIB_REF_CNT_MASK       (0x3FF << REG_RC_CLK_CALIB_REF_CNT_SHIFT)
#define REG_RC_CLK_CALIB_REF_CNT(n)         BITFIELD_VAL(REG_RC_CLK_CALIB_REF_CNT, n)
#define REG_RC_CLK_CALIB_SLOW_FINE_MASK     (1 << 11)
#define REG_RC_CLK_CALIB_THRE_DONE_EN       (1 << 12)
#define REG_RC_CLK_CALIB_INIT_SEL           (1 << 13)
#define REG_RC_CLK_CALIB_INIT_VLD_SEL       (1 << 14)

// REG_AB
#define REG_RC_CLK_CALIB_FTRIM_SHIFT        0
#define REG_RC_CLK_CALIB_FTRIM_MASK         (0x1F << REG_RC_CLK_CALIB_FTRIM_SHIFT)
#define REG_RC_CLK_CALIB_FTRIM(n)           BITFIELD_VAL(REG_RC_CLK_CALIB_FTRIM, n)
#define REG_RC_CLK_CALIB_FTRIM_DR           (1 << 5)
#define REG_RC_CLK_CALIB_FTRIM_FINE_SHIFT   6
#define REG_RC_CLK_CALIB_FTRIM_FINE_MASK    (0x3F << REG_RC_CLK_CALIB_FTRIM_FINE_SHIFT)
#define REG_RC_CLK_CALIB_FTRIM_FINE(n)      BITFIELD_VAL(REG_RC_CLK_CALIB_FTRIM_FINE, n)
#define REG_RC_CLK_CALIB_FTRIM_FINE_DR      (1 << 12)
#define REG_RC_CLK_CALIB_DONE_INTR_EN       (1 << 13)
#define REG_RC_CLK_CALIB_DONE_INTR_MASK     (1 << 14)
#define REG_RC_CLK_CALIB_DONE_INTR_CLR      (1 << 15)

// REG_AC
#define RC_CLK_CALIB_GOAL_CNT_15_0_SHIFT    0
#define RC_CLK_CALIB_GOAL_CNT_15_0_MASK     (0xFFFF << RC_CLK_CALIB_GOAL_CNT_15_0_SHIFT)
#define RC_CLK_CALIB_GOAL_CNT_15_0(n)       BITFIELD_VAL(RC_CLK_CALIB_GOAL_CNT_15_0, n)

// REG_AD
#define RC_CLK_CALIB_FTRIM_FINE_SHIFT       0
#define RC_CLK_CALIB_FTRIM_FINE_MASK        (0x3F << RC_CLK_CALIB_FTRIM_FINE_SHIFT)
#define RC_CLK_CALIB_FTRIM_FINE(n)          BITFIELD_VAL(RC_CLK_CALIB_FTRIM_FINE, n)
#define RC_CLK_CALIB_FTRIM_SHIFT            6
#define RC_CLK_CALIB_FTRIM_MASK             (0x1F << RC_CLK_CALIB_FTRIM_SHIFT)
#define RC_CLK_CALIB_FTRIM(n)               BITFIELD_VAL(RC_CLK_CALIB_FTRIM, n)
#define RC_CLK_CALIB_STATE_SHIFT            11
#define RC_CLK_CALIB_STATE_MASK             (0x3 << RC_CLK_CALIB_STATE_SHIFT)
#define RC_CLK_CALIB_STATE(n)               BITFIELD_VAL(RC_CLK_CALIB_STATE, n)
#define RC_CLK_CALIB_DONE_RAW_INTR          (1 << 13)
#define RC_CLK_CALIB_DONE_INTR              (1 << 14)
#define RC_CLK_CALIB_GOAL_CNT_16            (1 << 15)

// REG_AE
#define REG_RC_CLK_CALIB_THRE_DONE_SHIFT    0
#define REG_RC_CLK_CALIB_THRE_DONE_MASK     (0xFF << REG_RC_CLK_CALIB_THRE_DONE_SHIFT)
#define REG_RC_CLK_CALIB_THRE_DONE(n)       BITFIELD_VAL(REG_RC_CLK_CALIB_THRE_DONE, n)
#define REG_RC_CLK_CALIB_CLK_REF_DIV_SHIFT  8
#define REG_RC_CLK_CALIB_CLK_REF_DIV_MASK   (0xFF << REG_RC_CLK_CALIB_CLK_REF_DIV_SHIFT)
#define REG_RC_CLK_CALIB_CLK_REF_DIV(n)     BITFIELD_VAL(REG_RC_CLK_CALIB_CLK_REF_DIV, n)

// REG_B0
#define REG_RC_CLK_CALIB_RE_MODE            (1 << 0)
#define REG_RC_CLK_CALIB_32K_TIME_SHIFT     1
#define REG_RC_CLK_CALIB_32K_TIME_MASK      (0x7FFF << REG_RC_CLK_CALIB_32K_TIME_SHIFT)
#define REG_RC_CLK_CALIB_32K_TIME(n)        BITFIELD_VAL(REG_RC_CLK_CALIB_32K_TIME, n)

// REG_B1
#define PU_RC_CLK_32K_CALIB_STOP_CLR        (1 << 0)
#define RC_CLK_CALIB_FTRIM_BUF_SHIFT        1
#define RC_CLK_CALIB_FTRIM_BUF_MASK         (0x1F << RC_CLK_CALIB_FTRIM_BUF_SHIFT)
#define RC_CLK_CALIB_FTRIM_BUF(n)           BITFIELD_VAL(RC_CLK_CALIB_FTRIM_BUF, n)
#define RC_CLK_CALIB_FTRIM_FINE_BUF_SHIFT   6
#define RC_CLK_CALIB_FTRIM_FINE_BUF_MASK    (0x3F << RC_CLK_CALIB_FTRIM_FINE_BUF_SHIFT)
#define RC_CLK_CALIB_FTRIM_FINE_BUF(n)      BITFIELD_VAL(RC_CLK_CALIB_FTRIM_FINE_BUF, n)
#define RC_CLK_CALIB_32K_STATE_SHIFT        12
#define RC_CLK_CALIB_32K_STATE_MASK         (0x3 << RC_CLK_CALIB_32K_STATE_SHIFT)
#define RC_CLK_CALIB_32K_STATE(n)           BITFIELD_VAL(RC_CLK_CALIB_32K_STATE, n)

// REG_B2
#define REG_RC_32K_CALIB_CLK                (1 << 0)
#define RC_32K_CALIB_DR_CLK                 (1 << 1)
#define REG_32K_CALIB_BEGIN_DELAY_CLK_SHIFT 2
#define REG_32K_CALIB_BEGIN_DELAY_CLK_MASK  (0xF << REG_32K_CALIB_BEGIN_DELAY_CLK_SHIFT)
#define REG_32K_CALIB_BEGIN_DELAY_CLK(n)    BITFIELD_VAL(REG_32K_CALIB_BEGIN_DELAY_CLK, n)


// REG_101
#define REG_SAR_INIT_CALI_BIT_SHIFT         0
#define REG_SAR_INIT_CALI_BIT_MASK          (0x1F << REG_SAR_INIT_CALI_BIT_SHIFT)
#define REG_SAR_INIT_CALI_BIT(n)            BITFIELD_VAL(REG_SAR_INIT_CALI_BIT, n)
#define REG_SAR_CALI                        (1 << 5)
#define REG_SAR_CALI_CNT_SHIFT              6
#define REG_SAR_CALI_CNT_MASK               (0xF << REG_SAR_CALI_CNT_SHIFT)
#define REG_SAR_CALI_CNT(n)                 BITFIELD_VAL(REG_SAR_CALI_CNT, n)
#define REG_SAR_CALI_LSB_SCRN               (1 << 10)
#define REG_SAR_WEIGHT_DR                   (1 << 11)
#define REG_CODEC_SAR_VREF_PULLDOWN         (1 << 12)
#define REG_CODEC_SAR_DVDD_IBIT             (1 << 13)
#define REG_CODEC_SAR_VREF_LOWGAIN_SHIFT    14
#define REG_CODEC_SAR_VREF_LOWGAIN_MASK     (0x3 << REG_CODEC_SAR_VREF_LOWGAIN_SHIFT)
#define REG_CODEC_SAR_VREF_LOWGAIN(n)       BITFIELD_VAL(REG_CODEC_SAR_VREF_LOWGAIN, n)

// REG_102
#define CLK_SARADC_CODEC_INV                (1 << 0)
#define REG_CLK_SAR_MUX                     (1 << 1)
#define REG_SAR_OFFSET_DR                   (1 << 2)
#define REG_SAR_OFFSET_P_SHIFT              3
#define REG_SAR_OFFSET_P_MASK               (0x1F << REG_SAR_OFFSET_P_SHIFT)
#define REG_SAR_OFFSET_P(n)                 BITFIELD_VAL(REG_SAR_OFFSET_P, n)
#define REG_SAR_OFFSET_N_SHIFT              8
#define REG_SAR_OFFSET_N_MASK               (0x1F << REG_SAR_OFFSET_N_SHIFT)
#define REG_SAR_OFFSET_N(n)                 BITFIELD_VAL(REG_SAR_OFFSET_N, n)
#define REG_CODEC_SAR_DELAY_CMP             (1 << 13)
#define REG_CODEC_SAR_HIGH_DVDD_EN          (1 << 14)
#define REG_SAR_EN_SAR_DOUT                 (1 << 15)

// REG_103
#define REG_CODEC_SAR_PGA_EN_IN             (1 << 0)
#define REG_SAR_DIFF_EN_IN_DR               (1 << 1)
#define REG_SAR_DIFF_EN_IN_REG              (1 << 2)
#define REG_CODEC_SAR_CFB_SEL_SHIFT         3
#define REG_CODEC_SAR_CFB_SEL_MASK          (0xF << REG_CODEC_SAR_CFB_SEL_SHIFT)
#define REG_CODEC_SAR_CFB_SEL(n)            BITFIELD_VAL(REG_CODEC_SAR_CFB_SEL, n)
#define REG_SAR_ADC_OFFSET_DR               (1 << 8)
#define REG_CODEC_SAR_EN_PGA                (1 << 9)
#define REG_CODEC_SAR_PGA_BYPASS            (1 << 10)
#define REG_CODEC_SAR_PGA_CC_SEL            (1 << 11)
#define REG_CODEC_SAR_PGA_OFFSET_CAL_EN     (1 << 12)
#define REG_CODEC_SAR_PGA_RFB_HALF          (1 << 13)
#define REG_CODEC_SAR_PGA_RIN_HALF          (1 << 14)
#define REG_CODEC_SAR_PRE_CHARGE            (1 << 15)

// REG_104
#define REG_SAR_ADC_OFFSET_SHIFT            0
#define REG_SAR_ADC_OFFSET_MASK             (0xFFFF << REG_SAR_ADC_OFFSET_SHIFT)
#define REG_SAR_ADC_OFFSET(n)               BITFIELD_VAL(REG_SAR_ADC_OFFSET, n)

// REG_105
#define REG_CODEC_SAR_VCMBUF_I_SEL          (1 << 0)
#define REG_CODEC_SAR_PU_AVDD18             (1 << 1)
#define REG_CODEC_SAR_EN_VREF_LP            (1 << 2)
#define REG_CODEC_SAR_HIGH_PW_CMP_SHIFT     3
#define REG_CODEC_SAR_HIGH_PW_CMP_MASK      (0x3 << REG_CODEC_SAR_HIGH_PW_CMP_SHIFT)
#define REG_CODEC_SAR_HIGH_PW_CMP(n)        BITFIELD_VAL(REG_CODEC_SAR_HIGH_PW_CMP, n)
#define REG_CODEC_SAR_DELAY_BIT_SHIFT       5
#define REG_CODEC_SAR_DELAY_BIT_MASK        (0x7 << REG_CODEC_SAR_DELAY_BIT_SHIFT)
#define REG_CODEC_SAR_DELAY_BIT(n)          BITFIELD_VAL(REG_CODEC_SAR_DELAY_BIT, n)
#define REG_CODEC_SAR_PU_CHOP               (1 << 8)
#define REG_CODEC_SAR_PU_IN                 (1 << 9)
#define REG_CODEC_SAR_RESET_PGA             (1 << 10)
#define REG_CODEC_SAR_RFB_EN                (1 << 11)
#define REG_CODEC_SAR_GAIN_SHIFT            12
#define REG_CODEC_SAR_GAIN_MASK             (0x7 << REG_CODEC_SAR_GAIN_SHIFT)
#define REG_CODEC_SAR_GAIN(n)               BITFIELD_VAL(REG_CODEC_SAR_GAIN, n)

// REG_106
#define SAR_DOUT_SHIFT                      0
#define SAR_DOUT_MASK                       (0xFFFF << SAR_DOUT_SHIFT)
#define SAR_DOUT(n)                         BITFIELD_VAL(SAR_DOUT, n)

// REG_107
#define SAR_RAW_DATA_8_B_SHIFT              0
#define SAR_RAW_DATA_8_B_MASK               (0x1FF << SAR_RAW_DATA_8_B_SHIFT)
#define SAR_RAW_DATA_8_B(n)                 BITFIELD_VAL(SAR_RAW_DATA_8_B, n)

// REG_108
#define SAR_RAW_DATA_B_SHIFT                0
#define SAR_RAW_DATA_B_MASK                 (0x1FF << SAR_RAW_DATA_B_SHIFT)
#define SAR_RAW_DATA_B(n)                   BITFIELD_VAL(SAR_RAW_DATA_B, n)
#define CODEC_SARADC_CH_0                   (1 << 9)

// REG_109
#define CODEC_SARADC_CH_16_1_SHIFT          0
#define CODEC_SARADC_CH_16_1_MASK           (0xFFFF << CODEC_SARADC_CH_16_1_SHIFT)
#define CODEC_SARADC_CH_16_1(n)             BITFIELD_VAL(CODEC_SARADC_CH_16_1, n)

// REG_10A
#define REG_SAR_OFFSET_CALI                 (1 << 0)
#define REG_SAR_OFFSET_CALI_CNT_SHIFT       1
#define REG_SAR_OFFSET_CALI_CNT_MASK        (0x7 << REG_SAR_OFFSET_CALI_CNT_SHIFT)
#define REG_SAR_OFFSET_CALI_CNT(n)          BITFIELD_VAL(REG_SAR_OFFSET_CALI_CNT, n)
#define REG_SAR_CLK_OUT_SEL                 (1 << 4)
#define REG_SAR_CLK_INT_DIV_SHIFT           5
#define REG_SAR_CLK_INT_DIV_MASK            (0x7F << REG_SAR_CLK_INT_DIV_SHIFT)
#define REG_SAR_CLK_INT_DIV(n)              BITFIELD_VAL(REG_SAR_CLK_INT_DIV, n)
#define SAR_VOUT_CALIB_INV                  (1 << 12)
#define SAR_CONV_DONE_INV                   (1 << 13)
#define REG_SAR_RESULT_SEL                  (1 << 14)
#define REG_SAR_ADC_ON                      (1 << 15)

// REG_10B
#define REG_CODEC_SAR_RES_BIT_SHIFT         0
#define REG_CODEC_SAR_RES_BIT_MASK          (0x3 << REG_CODEC_SAR_RES_BIT_SHIFT)
#define REG_CODEC_SAR_RES_BIT(n)            BITFIELD_VAL(REG_CODEC_SAR_RES_BIT, n)
#define REG_CODEC_SAR_IBIT_IN1_SHIFT        2
#define REG_CODEC_SAR_IBIT_IN1_MASK         (0x7 << REG_CODEC_SAR_IBIT_IN1_SHIFT)
#define REG_CODEC_SAR_IBIT_IN1(n)           BITFIELD_VAL(REG_CODEC_SAR_IBIT_IN1, n)
#define REG_CODEC_SAR_IBIT_IN2_SHIFT        5
#define REG_CODEC_SAR_IBIT_IN2_MASK         (0x7 << REG_CODEC_SAR_IBIT_IN2_SHIFT)
#define REG_CODEC_SAR_IBIT_IN2(n)           BITFIELD_VAL(REG_CODEC_SAR_IBIT_IN2, n)
#define REG_CODEC_SAR_CLK_TRIM_SHIFT        8
#define REG_CODEC_SAR_CLK_TRIM_MASK         (0x3 << REG_CODEC_SAR_CLK_TRIM_SHIFT)
#define REG_CODEC_SAR_CLK_TRIM(n)           BITFIELD_VAL(REG_CODEC_SAR_CLK_TRIM, n)
#define REG_CODEC_SAR_CLK_MODE              (1 << 10)
#define REG_CODEC_SAR_EN_PREAMP             (1 << 13)
#define REG_SAR_CLK_EN                      (1 << 14)

// REG_10C
#define REG_SAR_PU_PIN_BIAS                 (1 << 0)
#define REG_SAR_PU_NIN_BIAS                 (1 << 1)
#define REG_CODEC_SAR_SE_MODE               (1 << 2)
#define REG_CODEC_SAR_VREG_IBIT_SHIFT       5
#define REG_CODEC_SAR_VREG_IBIT_MASK        (0x3 << REG_CODEC_SAR_VREG_IBIT_SHIFT)
#define REG_CODEC_SAR_VREG_IBIT(n)          BITFIELD_VAL(REG_CODEC_SAR_VREG_IBIT, n)
#define REG_CODEC_SAR_VREG_OUTCAP_MODE_SHIFT 7
#define REG_CODEC_SAR_VREG_OUTCAP_MODE_MASK (0x3 << REG_CODEC_SAR_VREG_OUTCAP_MODE_SHIFT)
#define REG_CODEC_SAR_VREG_OUTCAP_MODE(n)   BITFIELD_VAL(REG_CODEC_SAR_VREG_OUTCAP_MODE, n)
#define REG_CODEC_SAR_VREG_SEL_SHIFT        9
#define REG_CODEC_SAR_VREG_SEL_MASK         (0xF << REG_CODEC_SAR_VREG_SEL_SHIFT)
#define REG_CODEC_SAR_VREG_SEL(n)           BITFIELD_VAL(REG_CODEC_SAR_VREG_SEL, n)
#define REG_SAR_PU_PIN_BIAS_DR              (1 << 13)
#define REG_SAR_PU_NIN_BIAS_DR              (1 << 14)

// REG_10D
#define REG_SAR_CLK_OUT_DIV_SHIFT           0
#define REG_SAR_CLK_OUT_DIV_MASK            (0x1FFF << REG_SAR_CLK_OUT_DIV_SHIFT)
#define REG_SAR_CLK_OUT_DIV(n)              BITFIELD_VAL(REG_SAR_CLK_OUT_DIV, n)
#define REG_SAR_CLK_SEL_SHIFT               13
#define REG_SAR_CLK_SEL_MASK                (0x3 << REG_SAR_CLK_SEL_SHIFT)
#define REG_SAR_CLK_SEL(n)                  BITFIELD_VAL(REG_SAR_CLK_SEL, n)

// REG_10E
#define REG_SAR_PU_VREF_DR                  (1 << 0)
#define REG_SAR_PU_VREF_REG                 (1 << 1)
#define REG_SAR_PU_VREF_IN                  (1 << 2)
#define REG_SAR_PU_DR                       (1 << 3)
#define REG_SAR_PU_REG                      (1 << 4)
#define REG_SAR_PU_PRECHARGE_DR             (1 << 5)
#define REG_SAR_PU_PRECHARGE_REG            (1 << 6)
#define REG_SAR_PU_RST_DR                   (1 << 7)
#define REG_SAR_PU_RST_REG                  (1 << 8)
#define REG_DET_EN                          (1 << 10)

// REG_10F
#define REG_SAR_PU_START_DLY_CNT_SHIFT      0
#define REG_SAR_PU_START_DLY_CNT_MASK       (0x7F << REG_SAR_PU_START_DLY_CNT_SHIFT)
#define REG_SAR_PU_START_DLY_CNT(n)         BITFIELD_VAL(REG_SAR_PU_START_DLY_CNT, n)
#define REG_SAR_PU_PRECHARGE_START_DLY_CNT_SHIFT 7
#define REG_SAR_PU_PRECHARGE_START_DLY_CNT_MASK (0x7F << REG_SAR_PU_PRECHARGE_START_DLY_CNT_SHIFT)
#define REG_SAR_PU_PRECHARGE_START_DLY_CNT(n) BITFIELD_VAL(REG_SAR_PU_PRECHARGE_START_DLY_CNT, n)

// REG_110
#define REG_SAR_PU_RST_START_DLY_CNT_SHIFT  0
#define REG_SAR_PU_RST_START_DLY_CNT_MASK   (0x7F << REG_SAR_PU_RST_START_DLY_CNT_SHIFT)
#define REG_SAR_PU_RST_START_DLY_CNT(n)     BITFIELD_VAL(REG_SAR_PU_RST_START_DLY_CNT, n)
#define REG_SAR_PU_RST_LAST_CNT_SHIFT       7
#define REG_SAR_PU_RST_LAST_CNT_MASK        (0x7F << REG_SAR_PU_RST_LAST_CNT_SHIFT)
#define REG_SAR_PU_RST_LAST_CNT(n)          BITFIELD_VAL(REG_SAR_PU_RST_LAST_CNT, n)

// REG_111
#define REG_SAR_PU_PRECHARGE_LAST_CNT_SHIFT 0
#define REG_SAR_PU_PRECHARGE_LAST_CNT_MASK  (0x1FF << REG_SAR_PU_PRECHARGE_LAST_CNT_SHIFT)
#define REG_SAR_PU_PRECHARGE_LAST_CNT(n)    BITFIELD_VAL(REG_SAR_PU_PRECHARGE_LAST_CNT, n)

// REG_112
#define SAR_BIT00_WEIGHT_SHIFT              0
#define SAR_BIT00_WEIGHT_MASK               (0x3FFF << SAR_BIT00_WEIGHT_SHIFT)
#define SAR_BIT00_WEIGHT(n)                 BITFIELD_VAL(SAR_BIT00_WEIGHT, n)

// REG_113
#define SAR_BIT01_WEIGHT_SHIFT              0
#define SAR_BIT01_WEIGHT_MASK               (0x3FFF << SAR_BIT01_WEIGHT_SHIFT)
#define SAR_BIT01_WEIGHT(n)                 BITFIELD_VAL(SAR_BIT01_WEIGHT, n)

// REG_114
#define SAR_BIT02_WEIGHT_SHIFT              0
#define SAR_BIT02_WEIGHT_MASK               (0x3FFF << SAR_BIT02_WEIGHT_SHIFT)
#define SAR_BIT02_WEIGHT(n)                 BITFIELD_VAL(SAR_BIT02_WEIGHT, n)

// REG_115
#define SAR_BIT03_WEIGHT_SHIFT              0
#define SAR_BIT03_WEIGHT_MASK               (0x3FFF << SAR_BIT03_WEIGHT_SHIFT)
#define SAR_BIT03_WEIGHT(n)                 BITFIELD_VAL(SAR_BIT03_WEIGHT, n)

// REG_116
#define SAR_BIT04_WEIGHT_SHIFT              0
#define SAR_BIT04_WEIGHT_MASK               (0x3FFF << SAR_BIT04_WEIGHT_SHIFT)
#define SAR_BIT04_WEIGHT(n)                 BITFIELD_VAL(SAR_BIT04_WEIGHT, n)

// REG_117
#define SAR_P_BIT05_WEIGHT_SHIFT            0
#define SAR_P_BIT05_WEIGHT_MASK             (0x3FFF << SAR_P_BIT05_WEIGHT_SHIFT)
#define SAR_P_BIT05_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT05_WEIGHT, n)

// REG_118
#define SAR_P_BIT06_WEIGHT_SHIFT            0
#define SAR_P_BIT06_WEIGHT_MASK             (0x3FFF << SAR_P_BIT06_WEIGHT_SHIFT)
#define SAR_P_BIT06_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT06_WEIGHT, n)

// REG_119
#define SAR_P_BIT07_WEIGHT_SHIFT            0
#define SAR_P_BIT07_WEIGHT_MASK             (0x3FFF << SAR_P_BIT07_WEIGHT_SHIFT)
#define SAR_P_BIT07_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT07_WEIGHT, n)

// REG_11A
#define SAR_P_BIT08_WEIGHT_SHIFT            0
#define SAR_P_BIT08_WEIGHT_MASK             (0x3FFF << SAR_P_BIT08_WEIGHT_SHIFT)
#define SAR_P_BIT08_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT08_WEIGHT, n)

// REG_11B
#define SAR_P_BIT09_WEIGHT_SHIFT            0
#define SAR_P_BIT09_WEIGHT_MASK             (0x3FFF << SAR_P_BIT09_WEIGHT_SHIFT)
#define SAR_P_BIT09_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT09_WEIGHT, n)

// REG_11C
#define SAR_P_BIT10_WEIGHT_SHIFT            0
#define SAR_P_BIT10_WEIGHT_MASK             (0x3FFF << SAR_P_BIT10_WEIGHT_SHIFT)
#define SAR_P_BIT10_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT10_WEIGHT, n)

// REG_11D
#define SAR_P_BIT11_WEIGHT_SHIFT            0
#define SAR_P_BIT11_WEIGHT_MASK             (0x3FFF << SAR_P_BIT11_WEIGHT_SHIFT)
#define SAR_P_BIT11_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT11_WEIGHT, n)

// REG_11E
#define SAR_P_BIT12_WEIGHT_SHIFT            0
#define SAR_P_BIT12_WEIGHT_MASK             (0x3FFF << SAR_P_BIT12_WEIGHT_SHIFT)
#define SAR_P_BIT12_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT12_WEIGHT, n)

// REG_11F
#define SAR_P_BIT13_WEIGHT_SHIFT            0
#define SAR_P_BIT13_WEIGHT_MASK             (0x3FFF << SAR_P_BIT13_WEIGHT_SHIFT)
#define SAR_P_BIT13_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT13_WEIGHT, n)

// REG_120
#define SAR_P_BIT14_WEIGHT_SHIFT            0
#define SAR_P_BIT14_WEIGHT_MASK             (0x3FFF << SAR_P_BIT14_WEIGHT_SHIFT)
#define SAR_P_BIT14_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT14_WEIGHT, n)

// REG_121
#define SAR_P_BIT15_WEIGHT_SHIFT            0
#define SAR_P_BIT15_WEIGHT_MASK             (0x3FFF << SAR_P_BIT15_WEIGHT_SHIFT)
#define SAR_P_BIT15_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT15_WEIGHT, n)

// REG_122
#define SAR_P_BIT16_WEIGHT_SHIFT            0
#define SAR_P_BIT16_WEIGHT_MASK             (0x3FFF << SAR_P_BIT16_WEIGHT_SHIFT)
#define SAR_P_BIT16_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT16_WEIGHT, n)

// REG_123
#define SAR_P_BIT17_WEIGHT_SHIFT            0
#define SAR_P_BIT17_WEIGHT_MASK             (0x3FFF << SAR_P_BIT17_WEIGHT_SHIFT)
#define SAR_P_BIT17_WEIGHT(n)               BITFIELD_VAL(SAR_P_BIT17_WEIGHT, n)

// REG_124
#define SAR_N_BIT05_WEIGHT_SHIFT            0
#define SAR_N_BIT05_WEIGHT_MASK             (0x3FFF << SAR_N_BIT05_WEIGHT_SHIFT)
#define SAR_N_BIT05_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT05_WEIGHT, n)

// REG_125
#define SAR_N_BIT06_WEIGHT_SHIFT            0
#define SAR_N_BIT06_WEIGHT_MASK             (0x3FFF << SAR_N_BIT06_WEIGHT_SHIFT)
#define SAR_N_BIT06_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT06_WEIGHT, n)

// REG_126
#define SAR_N_BIT07_WEIGHT_SHIFT            0
#define SAR_N_BIT07_WEIGHT_MASK             (0x3FFF << SAR_N_BIT07_WEIGHT_SHIFT)
#define SAR_N_BIT07_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT07_WEIGHT, n)

// REG_127
#define SAR_N_BIT08_WEIGHT_SHIFT            0
#define SAR_N_BIT08_WEIGHT_MASK             (0x3FFF << SAR_N_BIT08_WEIGHT_SHIFT)
#define SAR_N_BIT08_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT08_WEIGHT, n)

// REG_128
#define SAR_N_BIT09_WEIGHT_SHIFT            0
#define SAR_N_BIT09_WEIGHT_MASK             (0x3FFF << SAR_N_BIT09_WEIGHT_SHIFT)
#define SAR_N_BIT09_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT09_WEIGHT, n)

// REG_129
#define SAR_N_BIT10_WEIGHT_SHIFT            0
#define SAR_N_BIT10_WEIGHT_MASK             (0x3FFF << SAR_N_BIT10_WEIGHT_SHIFT)
#define SAR_N_BIT10_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT10_WEIGHT, n)

// REG_12A
#define SAR_N_BIT11_WEIGHT_SHIFT            0
#define SAR_N_BIT11_WEIGHT_MASK             (0x3FFF << SAR_N_BIT11_WEIGHT_SHIFT)
#define SAR_N_BIT11_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT11_WEIGHT, n)

// REG_12B
#define SAR_N_BIT12_WEIGHT_SHIFT            0
#define SAR_N_BIT12_WEIGHT_MASK             (0x3FFF << SAR_N_BIT12_WEIGHT_SHIFT)
#define SAR_N_BIT12_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT12_WEIGHT, n)

// REG_12C
#define SAR_N_BIT13_WEIGHT_SHIFT            0
#define SAR_N_BIT13_WEIGHT_MASK             (0x3FFF << SAR_N_BIT13_WEIGHT_SHIFT)
#define SAR_N_BIT13_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT13_WEIGHT, n)

// REG_12D
#define SAR_N_BIT14_WEIGHT_SHIFT            0
#define SAR_N_BIT14_WEIGHT_MASK             (0x3FFF << SAR_N_BIT14_WEIGHT_SHIFT)
#define SAR_N_BIT14_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT14_WEIGHT, n)

// REG_12E
#define SAR_N_BIT15_WEIGHT_SHIFT            0
#define SAR_N_BIT15_WEIGHT_MASK             (0x3FFF << SAR_N_BIT15_WEIGHT_SHIFT)
#define SAR_N_BIT15_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT15_WEIGHT, n)

// REG_12F
#define SAR_N_BIT16_WEIGHT_SHIFT            0
#define SAR_N_BIT16_WEIGHT_MASK             (0x3FFF << SAR_N_BIT16_WEIGHT_SHIFT)
#define SAR_N_BIT16_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT16_WEIGHT, n)

// REG_130
#define SAR_N_BIT17_WEIGHT_SHIFT            0
#define SAR_N_BIT17_WEIGHT_MASK             (0x3FFF << SAR_N_BIT17_WEIGHT_SHIFT)
#define SAR_N_BIT17_WEIGHT(n)               BITFIELD_VAL(SAR_N_BIT17_WEIGHT, n)

// REG_131
#define REG_SAR_TRIG_ENABLE                 (1 << 0)
#define REG_SAR_TRIG_POL_RATE               (1 << 1)
#define REG_SAR_TRIG_DET_CLR                (1 << 2)
#define REG_SAR_TRIG_HPF_BYPASS             (1 << 3)
#define REG_SAR_TRIG_LPF_BYPASS             (1 << 4)
#define REG_SAR_TRIG_U_DC_SHIFT             5
#define REG_SAR_TRIG_U_DC_MASK              (0xF << REG_SAR_TRIG_U_DC_SHIFT)
#define REG_SAR_TRIG_U_DC(n)                BITFIELD_VAL(REG_SAR_TRIG_U_DC, n)

// REG_132
#define REG_SAR_TRIG_COEF_A1_SHIFT          0
#define REG_SAR_TRIG_COEF_A1_MASK           (0x7F << REG_SAR_TRIG_COEF_A1_SHIFT)
#define REG_SAR_TRIG_COEF_A1(n)             BITFIELD_VAL(REG_SAR_TRIG_COEF_A1, n)
#define REG_SAR_TRIG_COEF_B0_SHIFT          7
#define REG_SAR_TRIG_COEF_B0_MASK           (0x7F << REG_SAR_TRIG_COEF_B0_SHIFT)
#define REG_SAR_TRIG_COEF_B0(n)             BITFIELD_VAL(REG_SAR_TRIG_COEF_B0, n)

// REG_133
#define REG_SAR_TRIG_COEF_B1_SHIFT          0
#define REG_SAR_TRIG_COEF_B1_MASK           (0x7F << REG_SAR_TRIG_COEF_B1_SHIFT)
#define REG_SAR_TRIG_COEF_B1(n)             BITFIELD_VAL(REG_SAR_TRIG_COEF_B1, n)

// REG_134
#define REG_SAR_TRIG_TH_SHIFT               0
#define REG_SAR_TRIG_TH_MASK                (0xFFFF << REG_SAR_TRIG_TH_SHIFT)
#define REG_SAR_TRIG_TH(n)                  BITFIELD_VAL(REG_SAR_TRIG_TH, n)

// REG_135
#define CFG_SAR_DET_DELAY_SHIFT             0
#define CFG_SAR_DET_DELAY_MASK              (0xFFF << CFG_SAR_DET_DELAY_SHIFT)
#define CFG_SAR_DET_DELAY(n)                BITFIELD_VAL(CFG_SAR_DET_DELAY, n)
#define SAR_SWITCH2OSC_EN                   (1 << 12)
#define REG_SAR_TO_SIGN                     (1 << 14)
#define REG_SAR_CLOSE_ON_DET                (1 << 15)

// REG_136
#define REG_SAR_DET_DLY_TIMER_SHIFT         0
#define REG_SAR_DET_DLY_TIMER_MASK          (0xFF << REG_SAR_DET_DLY_TIMER_SHIFT)
#define REG_SAR_DET_DLY_TIMER(n)            BITFIELD_VAL(REG_SAR_DET_DLY_TIMER, n)

// REG_137
#define REG_SAR_ADC_OFFSET_IN_SHIFT         0
#define REG_SAR_ADC_OFFSET_IN_MASK          (0xFFFF << REG_SAR_ADC_OFFSET_IN_SHIFT)
#define REG_SAR_ADC_OFFSET_IN(n)            BITFIELD_VAL(REG_SAR_ADC_OFFSET_IN, n)

// REG_138
#define REG_SAR_OFFSET_P_OUT_SHIFT          0
#define REG_SAR_OFFSET_P_OUT_MASK           (0x1F << REG_SAR_OFFSET_P_OUT_SHIFT)
#define REG_SAR_OFFSET_P_OUT(n)             BITFIELD_VAL(REG_SAR_OFFSET_P_OUT, n)
#define REG_SAR_OFFSET_N_OUT_SHIFT          5
#define REG_SAR_OFFSET_N_OUT_MASK           (0x1F << REG_SAR_OFFSET_N_OUT_SHIFT)
#define REG_SAR_OFFSET_N_OUT(n)             BITFIELD_VAL(REG_SAR_OFFSET_N_OUT, n)

// REG_139
#define SAR_P_BIT05_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT05_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT05_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT05_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT05_WEIGHT_OUT, n)

// REG_13A
#define SAR_P_BIT06_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT06_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT06_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT06_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT06_WEIGHT_OUT, n)

// REG_13B
#define SAR_P_BIT07_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT07_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT07_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT07_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT07_WEIGHT_OUT, n)

// REG_13C
#define SAR_P_BIT08_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT08_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT08_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT08_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT08_WEIGHT_OUT, n)

// REG_13D
#define SAR_P_BIT09_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT09_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT09_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT09_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT09_WEIGHT_OUT, n)

// REG_13E
#define SAR_P_BIT10_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT10_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT10_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT10_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT10_WEIGHT_OUT, n)

// REG_13F
#define SAR_P_BIT11_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT11_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT11_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT11_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT11_WEIGHT_OUT, n)

// REG_140
#define SAR_P_BIT12_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT12_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT12_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT12_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT12_WEIGHT_OUT, n)

// REG_141
#define SAR_P_BIT13_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT13_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT13_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT13_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT13_WEIGHT_OUT, n)

// REG_142
#define SAR_P_BIT14_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT14_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT14_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT14_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT14_WEIGHT_OUT, n)

// REG_143
#define SAR_P_BIT15_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT15_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT15_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT15_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT15_WEIGHT_OUT, n)

// REG_144
#define SAR_P_BIT16_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT16_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT16_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT16_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT16_WEIGHT_OUT, n)

// REG_145
#define SAR_P_BIT17_WEIGHT_OUT_SHIFT        0
#define SAR_P_BIT17_WEIGHT_OUT_MASK         (0x3FFF << SAR_P_BIT17_WEIGHT_OUT_SHIFT)
#define SAR_P_BIT17_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_P_BIT17_WEIGHT_OUT, n)

// REG_146
#define SAR_N_BIT05_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT05_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT05_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT05_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT05_WEIGHT_OUT, n)

// REG_147
#define SAR_N_BIT06_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT06_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT06_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT06_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT06_WEIGHT_OUT, n)

// REG_148
#define SAR_N_BIT07_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT07_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT07_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT07_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT07_WEIGHT_OUT, n)

// REG_149
#define SAR_N_BIT08_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT08_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT08_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT08_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT08_WEIGHT_OUT, n)

// REG_14A
#define SAR_N_BIT09_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT09_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT09_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT09_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT09_WEIGHT_OUT, n)

// REG_14B
#define SAR_N_BIT10_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT10_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT10_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT10_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT10_WEIGHT_OUT, n)

// REG_14C
#define SAR_N_BIT11_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT11_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT11_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT11_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT11_WEIGHT_OUT, n)

// REG_14D
#define SAR_N_BIT12_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT12_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT12_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT12_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT12_WEIGHT_OUT, n)

// REG_14E
#define SAR_N_BIT13_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT13_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT13_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT13_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT13_WEIGHT_OUT, n)

// REG_14F
#define SAR_N_BIT14_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT14_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT14_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT14_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT14_WEIGHT_OUT, n)

// REG_150
#define SAR_N_BIT15_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT15_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT15_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT15_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT15_WEIGHT_OUT, n)

// REG_151
#define SAR_N_BIT16_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT16_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT16_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT16_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT16_WEIGHT_OUT, n)

// REG_152
#define SAR_N_BIT17_WEIGHT_OUT_SHIFT        0
#define SAR_N_BIT17_WEIGHT_OUT_MASK         (0x3FFF << SAR_N_BIT17_WEIGHT_OUT_SHIFT)
#define SAR_N_BIT17_WEIGHT_OUT(n)           BITFIELD_VAL(SAR_N_BIT17_WEIGHT_OUT, n)

// REG_153
#define REG_ADCE_OPEN                       (1 << 0)
#define REG_SAR_LP_MODE_DR                  (1 << 1)
#define REG_SAR_LP_MODE                     (1 << 2)
#define REG_R_DET_ACTIVE                    (1 << 3)
#define REG_R_DET_SAR_PU_CH0                (1 << 4)
#define REG_R_DET_SAR_PU_CH1                (1 << 5)

// REG_154
#define REG_SARADC_IN_SIGNED                (1 << 0)
#define REG_SARADC_DOWN_SEL_SHIFT           1
#define REG_SARADC_DOWN_SEL_MASK            (0x3 << REG_SARADC_DOWN_SEL_SHIFT)
#define REG_SARADC_DOWN_SEL(n)              BITFIELD_VAL(REG_SARADC_DOWN_SEL, n)
#define REG_SARADC_INN_IIR_CNT_SHIFT        3
#define REG_SARADC_INN_IIR_CNT_MASK         (0x3 << REG_SARADC_INN_IIR_CNT_SHIFT)
#define REG_SARADC_INN_IIR_CNT(n)           BITFIELD_VAL(REG_SARADC_INN_IIR_CNT, n)
#define REG_SARADC_DCF_BYPASS               (1 << 5)
#define REG_SARADC_EN                       (1 << 6)

// REG_155
#define REG_SARADC_COEF_UDC_15_0_SHIFT      0
#define REG_SARADC_COEF_UDC_15_0_MASK       (0xFFFF << REG_SARADC_COEF_UDC_15_0_SHIFT)
#define REG_SARADC_COEF_UDC_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF_UDC_15_0, n)

// REG_156
#define REG_SARADC_COEF_UDC_19_16_SHIFT     0
#define REG_SARADC_COEF_UDC_19_16_MASK      (0xF << REG_SARADC_COEF_UDC_19_16_SHIFT)
#define REG_SARADC_COEF_UDC_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF_UDC_19_16, n)

// REG_157
#define REG_SARADC_COEF0_A1_15_0_SHIFT      0
#define REG_SARADC_COEF0_A1_15_0_MASK       (0xFFFF << REG_SARADC_COEF0_A1_15_0_SHIFT)
#define REG_SARADC_COEF0_A1_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF0_A1_15_0, n)

// REG_158
#define REG_SARADC_COEF0_A1_19_16_SHIFT     0
#define REG_SARADC_COEF0_A1_19_16_MASK      (0xF << REG_SARADC_COEF0_A1_19_16_SHIFT)
#define REG_SARADC_COEF0_A1_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF0_A1_19_16, n)

// REG_159
#define REG_SARADC_COEF0_A2_15_0_SHIFT      0
#define REG_SARADC_COEF0_A2_15_0_MASK       (0xFFFF << REG_SARADC_COEF0_A2_15_0_SHIFT)
#define REG_SARADC_COEF0_A2_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF0_A2_15_0, n)

// REG_15A
#define REG_SARADC_COEF0_A2_19_16_SHIFT     0
#define REG_SARADC_COEF0_A2_19_16_MASK      (0xF << REG_SARADC_COEF0_A2_19_16_SHIFT)
#define REG_SARADC_COEF0_A2_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF0_A2_19_16, n)

// REG_15B
#define REG_SARADC_COEF0_B0_15_0_SHIFT      0
#define REG_SARADC_COEF0_B0_15_0_MASK       (0xFFFF << REG_SARADC_COEF0_B0_15_0_SHIFT)
#define REG_SARADC_COEF0_B0_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF0_B0_15_0, n)

// REG_15C
#define REG_SARADC_COEF0_B0_19_16_SHIFT     0
#define REG_SARADC_COEF0_B0_19_16_MASK      (0xF << REG_SARADC_COEF0_B0_19_16_SHIFT)
#define REG_SARADC_COEF0_B0_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF0_B0_19_16, n)

// REG_15D
#define REG_SARADC_COEF0_B1_15_0_SHIFT      0
#define REG_SARADC_COEF0_B1_15_0_MASK       (0xFFFF << REG_SARADC_COEF0_B1_15_0_SHIFT)
#define REG_SARADC_COEF0_B1_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF0_B1_15_0, n)

// REG_15E
#define REG_SARADC_COEF0_B1_19_16_SHIFT     0
#define REG_SARADC_COEF0_B1_19_16_MASK      (0xF << REG_SARADC_COEF0_B1_19_16_SHIFT)
#define REG_SARADC_COEF0_B1_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF0_B1_19_16, n)

// REG_160
#define REG_SARADC_COEF0_B2_15_0_SHIFT      0
#define REG_SARADC_COEF0_B2_15_0_MASK       (0xFFFF << REG_SARADC_COEF0_B2_15_0_SHIFT)
#define REG_SARADC_COEF0_B2_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF0_B2_15_0, n)

// REG_161
#define REG_SARADC_COEF0_B2_19_16_SHIFT     0
#define REG_SARADC_COEF0_B2_19_16_MASK      (0xF << REG_SARADC_COEF0_B2_19_16_SHIFT)
#define REG_SARADC_COEF0_B2_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF0_B2_19_16, n)

// REG_162
#define REG_SARADC_COEF1_A1_15_0_SHIFT      0
#define REG_SARADC_COEF1_A1_15_0_MASK       (0xFFFF << REG_SARADC_COEF1_A1_15_0_SHIFT)
#define REG_SARADC_COEF1_A1_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF1_A1_15_0, n)

// REG_163
#define REG_SARADC_COEF1_A1_19_16_SHIFT     0
#define REG_SARADC_COEF1_A1_19_16_MASK      (0xF << REG_SARADC_COEF1_A1_19_16_SHIFT)
#define REG_SARADC_COEF1_A1_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF1_A1_19_16, n)

// REG_164
#define REG_SARADC_COEF1_A2_15_0_SHIFT      0
#define REG_SARADC_COEF1_A2_15_0_MASK       (0xFFFF << REG_SARADC_COEF1_A2_15_0_SHIFT)
#define REG_SARADC_COEF1_A2_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF1_A2_15_0, n)

// REG_165
#define REG_SARADC_COEF1_A2_19_16_SHIFT     0
#define REG_SARADC_COEF1_A2_19_16_MASK      (0xF << REG_SARADC_COEF1_A2_19_16_SHIFT)
#define REG_SARADC_COEF1_A2_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF1_A2_19_16, n)

// REG_166
#define REG_SARADC_COEF1_B0_15_0_SHIFT      0
#define REG_SARADC_COEF1_B0_15_0_MASK       (0xFFFF << REG_SARADC_COEF1_B0_15_0_SHIFT)
#define REG_SARADC_COEF1_B0_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF1_B0_15_0, n)

// REG_167
#define REG_SARADC_COEF1_B0_19_16_SHIFT     0
#define REG_SARADC_COEF1_B0_19_16_MASK      (0xF << REG_SARADC_COEF1_B0_19_16_SHIFT)
#define REG_SARADC_COEF1_B0_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF1_B0_19_16, n)

// REG_168
#define REG_SARADC_COEF1_B1_15_0_SHIFT      0
#define REG_SARADC_COEF1_B1_15_0_MASK       (0xFFFF << REG_SARADC_COEF1_B1_15_0_SHIFT)
#define REG_SARADC_COEF1_B1_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF1_B1_15_0, n)

// REG_169
#define REG_SARADC_COEF1_B1_19_16_SHIFT     0
#define REG_SARADC_COEF1_B1_19_16_MASK      (0xF << REG_SARADC_COEF1_B1_19_16_SHIFT)
#define REG_SARADC_COEF1_B1_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF1_B1_19_16, n)

// REG_16A
#define REG_SARADC_COEF1_B2_15_0_SHIFT      0
#define REG_SARADC_COEF1_B2_15_0_MASK       (0xFFFF << REG_SARADC_COEF1_B2_15_0_SHIFT)
#define REG_SARADC_COEF1_B2_15_0(n)         BITFIELD_VAL(REG_SARADC_COEF1_B2_15_0, n)

// REG_16B
#define REG_SARADC_COEF1_B2_19_16_SHIFT     0
#define REG_SARADC_COEF1_B2_19_16_MASK      (0xF << REG_SARADC_COEF1_B2_19_16_SHIFT)
#define REG_SARADC_COEF1_B2_19_16(n)        BITFIELD_VAL(REG_SARADC_COEF1_B2_19_16, n)

// REG_16C
#define REG_SARADC_GAIN_15_0_SHIFT          0
#define REG_SARADC_GAIN_15_0_MASK           (0xFFFF << REG_SARADC_GAIN_15_0_SHIFT)
#define REG_SARADC_GAIN_15_0(n)             BITFIELD_VAL(REG_SARADC_GAIN_15_0, n)

// REG_16D
#define REG_SARADC_GAIN_19_16_SHIFT         0
#define REG_SARADC_GAIN_19_16_MASK          (0xF << REG_SARADC_GAIN_19_16_SHIFT)
#define REG_SARADC_GAIN_19_16(n)            BITFIELD_VAL(REG_SARADC_GAIN_19_16, n)
#define REG_SARADC_GAIN_SEL                 (1 << 4)
#define REG_SARADC_GAIN_UPDATE              (1 << 5)

// REG_16E
#define REG_SARADC_DC_DIN_SHIFT             0
#define REG_SARADC_DC_DIN_MASK              (0xFFFF << REG_SARADC_DC_DIN_SHIFT)
#define REG_SARADC_DC_DIN(n)                BITFIELD_VAL(REG_SARADC_DC_DIN, n)

// REG_16F
#define REG_SARADC_DC_UPDATE                (1 << 0)
#define REG_CHAN0_SAMPLE_P                  (1 << 1)
#define REG_CHAN1_SAMPLE_P                  (1 << 2)

#define SAR_TRIG_DOUT_ABS_SHIFT             0
#define SAR_TRIG_DOUT_ABS_MASK              (0xFFFF << SAR_TRIG_DOUT_ABS_SHIFT)
#define SAR_TRIG_DOUT_ABS(n)                BITFIELD_VAL(SAR_TRIG_DOUT_ABS, n)

// REG_172
#define SAR_LP_MODE                         (1 << 1)

#endif

