/***************************************************************************
 *
 * Copyright 2015-2024 BES.
 * All rights reserved. All unpublished rights reserved.
 *
 * No part of this work may be used or reproduced in any form or by any
 * means, or stored in a database or retrieval system, without prior written
 * permission of BES.
 *
 * Use of this work is governed by a license granted by BES.
 * This work contains confidential and proprietary information of
 * BES. which is protected by copyright, trade secret,
 * trademark and other intellectual property rights.
 *
 * @brief xxx.
 *
 ****************************************************************************/
#ifndef __BT_STACK_EVENT_H__
#define __BT_STACK_EVENT_H__

#ifdef __cplusplus
extern "C" {
#endif

/****************************** header include ********************************/
#include <stdint.h>

/***************************** external declaration *****************************/

/***************************** macro defination *******************************/

/***************************** type defination ********************************/
typedef enum {
    BT_GROUP_INDEX_LINK = 0,    // 0x1000
    BT_GROUP_INDEX_HFP_HF,      // 0x1100
    BT_GROUP_INDEX_HFP_AG,      // 0x1200
    BT_GROUP_INDEX_A2DP_SNK,    // 0x1300
    BT_GROUP_INDEX_A2DP_SRC,    // 0x1400
    BT_GROUP_INDEX_AVRCP,       // 0x1500
    BT_GROUP_INDEX_HID,         // 0x1600
    BT_GROUP_INDEX_MAP,         // 0x1700
    BT_GROUP_INDEX_PBAP,        // 0x1800
    BT_GROUP_INDEX_DIP,         // 0x1900
    BT_GROUP_INDEX_PAN,         // 0x1A00
    BT_GROUP_INDEX_OPP,         // 0x1B00
    BT_GROUP_INDEX_SPP,         // 0x1C00
    BT_GROUP_INDEX_HCI,         // 0x1D00
    BT_GROUP_INDEX_L2CAP,       // 0x1E00
    BT_GROUP_INDEX_GATT,        // 0x1F00
    BT_GROUP_INDEX_GAP,         // 0x2000
    BT_GROUP_INDEX_BAP,         // 0x2100
    BT_GROUP_INDEX_CS,          // 0x2200
    BT_GROUP_INDEX_RAP,         // 0x2300
} bt_event_group_index_t;

#define BT_EVENT_ID_START_BASE 0x1000
#define BT_EVENT_ID_GROUP_DIFF 0x0100
#define BT_EVENT_ID_GROUP_START(idx) (BT_EVENT_ID_START_BASE + (idx) * BT_EVENT_ID_GROUP_DIFF)
#define BT_EVENT_TO_GROUP_MASK(evid) (1 << (((evid&0xff00) - BT_EVENT_ID_START_BASE) / BT_EVENT_ID_GROUP_DIFF))

#define BT_EVENT_MASK_LINK_GROUP        (1<<BT_GROUP_INDEX_LINK)
#define BT_EVENT_MASK_HFP_HF_GROUP      (1<<BT_GROUP_INDEX_HFP_HF)
#define BT_EVENT_MASK_HFP_AG_GROUP      (1<<BT_GROUP_INDEX_HFP_AG)
#define BT_EVENT_MASK_A2DP_SNK_GROUP    (1<<BT_GROUP_INDEX_A2DP_SNK)
#define BT_EVENT_MASK_A2DP_SRC_GROUP    (1<<BT_GROUP_INDEX_A2DP_SRC)
#define BT_EVENT_MASK_AVRCP_GROUP       (1<<BT_GROUP_INDEX_AVRCP)
#define BT_EVENT_MASK_HID_GROUP         (1<<BT_GROUP_INDEX_HID)
#define BT_EVENT_MASK_MAP_GROUP         (1<<BT_GROUP_INDEX_MAP)
#define BT_EVENT_MASK_PBAP_GROUP        (1<<BT_GROUP_INDEX_PBAP)
#define BT_EVENT_MASK_DIP_GROUP         (1<<BT_GROUP_INDEX_DIP)
#define BT_EVENT_MASK_PAN_GROUP         (1<<BT_GROUP_INDEX_PAN)
#define BT_EVENT_MASK_OPP_GROUP         (1<<BT_GROUP_INDEX_OPP)
#define BT_EVENT_MASK_SPP_GROUP         (1<<BT_GROUP_INDEX_SPP)
#define BT_EVENT_MASK_HCI_GROUP         (1<<BT_GROUP_INDEX_HCI)
#define BT_EVENT_MASK_L2CAP_GROUP       (1<<BT_GROUP_INDEX_L2CAP)
#define BT_EVENT_MASK_GATT_GROUP        (1<<BT_GROUP_INDEX_GATT)
#define BT_EVENT_MASK_GAP_GROUP         (1<<BT_GROUP_INDEX_GAP)
#define BT_EVENT_MASK_BAP_GROUP         (1<<BT_GROUP_INDEX_BAP)
#define BT_EVENT_MASK_CS_GROUP          (1<<BT_GROUP_INDEX_CS)
#define BT_EVENT_MASK_RAP_GROUP         (1<<BT_GROUP_INDEX_RAP)

typedef enum {
    BT_EVENT_INVALID_EVENT = 0,

    BT_EVENT_ACL_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_LINK), // 0x1000
    BT_EVENT_ACL_CLOSED,
    BT_EVENT_ACL_CONNECT_REQ,
    BT_EVENT_SCO_OPENED,
    BT_EVENT_SCO_CLOSED,
    BT_EVENT_SCO_CONNECT_REQ,
    BT_EVENT_SCO_CONNECT_FAIL,
    BT_EVENT_ACCESS_CHANGE,
    BT_EVENT_ROLE_DISCOVER,
    BT_EVENT_ROLE_CHANGE,
    BT_EVENT_MODE_CHANGE,
    BT_EVENT_AUTHENTICATED,
    BT_EVENT_ENC_CHANGE,
    BT_EVENT_INQUIRY_RESULT,
    BT_EVENT_INQUIRY_COMPLETE,
    BT_EVENT_BOND_STATE_CHANGE,
    BT_EVENT_PROPERTY_STATE,
    BT_EVENT_LINK_END,

    BT_EVENT_HF_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_HFP_HF), // 0x1100
    BT_EVENT_HF_CLOSED,
    BT_EVENT_HF_AUDIO_OPENED,
    BT_EVENT_HF_AUDIO_CLOSED,
    BT_EVENT_HF_NETWORK_STATE,
    BT_EVENT_HF_NETWORK_ROAMING,
    BT_EVENT_HF_NETWORK_SIGNAL,
    BT_EVENT_HF_BATTERY_LEVEL,
    BT_EVENT_HF_CALL_IND,
    BT_EVENT_HF_CALLSETUP_IND,
    BT_EVENT_HF_CALLHELD_IND,
    BT_EVENT_HF_RING_IND,
    BT_EVENT_HF_CLIP_IND,
    BT_EVENT_HF_CALL_WAITING_IND,
    BT_EVENT_HF_RESP_AND_HOLD,
    BT_EVENT_HF_CURRENT_CALLS,
    BT_EVENT_HF_VOLUME_CHANGE,
    BT_EVENT_HF_AT_CMD_COMPLETE,
    BT_EVENT_HF_CURRENT_OPERATOR,
    BT_EVENT_HF_SUBSCRIBER_INFO,
    BT_EVENT_HF_VOICE_RECOGNITION_STATE,
    BT_EVENT_HF_IN_BAND_RING_STATE,
    BT_EVENT_HF_LAST_VOICE_TAG_NUMBER,
    BT_EVENT_HF_CCLK_TIME,
    BT_EVENT_HF_RECEIVE_UNKNOWN,
    BT_EVENT_HF_END,

    BT_EVENT_AG_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_HFP_AG), // 0x1200
    BT_EVENT_AG_CLOSED,
    BT_EVENT_AG_AUDIO_OPENED,
    BT_EVENT_AG_AUDIO_CLOSED,
    BT_EVENT_AG_VOLUME_CONTROL,
    BT_EVENT_AG_WBS_STATE,
    BT_EVENT_AG_BIA_IND,
    BT_EVENT_AG_BIEV_IND,
    BT_EVENT_AG_DIAL_CALL_REQ,
    BT_EVENT_AG_DIAL_MEMORY_REQ,
    BT_EVENT_AG_CALL_ACTION_REQ,
    BT_EVENT_AG_AT_DTMF_REQ,
    BT_EVENT_AG_AT_BVRA_REQ,
    BT_EVENT_AG_AT_NREC_REQ,
    BT_EVENT_AG_AT_CNUM_REQ,
    BT_EVENT_AG_AT_CIND_REQ,
    BT_EVENT_AG_AT_COPS_REQ,
    BT_EVENT_AG_AT_CLCC_REQ,
    BT_EVENT_AG_AT_CKPD_REQ,
    BT_EVENT_AG_AT_BIND_REQ,
    BT_EVENT_AG_UNKNOWN_AT_REQ,
    BT_EVENT_AG_END,

    BT_EVENT_A2DP_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_A2DP_SNK), // 0x1300
    BT_EVENT_A2DP_CLOSED,
    BT_EVENT_A2DP_STREAM_START,
    BT_EVENT_A2DP_STREAM_RECONFIG,
    BT_EVENT_A2DP_CODEC_INFO,
    BT_EVENT_A2DP_STREAM_SUSPEND,
    BT_EVENT_A2DP_STREAM_CLOSE,
    BT_EVENT_A2DP_STREAM_DATA_IND,
    BT_EVENT_A2DP_CUSTOM_CMD_REQ,
    BT_EVENT_A2DP_CUSTOM_CMD_RSP,
    BT_EVENT_A2DP_END,

    BT_EVENT_A2DP_SOURCE_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_A2DP_SRC), // 0x1400
    BT_EVENT_A2DP_SOURCE_CLOSED,
    BT_EVENT_A2DP_SOURCE_STREAM_START,
    BT_EVENT_A2DP_SOURCE_STREAM_RECONFIG,
    BT_EVENT_A2DP_SOURCE_STREAM_SUSPEND,
    BT_EVENT_A2DP_SOURCE_STREAM_CLOSE,
    BT_EVENT_A2DP_SOURCE_END,

    BT_EVENT_AVRCP_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_AVRCP), // 0x1500
    BT_EVENT_AVRCP_CLOSED,
    BT_EVENT_AVRCP_VOLUME_CHANGE,
    BT_EVENT_AVRCP_PLAY_STATUS_CHANGE,
    BT_EVENT_AVRCP_PLAY_POS_CHANGE,
    BT_EVENT_AVRCP_TRACK_CHANGE,
    BT_EVENT_AVRCP_BATTERY_CHANGE,
    BT_EVENT_AVRCP_RECV_PASSTHROUGH_CMD,
    BT_EVENT_AVRCP_RECV_PLAY_STATUS,
    BT_EVENT_AVRCP_RECV_MEDIA_STATUS,
    BT_EVENT_AVRCP_SEND_KEY_INFO,
    BT_EVENT_AVRCP_GET_COMPANY_ID,
    BT_EVENT_AVRCP_GET_CAPABILITY,
    BT_EVENT_AVRCP_NOTIFY_CHANGE,
    BT_EVENT_AVRCP_ADDRESSED_PLAYER_CHANGED,
    BT_EVENT_AVRCP_BROSING_OPENED,
    BT_EVENT_AVRCP_BROSING_CMD_INFO,
    BT_EVENT_AVRCP_BROSING_RSP_INFO,
    BT_EVENT_AVRCP_BROSING_CLOSED,
    BT_EVENT_AVRCP_OBEX_OPENED,
    BT_EVENT_AVRCP_OBEX_CLOSED,
    BT_EVENT_AVRCP_OBEX_GET_IMAGE_DONE,
    BT_EVENT_AVRCP_OBEX_GET_THM_DONE,
    BT_EVENT_AVRCP_OBEX_GET_IMAGE_PROPERTIES_DONE,
    BT_EVENT_AVRCP_OBEX_EVENT_INFO,
    BT_EVENT_AVRCP_END,

    BT_EVENT_HID_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_HID), // 0x1600
    BT_EVENT_HID_CLOSED,
    BT_EVENT_HID_SENSOR_STATE_CHANGED,
    BT_EVENT_HID_RCV_CTL_DATA,
    BT_EVENT_HID_RCV_INT_DATA,
    BT_EVENT_HID_SDP_REC_DATA,
    BT_EVENT_HID_TXDONE,
    BT_EVENT_HID_END,

    BT_EVENT_MAP_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_MAP), // 0x1700
    BT_EVENT_MAP_CLOSED,
    BT_EVENT_MAP_FOLDER_LISTING_RSP,
    BT_EVENT_MAP_MSG_LISTING_ITEM_RSP,
    BT_EVENT_MAP_GET_MSG_RSP,
    BT_EVENT_MAP_PUT_MSG_RSP,
    BT_EVENT_MAP_READ_STATUS_CHANGED,
    BT_EVENT_MAP_CONVO_LISTING_RSP,
    BT_EVENT_MAP_END,

    BT_EVENT_DIP_START  = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_DIP), // 0x1900
    BT_EVENT_DIP_QUIRED_SUCCESS,
    BT_EVENT_DIP_QUIRED_FAIL,
    BT_EVENT_DIP_END,

    BT_EVENT_SPP_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_SPP), // 0x1C00
    BT_EVENT_SPP_CLOSED,
    BT_EVENT_SPP_END = BT_EVENT_SPP_OPENED + 0xf,

    BT_EVENT_L2CAP_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_L2CAP), // 0x1E00
    BT_EVENT_L2CAP_CLOSED,
    BT_EVENT_L2CAP_END = BT_EVENT_L2CAP_OPENED + 0xf,

    BT_EVENT_GATT_SERV_OPENED = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_GATT), // 0x1F00
    BT_EVENT_GATT_SERV_END = BT_EVENT_GATT_SERV_OPENED + 0xf,

    BT_EVENT_GATT_PROF_OPENED, // 0x1F10
    BT_EVENT_GATT_PROF_CLOSED,
    BT_EVENT_GATT_PROF_END = BT_EVENT_GATT_PROF_OPENED + 0xf,

    BT_EVENT_GAP_EVENT_START = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_GAP), // 0x2000
    BT_EVENT_GAP_EVENT_END = BT_EVENT_GAP_EVENT_START + 0xf,

    BT_EVENT_GAP_ADV_EVENT_START,       // 0x2010
    BT_EVENT_GAP_ADV_EVENT_END = BT_EVENT_GAP_ADV_EVENT_START + 0xf,

    BT_EVENT_GAP_SCAN_EVENT_START,      // 0x2020
    BT_EVENT_GAP_SCAN_EVENT_END = BT_EVENT_GAP_SCAN_EVENT_START + 0xA,

    BT_EVENT_GAP_INIT_EVENT_START = BT_EVENT_GAP_SCAN_EVENT_END + 1,
    BT_EVENT_GAP_INIT_EVENT_END = BT_EVENT_GAP_SCAN_EVENT_START + 0xf,

    BT_EVENT_GAP_CONN_EVENT_START,      // 0x2030
    BT_EVENT_GAP_CONN_EVENT_END = BT_EVENT_GAP_CONN_EVENT_START + 0x1f,

    BT_EVENT_GAP_GLOBAL_EVENT_START,    // 0x2040
    BT_EVENT_GAP_GLOBAL_EVENT_END = BT_EVENT_GAP_GLOBAL_EVENT_START + 0xf,

    BT_EVENT_GAP_PA_SYNC_EVENT_START,      // 0x2050
    BT_EVENT_GAP_PA_SYNC_EVENT_END = BT_EVENT_GAP_PA_SYNC_EVENT_START + 0xf,

    BT_EVENT_BAP_EVENT_START = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_BAP),
    BT_EVENT_BAP_EVENT_END = BT_EVENT_BAP_EVENT_START + 0xf,

    BT_EVENT_CS_EVENT_START = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_CS),
    BT_EVENT_CS_EVENT_END   = BT_EVENT_CS_EVENT_START + 0x1f,

    BT_EVENT_RAP_EVENT_START = BT_EVENT_ID_GROUP_START(BT_GROUP_INDEX_RAP),
    BT_EVENT_RAP_EVENT_END   = BT_EVENT_RAP_EVENT_START + 0xf,
} BT_EVENT_T;
/***************************** variable defination *****************************/

/***************************** function declaration ****************************/


#ifdef __cplusplus
}
#endif

#endif /* __BT_STACK_EVENT_H__ */