KBUILD_CPPFLAGS += -DCHIP_BEST1503P
export CHIP_HAS_USB := 0
export CHIP_HAS_USBPHY := 0
export CHIP_HAS_CP := 1
export CHIP_HAS_PSRAM := 1
CHIP_HAS_DAC_FIFO := 2
CPU := m33
export CHIP_HAS_FPU := 1
ifneq ($(CHIP_ROLE_CP),1)
endif
export CHIP_HAS_I2S_TDM_TRIGGER := 1
export CHIP_HAS_PSC := 1
export CHIP_HAS_EXT_PMU := 0
export CHIP_FLASH_CTRL_VER := 9
export CHIP_PSRAM_CTRL_VER := 11
export CHIP_PSRAM_PHY_VER := 11
export PSRAM_CLASSIFY ?= XOPI
export PSRAM_X8_MODE ?= 1
export CHIP_SPI_VER := 6
ifeq ($(GRAPH_MODULE),1)
export CHIP_HAS_GPU := 1
export CHIP_HAS_LCDC := 1
export CHIP_HAS_JPEG := 1
endif
export CHIP_CACHE_VER := 5
export CHIP_INTERSYS_VER := 2
export CHIP_GPIO_VER := 2
export PSC_GPIO_IRQ_CTRL := 1
export CHIP_RAM_BOOT := 1
export CHIP_HAS_EC_CODEC_REF := 1
export CHIP_HAS_SCO_DMA_SNAPSHOT := 1
export CHIP_ROM_UTILS_VER := 2
export CHIP_HAS_SECURE_BOOT := 1
export CHIP_HAS_ANC_HW_GAIN_SMOOTHING := 1
export CHIP_BT_CLK_UNIT_IN_HSLOT := 1
export CHIP_HAS_MULTI_DMA_TC := 1
export CHIP_HAS_SUPPORT_ME_MEDIATOR := 1
export PMU_IRQ_UNIFIED ?= 1
export PMU_FORCE_LP_MODE ?= 1
export BOOT_LOADER_ENTRY_HOOK ?= 1
export PROGRAMMER_BOOT_ENTRY_HOOK ?= 1

ifeq ($(CP_INTR_RELAY),1)
KBUILD_CPPFLAGS += -DCP_INTR_RELAY
KBUILD_CPPFLAGS += -DMCU_RAM_CE_ALWAYS_ON
endif

ifeq ($(RC_FAST_WAKEUP),1)
export RC_SLOW_CLK_MHZ := 2
export RC_SLOW_CLK_ENABLE := 1
endif

ifeq ($(PMU_CLK_USE_EXT_CRYSTAL),1)
export CONFIG_SYSTICK_HZ_NOMINAL := 32768
else
export CONFIG_SYSTICK_HZ_NOMINAL := 32000
endif
KBUILD_CPPFLAGS += -DCONFIG_SYSTICK_HZ_NOMINAL=$(CONFIG_SYSTICK_HZ_NOMINAL)
