cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

obj-y :=
obj-y += ConvolutionFunctions/
obj-y += FullyConnectedFunctions/
obj-y += MultiHeadAttentionFunctions/
obj-y += NNSupportFunctions/
obj-y += RNNFunctions/
obj-y += PoolingFunctions/
obj-y += MVERequantFunctions/
