############ RAM OPTIMIZE ############
export USE_BASIC_THREADS ?= 1
export SCO_OPTIMIZE_FOR_RAM ?= 1
export BT_USE_COHEAP_ALLOC  ?= 1
export UNIFY_HEAP_ENABLED ?= 1
export FAST_RAM_OPTIMIZE ?= 0
export USE_OVERLAY_TXT_GAP ?= 0
########## RAM OPTIMIZE END ##########

ifeq ($(A2DP_CP_ACCEL),1)
export RAMCP_SIZE :=  0x38000
ifeq ($(AAC_BECO_FFT),1)
export RAMCPX_SIZE := 0xA800
else
ifeq ($(SPEECH_TX_2MIC_NS8), 1)
export RAMCPX_SIZE := 0xE000
else ifeq ($(SPEECH_TX_1MIC_NS), 1)
export RAMCPX_SIZE := 0xE000
else
export RAMCPX_SIZE := 0xA000
endif
endif

ifeq ($(SBC_REDUCE_SIZE),1)
export FAST_XRAM_SECTION_SIZE ?= 0x4000
else
ifeq ($(SPEECH_ALGO_IN_ROM),1)
export FAST_XRAM_SECTION_SIZE ?= 0x1400
else
export FAST_XRAM_SECTION_SIZE ?= 0x2300
endif
endif
else
export RAMCP_SIZE := 0
export RAMCPX_SIZE := 0
ifeq ($(SBC_REDUCE_SIZE),1)
export FAST_XRAM_SECTION_SIZE ?= 0xCC00
else
export FAST_XRAM_SECTION_SIZE ?= 0x9C00
endif
endif

ifeq ($(USE_BASIC_THREADS),1)
ifeq ($(TOTA_v2),1)
BESBT_STACK_SIZE := 1024*4
else
ifeq ($(BLE_AUDIO_ENABLED),1)
BESBT_STACK_SIZE := 1024*3
else
BESBT_STACK_SIZE := 1024*2+512
endif
endif
KBUILD_CPPFLAGS += -DAF_STACK_SIZE=1024*3+512
ifeq ($(DIRAC_AUDIO_ENABLE),1)
KBUILD_CPPFLAGS += -DAPP_THREAD_STACK_SIZE=1024*3
else
KBUILD_CPPFLAGS += -DAPP_THREAD_STACK_SIZE=1024*2
endif
KBUILD_CPPFLAGS += -DINTERSYS_STACK_SIZE=1024
export OS_TIMER_THREAD_STACK_SIZE ?= 0x800
endif
export OS_DYNAMIC_MEM_SIZE ?= 0x6000
export CP_IN_CACHE_SIZE := 1024*3

KBUILD_CPPFLAGS += -DFAST_XRAM_SECTION_SIZE=$(FAST_XRAM_SECTION_SIZE)
KBUILD_CPPFLAGS += -DRAMCP_SIZE=$(RAMCP_SIZE)
KBUILD_CPPFLAGS += -DRAMCPX_SIZE=$(RAMCPX_SIZE)
KBUILD_CPPFLAGS += -DCP_IN_CACHE_SIZE=$(CP_IN_CACHE_SIZE)
